### ISSUE TITLE
After installing tflearn, the tensorflow have a numpy error

### ISSUE THREAD

**Issue by lfwin** [tflearn/tflearn#1]
>>> import tensorflow as tf
RuntimeError: module compiled against API version a but this version of numpy is 9
...
    _pywrap_tensorflow = swig_import_helper()
  File "/home/mvg/tensorflow/_python_build/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: numpy.core.multiarray failed to import

**Comment by aymericdamien** [comment]
What is your numpy version? It seems that it is too old.

You can try to re-install numpy:
```python
pip uninstall numpy

pip install numpy
```

**Comment by lfwin** [comment]
Hi, Solved, I installed two numpy in my ubuntu14.04, now solved by 'aptitude purge python-numpy'.
Thanks.
