### ISSUE TITLE
Calling model.predict() from multiple processes

### ISSUE THREAD

**Issue by Rampagy** [tflearn/tflearn#1037]
Maybe this is an issue with my implementation, tflearn or tensorflow, I guess I am not sure.  The code hangs when I call `model.predict()` in multiple processes, but I know the exact same code works when evaluated in a single process.  [See my reproduction steps here](https://github.com/Rampagy/InvertedPendulum/tree/master/testing/multiprocessing).

I know I have seen [lots of issues with tensorflow](https://github.com/tensorflow/tensorflow/issues/8220) hanging when trying to predict within multiple processes, so I am not sure if this is a tflearn issue or a tensorflow issue.

**Comment by Rampagy** [comment]
Dang.  Thanks for looking into it.

**Comment by Lancerchiang** [comment]
@Rampagy Hi please refer to the solution I wrote for this issue #8220
