### ISSUE TITLE
constructed path not passed to the function

### ISSUE THREAD

**Issue by psnegi** [tflearn/tflearn#104]
In file 
https://github.com/tflearn/tflearn/blob/master/tflearn/datasets/oxflower17.py
line 29 is dataset_file="17flowers.pkl".
 It should be dataset_file= dataset_file
 based on path construction at line 22

**Comment by aymericdamien** [comment]
Hi, thanks for reporting that issue, can you send a pull-request to fix it?
Otherwise I will update code later.

**Comment by aymericdamien** [comment]
Already fixed
