### ISSUE TITLE
lstm imdb example

### ISSUE THREAD

**Issue by vinayakumarr** [tflearn/tflearn#106]
I have data set which is given below
1 i feel happy
2 i feel sad

first column class label and second column text and i would like to apply imdb lstm example how to convert these text to numeric. In our example you are reading pickle file and that contains numeric value. so how to convert these text to numeric

**Comment by aymericdamien** [comment]
you can create a dictionary that assign a unique number to a word, for example:
'I' -> 1
'am' -> 2
'here' -> 3
etc...
Then you can represent any sentence as a list of number instead of a list of words.

**Comment by vinayakumarr** [comment]
Thank you, I have seen skflow example in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/skflow/text_classification.py

Like this,Is there any option to read text file directly and to apply imdb lstm example?
