### ISSUE TITLE
17 Category Flower Dataset build_class_directories bug

### ISSUE THREAD

**Issue by panovr** [tflearn/tflearn#108]
I‘m doing experiment with 17 Category Flower Dataset example by running alexnet.py.
After downloading 17flowers.tgz file, it will untar the tgz file and invoke "build_class_directories" in file "oxflower17.py".
It seems there is a bug in "build_class_directories" function: after the class directories have been created,  the first directory "0" has only 79 images, and the last directory "16" has 81 images. However, the 17 Category Flower Dataset has 80 images for every class.
I believe that this bug is related to https://github.com/tflearn/tflearn/blob/master/tflearn/datasets/oxflower17.py#L62
It means that if i divide 80 equals 0, then new class directory will be created. But the 80th image will be move to "1" directory, and that is not correct.

**Comment by aymericdamien** [comment]
Thanks for reporting that issue, it indeed seem there is a bug here. Would you mind to push a PR to correct that bug if you already got a fix? Otherwise I will update code later.

**Comment by panovr** [comment]
I will push a PR.

**Comment by aymericdamien** [comment]
Great, thanks :)

**Comment by panovr** [comment]
I have pushed a PR, and please review the code.

**Comment by aymericdamien** [comment]
Great, it is working well, thanks :)

**Comment by atg1207** [comment]
Hey, I am not able to extract the dataset file. Can somebody help me out?
