### ISSUE TITLE
max_checkpoints cannot save my best model

### ISSUE THREAD

**Issue by ikingkong876** [tflearn/tflearn#1087]
I set max_checkpoints=5 as the code:
    `trainer = tflearn.helpers.trainer.Trainer(train_ops=trainop, tensorboard_verbose=0, max_checkpoints=5,                                                  tensorboard_dir='./tmp/tflearn_logs', best_val_accuracy=0.6,                                                  best_checkpoint_path='./Best_Model/{}'.format(m_f),                                                  checkpoint_path='./Checkpoint_Model/{}'.format(m_f))`
and in the folder Best_Model and Checkpoint_Model, there are only 5 files in folder Checkpoint_Model, nothing is in the folder Best_Model.
How can i keep the best model in Best_Model and another lastest 5 model in Checkpoint_Model?

**Comment by ztlevi** [comment]
How did you solve this problem? I am facing exact the same issue.
