### ISSUE TITLE
One of the activation function parameters, 'selu' be generates an error.

### ISSUE THREAD

**Issue by sunwoolee** [tflearn/tflearn#1092]
I am currently using version 1.9 of tensorflow, and version tflearn is using version 0.32.
One of the activation function parameters of tflearn, selu does not work properly.
The symptoms are as follows.
x = tflearn.conv_2d(_input, 16, 3, activation='selu', scope='conv1_1')
-> TypeError: expected string or bytes-like object
So I did the following processing.
Move to the location where tflearn is installed and change it to 'return scale * tf.nn.elu (x, alpha)' to 'return tf.nn.selu (x)' in 'activations.py'.
![image](https://user-images.githubusercontent.com/12380660/46884186-333bc380-ce8f-11e8-97d8-952be40a9d88.png)

**Comment by aymericdamien** [comment]
Thanks! Now that tf supports SELU, I updated the ops.
