### ISSUE TITLE
Is dynamic_rnn supported?

### ISSUE THREAD

**Issue by jinghuangzhu** [tflearn/tflearn#110]
Hi, I found you have dynamic_rnn in your recurrent.py, but did not find any example how to use it.
In example lstm.py, it used "lstm" class in recurrent.py, which just used "_rnn" instead of "dynamic_rnn".
So there is no way for me to use "dynamic_rnn" now?

Another question: if my input is [None, 300, 400], and the lstm size is 256, does "lstm" class take care of linearly transforming the input size 400 to match lstm size 256? 

Thanks for help.

**Comment by aymericdamien** [comment]
Currently dynamic_rnn has some issues, so it is not supported. We will wait next TFLearn version to revise it.

However, as TensorFlow supports dynamic calculation for its base 'rnn' function, you may directly use TFLearn layers, such as `lstm`, and assign a placeholder to argument `sequence_length` (that represents a list of each sequence length in the batch). Unfortunately `DNN` class doesn't handle it yet, so you must write your own training process (see this example for some hints: https://github.com/tflearn/tflearn/blob/master/examples/extending_tensorflow/layers.py)

I updated TFLearn code to support 'sequence_length', so you may reinstall TFLearn (pip uninstall/install).

**Comment by jinghuangzhu** [comment]
Thanks for replying.
In your example lstm.py, it pads zeros to make sequences equal length. Without sequence_length input to _rnn, how does it handle the padded zeros?

**Comment by jinghuangzhu** [comment]
Forgot to ask: what issues with dynamic_rnn in tensorflow? Thanks.

**Comment by aymericdamien** [comment]
Issue is related to TFLearn `DNN` class, that doesn't handle different sequence length, there is no issue with TensorFlow. So it means you can still build your network with TFLearn, but you have to write your own function to train model and feed data.

**Comment by aymericdamien** [comment]
@jinghuangzhu Dynamic RNNs are now supported, see:
https://github.com/tflearn/tflearn/blob/master/examples/nlp/dynamic_lstm.py
