### ISSUE TITLE
how to get the output of any specific layer

### ISSUE THREAD

**Issue by WuChannn** [tflearn/tflearn#1105]
I am trying to get the output of a fully-connected layer, but i can't find any api I can use. can anyone help me? thank u

**Comment by dushwe** [comment]
do you solve the problem

**Comment by WuChannn** [comment]
yeah, you can just define the model whose last layer is the layer you want to output, and then load the model you pretrain------------------ Original ------------------From: dushwe  <notifications@github.com>Date: Mon,Jan 7,2019 11:46 AMTo: tflearn/tflearn <tflearn@noreply.github.com>Cc: WuChannn <wuzchng@gmail.com>, State change <state_change@noreply.github.com>Subject: Re: [tflearn/tflearn] how to get the output of any specific layer(#1105)do you solve the problem

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tflearn/tflearn","title":"tflearn/tflearn","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/tflearn/tflearn"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dushwe in #1105: do you solve the problem"}],"action":{"name":"View Issue","url":"https://github.com/tflearn/tflearn/issues/1105#issuecomment-451813915"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/tflearn/tflearn/issues/1105#issuecomment-451813915",
"url": "https://github.com/tflearn/tflearn/issues/1105#issuecomment-451813915",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
