### ISSUE TITLE
picle file in nlp examples

### ISSUE THREAD

**Issue by vinayakumarr** [tflearn/tflearn#117]
I have data which contains positive, negative and neutral text files and i would like to convert it into the imdb.pkl format. how to do that? Do you have any basic code for this and i think this will be help full for beginners to apply your nlp examples on their own data set.

**Comment by aymericdamien** [comment]
You can use:
```
import pickle
x = ...
with open('file_path', 'wb') as f:
    f.dump(x)
```

**Comment by guotong1988** [comment]
How to convert the `imdb.pkl` to txt file? I want to see what is in it. Thank you @aymericdamien @vinayakumarr
