### ISSUE TITLE
Text classification

### ISSUE THREAD

**Issue by vinayakumarr** [tflearn/tflearn#124]
I have dataset which has positive and negative tweets and I want to push these data to IMDb as input. Could you please tell how to do this, sample data which is given below,.                                                Positive.     He got appraisal from others.                    Negative.     The movie was not good

**Comment by aymericdamien** [comment]
So what you have to do is:
- First make a dictionary of words where you assign an integer to every word, starting from 1. So you can first input all your tweets, split them to get words (split(" ")) and then you read all words of your dataset:
```
corpus = ... # an array of tweets
dictionary = {}
i = 1
for tweet in corpus:
  for word in tweet.split(" "):
    if words not in dictionary: dictionary['word'] = i
    i += 1

# Then parse a new tweet with:
tweet = ..... # your new tweet
tweet_parsed = list()
for word in tweet.split(" "):
  if word in dictionary:
    tweet_parsed.append(dictionary['word'])
  else:
    tweet_parsed.append(len(dictionary)) # last id is unknown word
```
- Choose a max sequence length and pad you sequences according to that (tflearn.data_utils.pad_sequence)
- just replace X and Y in the imdb example by your own data, and replace the embedding 'input_dim=20000' by the dictionary size (input_dim=len(dict)+1).

**Comment by aymericdamien** [comment]
For simplicity, I mirrored TensorFlow `VocabularyProcessor` class that does what you need:
```
tweets = your_list_of_tweets(strings)
max_tweet_length = 120
min_frequency = 2 # Minimum number of time a word should occur to be incoroporated inside the dictionary
vp = tflearn.data_utils.VocabularyProcessor(max_tweet_length, min_frequency=min_frequency)
vp = vp.fit(tweets)
tweets_parsed = vp.transform(tweets)
vp.save('my_dictionary') # Save so that can be loaded later

trainX = tweets_parsed
trainY = YOUR_LABELS_LIST # you can use tflearn.data_utils.to_categorical(trainY, NUM_CLASSES) if you are using categoirical_crossentropy

# model
....
```

**Comment by vinayakumarr** [comment]
from __future__ import print_function
import numpy as np
import tflearn
import pandas as pd
from tflearn.data_utils import to_categorical, pad_sequences

with open('1.txt') as f:
    content = f.readlines()

with open('2.txt') as f:
    content1 = f.readlines()

tweets = content
max_tweet_length = 120
min_frequency = 2
vp = tflearn.data_utils.VocabularyProcessor(max_tweet_length, min_frequency=min_frequency)
vp = vp.fit(tweets)
tweets_parsed = vp.transform(tweets)
vp.save('my_dictionary')

trainX = tweets_parsed
trainY = tflearn.data_utils.to_categorical(content1, nb_classes=0)

net = tflearn.input_data([None, 120])
net = tflearn.embedding(net, input_dim=2, output_dim=128)
net = tflearn.lstm(net, 128)
net = tflearn.dropout(net, 0.5)
net = tflearn.fully_connected(net, 2, activation='softmax')
net = tflearn.regression(net, optimizer='adam',loss='categorical_crossentropy')

model = tflearn.DNN(net, clip_gradients=0., tensorboard_verbose=0)
model.fit(trainX, trainY, show_metric=True, batch_size=128)

generates the following error
if i uses input_dim=np.max(trainX)+1, also generate same error. I came to know by searching in google i.e. trainX is a generator

filtered_gen = (item for item in trainX)
gen_to_list = list(filtered_gen)
print(len(gen_to_list))

after this what i need to do. Whether i need to use pad_sequence?
![untitled](https://cloud.githubusercontent.com/assets/18217467/15788817/f454f71c-29e6-11e6-8006-7837c04460dd.png)

**Comment by vinayakumarr** [comment]
generates the above error. Can you just tell how to correct this?

**Comment by aymericdamien** [comment]
It means that your input_dim of embedding layter is wrong. Maybe try:
```
net = tflearn.embedding(net, input_dim=val+2, output_dim=64)
```

**Comment by vinayakumarr** [comment]
No, generates same error

**Comment by vinayakumarr** [comment]
I have been trying to correct it. But I am getting same embedding error. Is it possible to remove embedding layer and work it out

**Comment by aymericdamien** [comment]
Oh, the error is that you didn't compute the right dictionary length, it should be:
```
# val = len(vp.dictionary)
net = tflearn.embedding(net, input_dim=len(vp.dictionary), output_dim=64)
```

**Comment by vinayakumarr** [comment]
generates the following error
TypeError: object of type 'VocabularyProcessor' has no len()

**Comment by aymericdamien** [comment]
ops, yes, it should be `vp.vocabulary_`
```
vp = tflearn.data_utils.VocabularyProcessor(max_tweet_length, min_frequency=min_frequency)
vp = vp.fit(tweets)
val = len(vp.vocabulary_)
```

**Comment by vinayakumarr** [comment]
Thanks, it works but accuracy is only 60 percentage. Do you know how to fine tune this. Currently i am using one memory blocks. If i increase the memory blocks, is there any possibility in increasing accuracy. I am working on preparing data set.I will finish this within 5 days. Once it works fine shall i share it with you. Is there any possibility that you will include in tflearn examples?

**Comment by aymericdamien** [comment]
Maybe you can combine different LSTM layers, also tries to add more features. Also compare your training loss and validation loss, maybe your are overfitting. If the dataset is public, then we could add that example :)

**Comment by vinayakumarr** [comment]
yes, we make data set is public and i will try multiple LSTM layers and bidirectional_rnn to improve accuracy. I would like to know how to add more feature. whether i should use word2vec or glove embedding

**Comment by inancarin** [comment]
Hi,

When I try following code, I am getting this error, what I am doing wrong?

Thanks,
Inanc

_Traceback (most recent call last):
  File "text_classification_sample.py", line 67, in <module>
    batch_size=32)
  File "/Users/inanc/anaconda/envs/tensorflow/lib/python2.7/site-packages/tflearn/models/dnn.py", line 213, in fit
    callbacks=callbacks)
  File "/Users/inanc/anaconda/envs/tensorflow/lib/python2.7/site-packages/tflearn/helpers/trainer.py", line 253, in fit
    self.summ_writer, self.coord)
  File "/Users/inanc/anaconda/envs/tensorflow/lib/python2.7/site-packages/tflearn/helpers/trainer.py", line 694, in initialize_fit
    self.n_train_samples = len(get_dict_first_element(feed_dict))
TypeError: object of type 'generator' has no len()_

```
max_tweet_length = 120
min_frequency = 2 # Minimum number of time a word should occur to be incoroporated inside the dictionary
vp = tflearn.data_utils.VocabularyProcessor(max_tweet_length, min_frequency=min_frequency)
vp = vp.fit(allDocuments)
tweets_parsed = vp.transform(allDocuments)

trainX = tweets_parsed
trainY = to_categorical(allLabels, nb_classes=2)

net = tflearn.input_data([None, max_tweet_length])
val = len(vp.vocabulary_)
net = tflearn.embedding(net, input_dim=val+2, output_dim=128)
net = tflearn.lstm(net, 128, dropout=0.8)
net = tflearn.fully_connected(net, 2, activation='softmax')
net = tflearn.regression(net, optimizer='adam', learning_rate=0.001,
                         loss='categorical_crossentropy')

# Training
model = tflearn.DNN(net, tensorboard_verbose=0)
model.fit(trainX, trainY, validation_set=(trainX, trainY), show_metric=True,
          batch_size=32) # I know validation and training are same here

```

**Comment by yunitata** [comment]
Hi, 

I've been trying to re-implement the code for other datasets. 
I have two questions:
1. In my case I want to decrease the vocabulary size (number of words). Have been looking for the documentation but can't find it
in scikit learn I could do it by easily run this code, 
`word_vectorizer = CountVectorizer(analyzer='word', max_features=700, max_df=0.95, min_df=2, ngram_range=(1,1))`
Is there anyway I can do it in tensorflow?

2. How to set vocabulary argument in VocabularyPreprocessor? 

Thanks!
