### ISSUE TITLE
Deep residual block always uses a projection instead of identity

### ISSUE THREAD

**Issue by daviddao** [tflearn/tflearn#13]
Refering to this line: https://github.com/tflearn/tflearn/blob/master/tflearn/layers/conv.py#L617.
Because it is connected to the two high-dimensional ends, it doubles model size and the time to train a residual net according to He _et al._ . 

I guess you want to do this instead:

```python
# Projection to new dimension
                if in_channels != out_channels:
                    identity = conv_2d(identity, out_channels, 1, 1, 'same',
                                       'linear', bias, weights_init,
                                       bias_init, regularizer, weight_decay,
                                       trainable, restore)
```

Or an additional parameter called `projection=False` in the function arguments. I can submit a PR if you want.

**Comment by aymericdamien** [comment]
ops.. yes, this is a mistake, this should be `if in_channels != out_channels:` instead of `else`. You can submit a PR to correct that, thanks!

**Comment by daviddao** [comment]
Done! Thanks for the quick responses!
