### ISSUE TITLE
3d operations support

### ISSUE THREAD

**Issue by aymericdamien** [tflearn/tflearn#136]
Now that tensorflow has 3d operation supports, we can add:
- conv3d, avg_pool3d, max_pool3d

See: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/nn.py

If anyone want to help and add these layers in 'tflearn/layers/conv.py' :)

**Comment by ranarag** [comment]
features added in pull request  #142.

**Comment by aymericdamien** [comment]
Great job!
