### ISSUE TITLE
Loading weights from npy [question]

### ISSUE THREAD

**Issue by FreakTheMighty** [tflearn/tflearn#139]
I'm working on an FCN example based on the new `upscore_layer` https://github.com/FreakTheMighty/tflearn/tree/fcn-example. I'd like to start by getting inference working using the weights provided in `tensorflow-fcn` [here](https://dl.dropboxusercontent.com/u/50333326/vgg16.npy), but I'm struggling to figure out how to assign the weights in the `npy` to the tf model. It appears that in `tensorflow-fcn`, @MarvinTeichmann initializes the `conv2d` layers with the loaded weights, but that doesn't seem like a typical flow in tflearn.

I would very much appreciate some guidance on this, how might I go about loading these weights?

Thanks in advance!

**Comment by FreakTheMighty** [comment]
I got a bit further. I now realize that I can pass a tensor into `weights_init`. I ran into the attached error. The error makes sense, but I wonder if `conv_2d` should ignore shape if `weights_init` is a tensor.

```
Traceback (most recent call last):
  File "./vgg_fcn_network.py", line 51, in <module>
    network = conv_2d(network, 64, 3, activation='relu', weights_init=get_conv_filter('conv1_1'))
  File "/Users/jvanderdoes/Code/tflearn/tflearn/layers/conv.py", line 79, in conv_2d
    trainable=trainable, restore=restore)
  File "/Users/jvanderdoes/Code/tflearn/tflearn/variables.py", line 54, in variable
    collections=collections)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 339, in get_variable
    collections=collections)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 262, in get_variable
    collections=collections, caching_device=caching_device)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 103, in get_variable
    raise ValueError("If initializer is a constant, do not specify shape.")
ValueError: If initializer is a constant, do not specify shape.
```

**Comment by aymericdamien** [comment]
I updated TFLearn source code to disable shape if you use a Tensor to initialize. Can you check again if that fix your issue?

**Comment by FreakTheMighty** [comment]
That worked, thanks!

**Comment by ywangeq** [comment]
@FreakTheMighty , hello i tried your example of fcn, however when i get the output, it doesn't has the same shape as the original image, i think this is wrong according to the fcn. can you help me check it ?

Thanks!

**Comment by FreakTheMighty** [comment]
hey @ywangeq I never did get my example working and its been quite some times sines I worked on it, so I won't be much help.
