### ISSUE TITLE
Data augmentation image flip UPDOWN seems to use LEFTRIGHT flipping

### ISSUE THREAD

**Issue by flor385** [tflearn/tflearn#141]
In `tflearn/data_augmentation` the `add_random_flip_updown` method calls `self.methods.append(self._random_flip_leftright)`... The `tflearn/data_augmentation:_random_flip_updown` function is not used anywhere in that file.

**Comment by aymericdamien** [comment]
Thanks for reporting that bug, it is indeed applying leftright instead of updown.
I just fixed it. You can reinstall tflearn.
