### ISSUE TITLE
Using tflearn in conda virtual environment

### ISSUE THREAD

**Issue by andrisan** [tflearn/tflearn#143]
I tried to use tflearn in conda virtual environment.

**`source activate <environment_name>`
`python`
`>>>import tflearn`**

And it gave me the error of **Segmentation fault**, after tensorflow library is loaded:

```
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
Segmentation fault (core dumped)
```

and then python exits

**Comment by aymericdamien** [comment]
Arf, these kind of errors are difficult to track. I will try to reproduce it.
Is it working when you are not using virtual environment?

**Comment by andrisan** [comment]
I haven't tried to install tflearn in system environment, as I installed tensorflow in the virtual environment. I think it defeats the purpose of isolated system that I want to achieve in the first place, if I install tflearn and tensorflow in the system environment.

Another articles I found suggest to install h5py and hdf5, and I tried to install those twos using:

```
conda install h5py
conda install hdf5
```

And the problem still exists

**Comment by XiaolongMeng** [comment]
I have this issue too,when I use tensorflow it works ,but when import tflearn ,it show Segmentation fault and break

**Comment by yfor1008** [comment]
hi all, have you fixed this issue. i also have this issue when i finish training and testing, not  when import
