### ISSUE TITLE
`tf.Tensor` as a Python `bool` is not allowed

### ISSUE THREAD

**Issue by Tallic** [tflearn/tflearn#149]
tflearn/layers/core.py triggers an "'tf.Tensor' as a Python 'bool' is not allowed" error if the _input_data_ gets a placeholder tensor.

Lines that trigger the error are 55 and 58. Rewrite the boolean check for the placeholder to `is None`.

**Comment by aymericdamien** [comment]
Thanks for reporting that issue, could you send a pull request to fix it? Otherwise I will correct it in the next update.

**Comment by facundoq** [comment]
@aymericdamien was this merged in master? Using the `bleeding edge` version with `pip install git+https://github.com/tflearn/tflearn.git` I get the same error and need to modify those lines as well.
