### ISSUE TITLE
Resnet example raises tensorflow error: stride must be less than or equal to kernel size

### ISSUE THREAD

**Issue by Jothecat** [tflearn/tflearn#152]
Hi!

I'm trying to run the resnet example, and I found out that in the residual block, when downsample = True is added, tensorflow will raise the error while calculating the average pooling gradient, since tensorflow do not allow the stride to be 2 when doing 1x1 convolution.

I've used the provided wheel to update tensorflow but still doesn't work. Any suggestions?

Best Regards
Jo

**Comment by aymericdamien** [comment]
You have to update TensorFlow to the latest version. In old version, TensorFlow doesn't support a stride less or equal to kernel size.

**Comment by rnditdev** [comment]
I compiled head from source for both TF and TFLearn, the ResNet example give the error referenced in the report.

**Comment by aymericdamien** [comment]
It may link to some changes in TensorFlow code. Can you try with TensorFlow 0.9?

**Comment by rnditdev** [comment]
I've tested on 0.9, and head, doesn't work In either one.

**Comment by aymericdamien** [comment]
Are you trying to run on CPU or GPU, I recall I ran into a similar strange issue; it couldn't run on CPU because of this kernel size issue, but it was fine on GPU.

**Comment by rnditdev** [comment]
I ran it on CPU, maybe it's time to fill a bug with TF ?

**Comment by jakubsimanek** [comment]
This is still an issue on CPU even with TF 0.11 and [latest](https://github.com/tflearn/tflearn/commit/433c75983ad21f122c2750cdff2076f047b760b9) tflearn. GPU version is fine.

```
tensorflow.python.framework.errors.InvalidArgumentError: stride must be less than or equal to kernel size
	 [[Node: Momentum/gradients/ResidualBlock_3/AvgPool2D/AvgPool_grad/AvgPoolGrad = AvgPoolGrad[T=DT_FLOAT, data_format="NHWC", ksize=[1, 1, 1, 1], padding="SAME", strides=[1, 2, 2, 1], _device="/job:localhost/replica:0/task:0/cpu:0"]
```

**Comment by mohamaddanesh** [comment]
I still have the same issue using Tensorflow 1.0.0 and TFLearn 0.3

`tensorflow.python.framework.errors_impl.InvalidArgumentError: stride must be less than or equal to kernel size
	 [[Node: Momentum/gradients/ResNeXtBlock_3/AvgPool2D/AvgPool_grad/AvgPoolGrad = AvgPoolGrad[T=DT_FLOAT, data_format="NHWC", ksize=[1, 1, 1, 1], padding="SAME", strides=[1, 2, 2, 1], _device="/job:localhost/replica:0/task:0/cpu:0"](Momentum/gradients/ResNeXtBlock_3/AvgPool2D/AvgPool_grad/Shape, Momentum/gradients/ResNeXtBlock_3/Pad_grad/Slice_1)]]
`
