### ISSUE TITLE
A little help with SequenceGenrator and lstm

### ISSUE THREAD

**Issue by BeasT321** [tflearn/tflearn#154]
Hi, 

I am new to deep learning and have only decent knowledge of neural network and theano. I am starting to develop a lstm network with my own dictionary (which have three words as of now), and the input and output is totally based on trail and error. The program is working if I only use char in dictionary, but I want to use strings. Here is the code:

`
import tflearn                                                                            
X = [[[1,0,0]],[[0,1,0]],[[0,0,1]]]
Y = [[0,1,0],[0,0,1],[1,0,0]]
dict = {'test ':0,'python ':1,'love ':2}
g = tflearn.input_data([None,  1,3])                                                      
g = tflearn.lstm(g, 10, return_seq=True)                                                  
g = tflearn.lstm(g, 10)                                                                   
g = tflearn.fully_connected(g, 3, activation='softmax')                                   
g = tflearn.regression(g, optimizer='adam', loss='categorical_crossentropy',                                     learning_rate=0.001)                                               
m = tflearn.SequenceGenerator(g , dictionary=dict,seq_maxlen=1,  clip_gradients=5.0,                             checkpoint_path='model_shakespeare')

m.fit(X, Y, validation_set=0.1, batch_size=128,
          n_epoch=1, run_id='shakespeare')
seed = ['love ']
print("-- TESTING...")
#print ("predict :")
#print (m.predict(seed))
print("-- Test with temperature of 1.0 --")
print(m.generate(6, temperature=1.0, seq_seed=seed))
print("-- Test with temperature of 0.5 --")
print(m.generate(6, temperature=0.5, seq_seed=seed))
`

This gives me the following error:

`Traceback (most recent call last):
  File "lstm.py", line 28, in <module>
    print(m.generate(6, temperature=1.0, seq_seed=seed))
  File "/usr/local/lib/python2.7/dist-packages/tflearn/models/generator.py", line 221, in generate
    sequence = sequence[1:] + next_char
TypeError: can only concatenate list (not "str") to list
`

Replacing the string (test,python,love) with (a,b,c) and changing seed to a string gives me no error. What I think is either the generate() doesn't support a string dictionary  **OR** I am doing something wrong. 

I have tried many trial-error modification to try to fix this , nothing worked out. 

Thanx in advance :)

**Comment by aymericdamien** [comment]
I think the error is due to the fact that seed should be a string and not a list.

**Comment by BeasT321** [comment]
I tried that, in that case it tries to iterate each character and ends up with error 
'L' not found in dictionary.

**Comment by aymericdamien** [comment]
Arf yes, generator with created to handle char, and seem that it is not compatible with list.
Can you try to change: https://github.com/tflearn/tflearn/blob/master/tflearn/models/generator.py#L218 into:
```
next_char = [self.rev_dic[next_index]]
```
Basically, the error says that you try to concatenate the seed (a list) with a string ('next_char', the predicted next id)
I can try to debug that as soon as I get a computer.

**Comment by BeasT321** [comment]
hi, thanx for the suggestion. 

`next_char = [self.rev_dic[next_index]]`

worked, but I had to change 

`generated = seq_seed
 sequence = seq_seed
 whole_sequence = seq_seed`

to 

`        generated = list(seq_seed)
        sequence = list(seq_seed)
        whole_sequence = list(seq_seed)`

since list in python works as a pointer, so I have to make a new list. Rest all code is fine. Right now trying with a larger dataset to see if it really works. Thanx for the help :+1:

**Comment by sabersf** [comment]
What if we want to predict the next word given a sequence of words? like when 
`seed = ['love ', 'test ']`
I get this error:
`  File "tflearn/models/generator.py", line 217, in generate
    x[0, t, self.dic[char]] = 1.
IndexError: index 1 is out of bounds for axis 1 with size 1`

Do you have a sample code in tflearn for when we want to predict the next word given different sequences of words?

**Comment by BeasT321** [comment]
Hi, even I was getting the same error, so I had to change the for loop (which is right above the place where you make changes. Due to some reason, I can access the tflearn file right now, but if you manual trace it (i made a table for every variable) you will know the error. It wasnt a big change, but I can't exactly remember it.

**Comment by sabersf** [comment]
Thanks BeasT321. I'm trying to change the 'for loop'. No success yet. Please let me know if you figured out where your tflearn generator is.

**Comment by sabersf** [comment]
I changed the generator.py and by modifying the x entry after this line:
`x = np.zeros((1, self.seq_maxlen, len(self.dic)))`
The code is not returning errors anymore, but I doubt the results are LSTM are accurate anymore. Maybe we need to change the structure of the network as well.

**Comment by sabersf** [comment]
@aymericdamien do you have any example of  the Sequence Genrator that works with lists? More specifically given a list of strings, it uses LSTM to predict the next string. It seems SequenceGenrator only works with char, and I've been trying to change generator.py but so far has not achieved much success.
