### ISSUE TITLE
How to create my own variable initializer function?

### ISSUE THREAD

**Issue by lfwin** [tflearn/tflearn#156]
I try to implement this algorithm in this paper 'http://arxiv.org/abs/1603.05279', but seems need binary weights as networks params. I add a function modified from conv function in tflearn and not work.
 ` ....
     with tf.name_scope(name) as scope:

        W_init = initializations.get(weights_init)()
        W_regul = None
        if regularizer:
            W_regul = lambda x: losses.get(regularizer)(x, weight_decay)
        W = vs.variable(scope + 'W', shape=filter_size,
                        regularizer=W_regul, initializer=W_init,
                        trainable=trainable, restore=restore)
        W_proj, _ = binary_project(W)
        # Track per layer variables
       
        tf.add_to_collection(tf.GraphKeys.LAYER_VARIABLES + '/' + scope, W_proj)
        
        b = None
        ...`

but the variables add to collection tf.GraphKeys.LAYER_VARIABLES to compute gradiet is W instead of W_proj, so any advice for me to implement this algorithm?

**Comment by aymericdamien** [comment]
Your tflearn version seems too old. Please reinstall it, and you can initialize weights with any custom function.

About W_proj, make sure it is trainable variable, tf.GraphKeys.LAYER_VARIABLES is just used to retrieve variables for users, but not to compute backprop.

**Comment by lfwin** [comment]
hi, aymericdamien
Thank you for your advice, i have already implemented this algorithm, using numpy array and tf.constant_initializer function to initialize binary weights, and after tf.apply_gradient binarize the weights again, right now, program can running. 
Thank you again.
