### ISSUE TITLE
Data download progress bar

### ISSUE THREAD

**Issue by johangithub** [tflearn/tflearn#160]
This may be very trivial, but while downloading CIFAR-10 using cifar_10.py, I thought it was stuck. Turns out that it was just download taking a bit of a time. In hindsight, I should've known how big the dataset was before downloading(~170MB), but maybe it's nice to know the progress, especially for bigger datasets. Again, this looks very trivial to me so let me know if you don't need to see this kind of issues.

so in datasets/cifar_10.py I added
```python
#reporthook from stackoverflow #13881092
def reporthook(blocknum, blocksize, totalsize):
    readsofar = blocknum * blocksize
    if totalsize > 0:
        percent = readsofar * 1e2 / totalsize
        s = "\r%5.1f%% %*d / %d" % (
            percent, len(str(totalsize)), readsofar, totalsize)
        sys.stderr.write(s)
        if readsofar >= totalsize: # near the end
            sys.stderr.write("\n")
    else: # total size is unknown
        sys.stderr.write("read %d\n" % (readsofar,))
```
and changed
```python
filepath, _ = urllib.request.urlretrieve(source_url + filename, filepath)
```
to
```python
filepath, _ = urllib.request.urlretrieve(source_url + filename, filepath,reporthook)
```

Note: There is a slight discrepacny between the numbers when complete
```
Downloading CIFAR 10, Please wait...
100.0% 170500096 / 170498071
('Succesfully downloaded', 'cifar-10-python.tar.gz', 170498071, 'bytes.')
```

**Comment by aymericdamien** [comment]
That looks cool, it would indeed be useful! Could you send a pull request, so that I can integrate it inside TFLearn? Thanks :)

**Comment by johangithub** [comment]
So I have not sent a pull request, but I'll do it once I figure it out

**Comment by johangithub** [comment]
Sent

**Comment by aymericdamien** [comment]
Thank you! Already merged.
