### ISSUE TITLE
Using a tuple for filter size causes crash

### ISSUE THREAD

**Issue by ivanmkc** [tflearn/tflearn#164]
Using tflearn.conv_2d with a tuple as a filter size causes the crash:

> TypeError: type() takes 1 or 3 arguments

Seems to be caused by this section of utils.py, in autoformat_filter_conv2d:

    if isinstance(fsize,int):
        return [fsize, fsize, in_depth, out_depth]
    elif type(fsize, (tuple, list)):
        if len(fsize) == 2:
            return [fsize[0], fsize[1], in_depth, out_depth]
        else:
            raise Exception("filter length error: " + str(len(fsize))
                            + ", only a length of 2 is supported.")
    else:
        raise Exception("filter format error: " + str(type(fsize)))

The line:
` elif type(fsize, (tuple, list)):`
can be fixed to:
` elif isinstance(fsize, (tuple, list)):`

**Comment by aymericdamien** [comment]
Hi, that error has been fixed. Please reinstall tflearn (from master).
