### ISSUE TITLE
Is there anyway to save only the weights, which gives the best validaton accuracy? 

### ISSUE THREAD

**Issue by ruizhaogit** [tflearn/tflearn#165]
Hi Tflearn Team,

Is there anyway to save (snapshot) only the weights, which gives the best validaton accuracy? 

Best,
Rui

**Comment by aymericdamien** [comment]
Hi, unfortunately there is no way yet. But that should be easy to implement it. I let that open if anyone want to help on that!

**Comment by munnybearz** [comment]
I'd also be very interested in this. I tried implementing it a couple of weeks ago but I kept breaking the library :(

**Comment by dongb5** [comment]
I think the core codes of training and validation are in the function '_train' of the class TrainOp in the file 'trainer.py'. The validation codes are like

          if snapshot and self.val_feed_dict:
                tflearn.is_training(False, session=self.session)
                # Evaluation returns the mean over all batches.
                eval_ops = [self.loss]
    ........
and I'm also trying to implement it.

**Comment by aymericdamien** [comment]
Yes, in Trainer, you should implement a list that can record the performances of every checkpoint. And save the top one in a distinct variable.

**Comment by braddengross** [comment]
Instead of having the trainer handle this we could update trainer.fit and dnn.fit to return the accuracy and validation accuracy and then the implementation could check those and save the model if it's best. This also allows for custom logging and saving of accuracy statistics over time.

**Comment by braddengross** [comment]
Something like this: https://github.com/braddengross/tflearn/commit/0ba9848b265eb39331ba77b59b3e6611dee1d6e1 combined with the model.save method would allow the developer to control when the model is saved based on loss/accuracy. The return values for validation will be None unless it's a snapshot step, though.

**Comment by aymericdamien** [comment]
Yes, we should find a way to do that. Maybe adding an argument to `.fit`, such as a dict {'loss': save_if_value_over, 'acc': save_if_value_over}.
Another useful feature would be to keep track of the best model. That should be easy to add too.

**Comment by braddengross** [comment]
One issue with keeping track of the best model is if the model is reloaded we don't know the previous stats. We can keep track of the best model per fit quite easily but not the best model overall if the model is reloaded and trained over time. Is there currently a way to retrieve the validation accuracy after fit has been called?
