### ISSUE TITLE
i have follow warning or error log at each train epoch end, why?

### ISSUE THREAD

**Issue by mlinxiang** [tflearn/tflearn#172]
![image](https://cloud.githubusercontent.com/assets/6283983/16539531/b1764fb0-4078-11e6-8215-2fa9c3e8dda8.png)

![image](https://cloud.githubusercontent.com/assets/6283983/16539547/26f20266-4079-11e6-8eee-039f78f0485f.png)

**Comment by aymericdamien** [comment]
ops that is a bug because ConfigProto can't be saved into the model file, I will patch it.

**Comment by aymericdamien** [comment]
you can reinstall tflearn, it should works fine!

**Comment by braddengross** [comment]
I'm seeing this issue after my final training step.

![image](https://cloud.githubusercontent.com/assets/3966170/16997540/ec415158-4e83-11e6-80c9-1724e0ef7add.png)


![image](https://cloud.githubusercontent.com/assets/3966170/16997507/cf5e18aa-4e83-11e6-8256-ab2834f2c844.png)

**Comment by aymericdamien** [comment]
Are you using bidirectional_rnn?
