### ISSUE TITLE
ValueError: Variable GRU/GRU/GRUCell/Gates/Linear/Matrix does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

### ISSUE THREAD

**Issue by ruizhaogit** [tflearn/tflearn#175]
Hi,

Anyone know how to solve this error?

ValueError: Variable GRU/GRU/GRUCell/Gates/Linear/Matrix does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

I think it is bug about gru in the tflearn master.

Gru works in tflearn 2.0.

Thanks!

Best,
Rui

**Comment by aymericdamien** [comment]
It is fix now!
