### ISSUE TITLE
Issue loading feed dict

### ISSUE THREAD

**Issue by mikecassell** [tflearn/tflearn#178]
Hey guys, I'm sure I am missing something obvious but trying to use dirs_to_samples seems to cause an issue on the feed dict. Sorry if I missed something obvious.

`x, y = tflearn.data_utils.image_dirs_to_samples(directory='./data/train/', resize=[60,80])

xTrain, xTest, yTrain, yTest = cross_validation.train_test_split(x, y, test_size=0.2)

yTrain = to_categorical(yTrain, numClasses)

yTest = to_categorical(yTest, numClasses)

... build a model

model = tflearn.DNN(network, tensorboard_verbose=0)

model.fit(xTrain, yTrain, n_epoch=50, shuffle=True, 
          show_metric=True, batch_size=24, run_id='test1')
`
throws:

`---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-30-de7ffd8109a0> in <module>()
      1 model = tflearn.DNN(network, tensorboard_verbose=0)
      2 model.fit(xTrain, yTrain, n_epoch=50, shuffle=True, 
----> 3           show_metric=True, batch_size=24, run_id='test1')

/home/mike/anaconda2/envs/tf/lib/python2.7/site-packages/tflearn/models/dnn.pyc in fit(self, X_inputs, Y_targets, n_epoch, validation_set, show_metric, batch_size, shuffle, snapshot_epoch, snapshot_step, excl_trainops, run_id)
    156         # TODO: check memory impact for large data and multiple optimizers
    157         feed_dict = feed_dict_builder(X_inputs, Y_targets, self.inputs,
--> 158                                       self.targets)
    159         feed_dicts = [feed_dict for i in self.train_ops]
    160         val_feed_dicts = None

/home/mike/anaconda2/envs/tf/lib/python2.7/site-packages/tflearn/utils.pyc in feed_dict_builder(X, Y, net_inputs, net_targets)
    265                 X = [X]
    266             for i, x in enumerate(X):
--> 267                 feed_dict[net_inputs[i]] = x
    268         else:
    269             # If a dict is provided

IndexError: list index out of range`

**Comment by aymericdamien** [comment]
It may be an issue with your data shape. Could you check that X shape matches your input_shape layer?

**Comment by mikecassell** [comment]
I can't duplicate now, closing

**Comment by Irtza** [comment]
@mikecassell where is original question of which this is a duplicate?

**Comment by Baschdl** [comment]
@lrtza I think he couldn't reproduce it, there is no duplicate question.

**Comment by gouthamand** [comment]
Hello All, 

Has this error been fixed ?. I have used tf.reset_default_graph().

call trace narrows to this code in /utils.py and feed_dict function.
/opt/conda/lib/python3.6/site-packages/tflearn/utils.py in feed_dict_builder(X, Y, net_inputs, net_targets)
    298                 X = [X]
    299             for i, x in enumerate(X):
--> 300                 feed_dict[net_inputs[i]] = x

update on this would be really appreciated.
