### ISSUE TITLE
TypeError: lstm() got an unexpected keyword argument 'dynamic'

### ISSUE THREAD

**Issue by forhonourlx** [tflearn/tflearn#183]
When running the example:  dynamic_lstm.py (my dependency is tensorflow 0.8.0-gpu)
File "dynamic_lstm.py", line 48, in <module>
    net = tflearn.lstm(net, 128, dropout=0.8, dynamic=True)
TypeError: lstm() got an unexpected keyword argument 'dynamic'
And searching in the doc, argument 'dynamic' exsists in lstm function, what is going wrong?

**Comment by aymericdamien** [comment]
Can you update TFLearn? It seems you do not have latest version that support dynamic RNNs.
```
pip install --upgrade git+https://github.com/tflearn/tflearn.git
```

**Comment by forhonourlx** [comment]
It does work.Thank you for your help.
