### ISSUE TITLE
bidirectional_rnn error

### ISSUE THREAD

**Issue by ruizhaogit** [tflearn/tflearn#196]
Hi TFlearn,

I am encoutered into an error, when using bidirectinal gru:

    net = tflearn.bidirectional_rnn(net, GRUCell(300), GRUCell(300), return_seq=False)
  File "/tflearn/layers/recurrent.py", line 386, in bidirectional_rnn
    sfw = states_fw if return_seq else states_fw[-1]
  File "/tensorflow/0.9.0/osl42-x86_64/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 224, in _SliceHelper
    raise NotImplementedError("Negative indices are currently unsupported")
NotImplementedError: Negative indices are currently unsupported

Do you know how to solve this error?

Thank you!

Best,
Rui

**Comment by aymericdamien** [comment]
it may due to the fact that bidir rnn has been updated in tensorflow. Let me check into this.

**Comment by ruizhaogit** [comment]
This works in tflearn 0.2.1 but not in the current master.

**Comment by aymericdamien** [comment]
It is working now!
