### ISSUE TITLE
GRU restore weights error:

### ISSUE THREAD

**Issue by ruizhaogit** [tflearn/tflearn#197]
Hi Tflearn,

GRU restore weights error:

tensorflow.python.framework.errors.NotFoundError: Tensor name "GRU/Candidate/W" not found in checkpoint files /net/rmc-lx0200/home_local/tflog/ntu_cross_subject_4/model_7/-7000

Best,
Rui

**Comment by aymericdamien** [comment]
I cannot reproduce your error. That seems strange, it suggest that GRU weights haven't been save in your model file.
