### ISSUE TITLE
Type Error: Unexpected key arguments in LSTM

### ISSUE THREAD

**Issue by krayush07** [tflearn/tflearn#202]
Hi, I am encountering a error while using parameters (_return_state_, _dynamic_) in LSTM layer.

`lstm_net = tflearn.layers.recurrent.lstm(input_net, 100, dropout=0.8, return_seq=False, return_state=False, dynamic=True, name='lstm_layer')`

Error: `TypeError: lstm() got an unexpected keyword argument 'dynamic'`. 
The same error holds for _return_state_ if dynamic parameter is removed.

**Comment by krayush07** [comment]
Dev version as in bleeding edge version? I tried that but was facing some import errors, so I had to move back to stable version.

`'module' object has no attribute 'add_arg'`

I checked with the issue already listed at https://github.com/rackerlabs/os_diskconfig_python_novaclient_ext/issues/2. However, solution mentioned there didn't work for my case.

**Comment by tgallice** [comment]
Yes the bleeding edge version :) Have you tried to update the python-novaclient package ? A more recent post about your issue https://github.com/saltstack/salt/issues/33593

**Comment by krayush07** [comment]
I could not locate ver 4.0.0, rather installed 4.1.0. However, same issue persists. Is it working for your case @tgallice?

**Comment by krayush07** [comment]
@aymericdamien DO you have any suggestion on resolving this issue. I need to have a dynamic LSTM running, however I am running into issues with the stable version as mentioned.

**Comment by aymericdamien** [comment]
as tgallice suggested, it seems you do not have the last version of tflearn, you need to update your version by using:
```
pip install --upgrade git+https://github.com/tflearn/tflearn.git
```

**Comment by krayush07** [comment]
I did that. But I encounter import issues with tflearn. With more google search and as suggested by tgallice, I upgraded python-novaclient but in vain.

**Comment by krayush07** [comment]
Hi @aymericdamien , please see the error trace:

```
Traceback (most recent call last):
  File "readCSV.py", line 1, in <module>
    import tflearn
  File "/usr/local/lib/python2.7/dist-packages/tflearn/__init__.py", line 9, in <module>
    from . import models
  File "/usr/local/lib/python2.7/dist-packages/tflearn/models/__init__.py", line 2, in <module>
    from .dnn import DNN
  File "/usr/local/lib/python2.7/dist-packages/tflearn/models/dnn.py", line 5, in <module>
    from ..helpers.trainer import Trainer
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/__init__.py", line 2, in <module>
    from .evaluator import Evaluator
  File "/usr/local/lib/python2.7/dist-packages/tflearn/helpers/evaluator.py", line 6, in <module>
    from ..utils import to_list
  File "/usr/local/lib/python2.7/dist-packages/tflearn/utils.py", line 16, in <module>
    import tflearn.variables as vs
  File "/usr/local/lib/python2.7/dist-packages/tflearn/variables.py", line 8, in <module>
    @tf.contrib.framework.add_arg_scope
AttributeError: 'module' object has no attribute 'add_arg_scope'

```

**Comment by krayush07** [comment]
Okay, this issue was resolved by upgrading the pip version.
