### ISSUE TITLE
Help: Cannot feed value of shape (128,) for Tensor u'target/Y:0', which has shape '(?, 1)'

### ISSUE THREAD

**Issue by yushuinanrong** [tflearn/tflearn#206]
Hi all,

I'm new to deep learning and TFlearn. I'm trying to modify the python code 'convnet_cifar10.py' for my own head pose image deaset. My task is a regression problem, so I mainly focus on modifying the top of the Convnet. However, I always encounter a same error:
ValueError: Cannot feed value of shape (128,) for Tensor u'target/Y:0', which has shape '(?, 1)'
I did google this problem and found some threads talking about how to solve the problem. While so far, the error is still there.
I attach my code and the errors below.
Any idea is greatly appreciated!

Jiawei 

# coding: utf-8

# In[ ]:

from __future__ import division, print_function, absolute_import

import tflearn
from tflearn.data_utils import shuffle, to_categorical
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.conv import conv_2d, max_pool_2d
from tflearn.layers.estimator import regression
from tflearn.data_preprocessing import ImagePreprocessing
from tflearn.data_augmentation import ImageAugmentation
from numpy import genfromtxt
import numpy as np

mydata = genfromtxt('/home/vivo/Desktop/Biwi Dataset/Biwi_32_by_32_cropped_RGB_normalized.csv',delimiter = ',')
[m,n]  = mydata.shape
Feat   = mydata[:,0:n-3]
Feat_re= Feat.reshape(m,32,32,1)
Label  = mydata[:,n-2]

X      = Feat_re[0:13500,:,:,:]
X_test = Feat_re[13500:-1,:,:,:]
#X      = np.reshape(X, ([-1,32,32,1]))
#X_test = np.reshape(X_test,([-1,32,32,1]))
X      = X.reshape([-1,32,32,1])
X_test = X_test.reshape([-1,32,32,1])
Y      = Label[0:13500]
Y_test = Label[13500:-1]

#Y      = np.transpose(Y)
#Y_test = np.transpose(Y_test)

# Real-time data preprocessing
img_prep = ImagePreprocessing()
img_prep.add_featurewise_zero_center()
img_prep.add_featurewise_stdnorm()

# Convolutional network building
network = input_data(shape=[None, 32, 32, 1], name='input')
network = conv_2d(network, 32, 3, activation='relu')
network = max_pool_2d(network, 2)
network = conv_2d(network, 64, 3, activation='relu')
network = conv_2d(network, 64, 3, activation='relu')
network = max_pool_2d(network, 2)
network = fully_connected(network, 512, activation='relu')
network = dropout(network, 0.5)
network = fully_connected(network, 1, activation='linear')
network = regression(network, optimizer='sgd',
                     loss='mean_square',
                     learning_rate=0.001, name ='target')

# Train using classifier
model = tflearn.DNN(network, tensorboard_verbose=3)
model.fit(X, Y, n_epoch=50, shuffle=True, validation_set=(X_test, Y_test),
          snapshot_step=100,  show_metric=True, batch_size=128, run_id='pose_cnn')

ERROR:
Traceback (most recent call last):
  File "My_firstTFlearn.py", line 61, in <module>
    snapshot_step=100,  show_metric=True, batch_size=128, run_id='pose_cnn')
  File "/home/vivo/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tflearn/models/dnn.py", line 188, in fit
    run_id=run_id)
  File "/home/vivo/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tflearn/helpers/trainer.py", line 277, in fit
    show_metric)
  File "/home/vivo/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tflearn/helpers/trainer.py", line 684, in _train
    feed_batch)
  File "/home/vivo/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)
  File "/home/vivo/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 625, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (128,) for Tensor u'target/Y:0', which has shape '(?, 1)'

**Comment by aymericdamien** [comment]
Because you are using categorical crossentropy, your target should be a 2-D array.
To do so, you can reshape your Y array as follow: 
`Y = np.reshape(Y, [-1, 1])`

**Comment by yushuinanrong** [comment]
@aymericdamien 
Hi Damien,
Thank you for your reply. You answer solve my problem perfectly.
Now, the code is running smoothly.

regards,
Jiawei

**Comment by aymericdamien** [comment]
Cool, glad to hear :)
