### ISSUE TITLE
How to use customized metrics like L1/L2 norm

### ISSUE THREAD

**Issue by yushuinanrong** [tflearn/tflearn#207]
Hi all

I would like to use L1 norm as my metric to evaluate the test performance. I'm not sure how to do it in TFlearn API.
Any idea?

thanks,
Jiawei

**Comment by aymericdamien** [comment]
You can define a custom function to be used as your metric, it have to follow this pattern (take 3 arguments):
```
def l1_norm(prediction, target, inputs):
    return tf.reduce_sum(tf.abs(prediction - target))
net = tflearn.regression(net, metric=l1_norm)
```

**Comment by yushuinanrong** [comment]
@aymericdamien 
Hi Damien,

I greatly appreciate your help! It works for my problem.

thanks,
Jiawei

**Comment by liuhuiwisdom** [comment]
hi, I am confused where to add the code?
in tflean source code OR my code?

**Comment by shahinkl** [comment]
@aymericdamien, can you also state an example for tf.edit_distance? I treid my best, but getting the following error.

def edit_distance(predictions, targets):
    if not isinstance(targets, tf.SparseTensor):
        raise ValueError("mean_per 'input' argument only accepts type "
                         "SparseTensor, '" + str(type(input)) + "' given.")

    predictions = tf.cast(predictions, tf.int32)

    with tf.name_scope('WER'):
        distance = tf.edit_distance(predictions, targets)
        wer = tf.reduce_mean(tf.cast(distance, tf.float32))
    return wer

Error : ValueError: as_list() is not defined on an unknown TensorShape

**Comment by TrinhTUHH** [comment]
@yushuinanrong I have followed @aymericdamien suggestion but I got this error when strart training: 
`ValueError: Tag: l1:0 cannot be found in summaries list.`
Do you have any ideas why?

**Comment by bhavikajalli** [comment]
Thanks for the instructions.
I tried to define my own custom metric, hamming loss as follows:
```
def hamming_loss(y_pred,y_true,inputs):
    return hamming_loss(y_true, y_pred)
```
This gives me the following error.
```
hamming_loss() takes exactly 3 arguments (2 given)
Reminder: Custom metric function arguments must be defined as: custom_metric(y_pred, y_true, x).
```
My custom loss does have 3 input arguments.  Any idea how to solve this problem?
