### ISSUE TITLE
Thread-specifc models in reinforcement Learning example

### ISSUE THREAD

**Issue by yukezhu** [tflearn/tflearn#214]
In the [reinforcement learning example](https://github.com/tflearn/tflearn/blob/master/examples/reinforcement_learning/atari_1step_qlearning.py), the note described that this example implemented the 1-step Q-learning algorithm from [this paper](http://arxiv.org/pdf/1602.01783v1.pdf). However, I found that the model does not maintain thread-specific parameters for each of the parallel threads. Does it means that the model is a simplification of the original asynchronous 1-step Q-learning model?

**Comment by aymericdamien** [comment]
The reason is that the asynchronous one-step learning algorithm from the paper is not using thread-specific parameters (c.f. Algorithm 1). But thread-specific parameters are required to implement the n-step version of the paper (Algorithm 2).

**Comment by yukezhu** [comment]
This answers my question. Thanks.
