### ISSUE TITLE
Embedding matrix initialization in Embedding layer

### ISSUE THREAD

**Issue by juliohm** [tflearn/tflearn#218]
I have a use case where the embedding matrix is computed in a pre-processing step with a large corpus. I am trying to pass this matrix to the embedding layer of tflearn:

```python
net = tflearn.embedding(net, input_dim=vocabsize, output_dim=embeddingsize, W_init=precomputed_W, trainable=False)
```

The code as it is throws an error regarding the initializer. It seems that there is an issue with passing the tensor W_init and the shape at the same time. When W_init is not provided, the object type of W_init is internally set to a callable object and everything is fine.

After fixing the issue above, I am now getting a FailedPreconditionError regarding the initialization of some graph variables. I will attach a screenshot later of the error, I don't have access to it right now.

I appreciate any help.

Sincerely.

**Comment by juliohm** [comment]
Attached below the screenshot of the error:

![1](https://cloud.githubusercontent.com/assets/3345261/17073876/836ab85a-503a-11e6-9b9d-c1ec31c88128.jpg)

![2](https://cloud.githubusercontent.com/assets/3345261/17073883/8e96feb4-503a-11e6-9377-af1c8b1dff89.jpg)

I am putting the tflearn code inside of a `with graph.as_default():` scope in a separate Jupyter cell. This graph is the global graph created by TensorFlow.

**Comment by aymericdamien** [comment]
Are you passing a 'tf.constant_initializer'? I am a little confuse about the 'unitialized value' error. Maybe the reason is that you are using a custom session, and then 'DNN' recreates a new session, so weights are not initialized.
Another way to tackle you issue, is to assign your custom weights to the embedding layer using 'DNN' `set_weights` method:
```python
net = ...
emb = tflearn.embedding(net, 64)
net = ...

model = tflearn.DNN(net)
model.set_weights(emb.W, YOUR_NUMPY_ARRAY)
model.fit(....)
```

**Comment by juliohm** [comment]
@aymericdamien I am passing a Tensor defined in the default graph in a previous Jupyter cell. It is defined inside of a `with tf.Session(graph=graph) as session:` clause with `graph` the default graph. Later on in a different cell I have:

```python
with graph.as_default():
    net = tflearn.input_data(...)
    net = tflearn.embedding(net, ..., W_init=PretrainedW, trainable=False)
    net = tflearn.lstm(net, ...)

    model = tflearn.DNN(net, ...) # do I need to pass a specific session here?
    ...
```

Is there anything incorrect or unreasonable? I am assuming that I can train the embedding matrix with a large corpus and just pass it to the embedding layer, which in turn will be the input to the lstm layer for classifying sentences.

**Comment by aymericdamien** [comment]
Maybe try to share the session with `DNN` object by setting its argument 'session'.
Otherwise, I am not sure what type is PretrainedW, if it is a numpy array, just use tf.constant_initializer(PretrainedW).

**Comment by juliohm** [comment]
The pre-trained matrix is of type TensorFlow.Tensor, I've double checked it. I will try to pass the session to the DNN tomorrow. Is there anything else that you have in mind that could be causing the issue?

**Comment by aymericdamien** [comment]
No, I think the issue is the session.

**Comment by juliohm** [comment]
Ok, I have collected more information about the usage. First I would like to show you the code and the associated TensorBoard graph:

![1](https://cloud.githubusercontent.com/assets/3345261/17122453/322c4bac-52a1-11e6-9e96-4f43e1f97337.jpg)
![2](https://cloud.githubusercontent.com/assets/3345261/17122465/3e898f22-52a1-11e6-8c93-ca5f04d0178f.jpg)

This application is running without errors, but there must be something wrong. I checked the accuracy on the validation set and it is constant throughout the entire training:

![3](https://cloud.githubusercontent.com/assets/3345261/17122502/845266b4-52a1-11e6-8a25-4517758b8efb.jpg)

I am also attaching other plots below for debugging purposes. It seems that the initial weights I am passing are not being used? Could you please confirm that the `weights_init` parameter in the embedding layer is just a matrix with the word vectors for each word in the vocabulary stacked as rows?

![4](https://cloud.githubusercontent.com/assets/3345261/17122599/73dba4c0-52a2-11e6-8d01-9ea144c11721.jpg)
![5](https://cloud.githubusercontent.com/assets/3345261/17122602/7b9ac4de-52a2-11e6-8298-12a732e9b237.jpg)
![6](https://cloud.githubusercontent.com/assets/3345261/17122605/8540aaa8-52a2-11e6-801a-0871f915fce9.jpg)

**Comment by aymericdamien** [comment]
Yes, it should works fine. Are you using 'dynamic' computations? Your first dimension (row '0') should be for padding, maybe that is the error.
You can verify that loads are loaded correctly, by printing `model.get_weights(emb.W)`. Embedding layer is just applying the `emnbedding_lookup` of TensorFlow (see https://github.com/tflearn/tflearn/blob/master/tflearn/layers/embedding_ops.py#L61).

**Comment by juliohm** [comment]
No, I have tried stacking a first row of zeros in the `final_embeddings`
variable but it complains:

>ValueError: Too many elements provided. Needed at most x, but received y

-Júlio

**Comment by juliohm** [comment]
What is `emb.W` in your verification code? Can you please point to the
variable in my code I should pass to this function?

-Júlio

**Comment by aymericdamien** [comment]
By 'emb' I meant your embedding layer 'tflearn.emedding(...)'

**Comment by juliohm** [comment]
I found other issues in the code and also have obtained better results with other optimizers. Thank you for your help.
