### ISSUE TITLE
One-hot output string labels

### ISSUE THREAD

**Issue by chrisruk** [tflearn/tflearn#220]
Hi,

I'm just wondering I have the following output in my network:

```
    network = fully_connected(network, len(mod), activation='softmax',name="out")
```

So there are 11 output neurons (len(mod) == 11), I'm wondering if it is possible 
to associate strings with those neurons, where the strings will be saved, when I freeze
the graph.

I'm struggling to find if this is possible.

For instance I've tried the following:

```
    s = tf.Variable("test string",name="outputs")
    tf.add_to_collection(tf.GraphKeys.VARIABLES, s)
    
    ops = tf.initialize_all_variables()
    sess.run([ops,s])
```

But it doesn't appear to be saved in the graph, when i use my savegraph routine after the sess.run

Any pointers would be great 

cheers

Chris

**Comment by aymericdamien** [comment]
To have it saved, you have to define
```
  s = tf.Variable("test string",name="outputs")
    tf.add_to_collection(tf.GraphKeys.VARIABLES, s)

    ops = tf.initialize_all_variables()
    sess.run([ops,s])
```
before creating your TF Saver object (or 'DNN' class object).

**Comment by chrisruk** [comment]
Thanks!

I found I also had to add the node to the list 
of output nodes in the savegraph function.
