### ISSUE TITLE
One Hot encoding defaults to on_value=1.0 AND off_value=1.0

### ISSUE THREAD

**Issue by DataWraith** [tflearn/tflearn#224]
Hi.

I think I may have found a typo: The `off_value` parameter of the `one_hot_encoding` function in `core.py` ([here](https://github.com/tflearn/tflearn/blob/7b13632ac1e781548f19f201e9eb98dc5e07d7b0/tflearn/layers/core.py#L544
)) defaults to `1.0`. Tensorflow itself defaults to a 0 here, and if my understanding of One Hot Encoding is correct, tflearn really should default to 0 as well.

Let me know if you want a pull request, or if this is so trivial to fix that that is not necessary. If it isn't a simple typo, then the reasoning behind it should probably be documented.

**Comment by aymericdamien** [comment]
Hi, that is correct, thanks for pointing that out! You can send a PR, I will merge it :)
