### ISSUE TITLE
RNN dynamic=True and return_seq=True mutually exclusive

### ISSUE THREAD

**Issue by elmar-haussmann** [tflearn/tflearn#227]
In the current code it seems you can either have a dynamic RNN or one that returns the whole sequence but not both.

The relevant code in recurrent.py:
```
...
    if dynamic:
        outputs = tf.transpose(tf.pack(outputs), [1, 0, 2])
        o = advanced_indexing_op(outputs, sequence_length)
    else:
        o = outputs if return_seq else outputs[-1]
...
    return (o, state) if return_state else o 
```
Is there a specific reason for this I am not seeing? Let me know if you want a pull request.

**Comment by aymericdamien** [comment]
True, seems there is a mistake here. You are welcome to send a pull request! Thanks.

**Comment by elmar-haussmann** [comment]
You can check pull request #229

**Comment by aymericdamien** [comment]
I merged it, Thank you!
