### ISSUE TITLE
ImportError: cannot import name 'build_hdf5_image_dataset'

### ISSUE THREAD

**Issue by tgs266** [tflearn/tflearn#228]
I really need to make an HDF5 dataset so I can create an image classifier, but the "build_hdf5_image_dataset" command does not work at all. I get an import error. 
Do you guys know what is wrong? Or is there any other way to make an HDF5 dataset with class ids?
Thanks in advance,
Tucker

**Comment by aymericdamien** [comment]
Could you paste the error trace?
```
>>> from tflearn.data_utils import build_hdf5_image_dataset
>>> build_hdf5_image_dataset(.....)
```
This is working fine for me

**Comment by tgs266** [comment]
Here is the error trace:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-5-a829657901f3> in <module>()
      3 from tflearn.data_utils import *
      4 from tflearn import *
----> 5 build_hdf5_image_dataset(d_file, image_shape=(128,128), mode='file', output_file='/home/tucker/RoomClass/Data/Datasets/Text/All.h5', categorical_labels=True, normalize=True)

NameError: name 'build_hdf5_image_dataset' is not defined

**Comment by aymericdamien** [comment]
Try to install the latest version of TFLearn: 
`pip install --upgrade git+https://github.com/tflearn/tflearn.git`

**Comment by tgs266** [comment]
@aymericdamien Thank you so much! That fixed my problem!
