### ISSUE TITLE
Bug in weights_persistance.py example

### ISSUE THREAD

**Issue by bruceweir** [tflearn/tflearn#231]
In https://github.com/tflearn/tflearn/blob/master/examples/basics/weights_persistence.py the 

print(model.get_weights(dense1_vars[0]))  line seems to fail.

Error is:

IndexError                                Traceback (most recent call last)
<ipython-input-2-85aeef9b46c9> in <module>()
     22 # Get a variable's value, using model `get_weights` method:
     23 print("Dense1 layer weights:")
---> 24 print(model.get_weights(dense1_vars[0]))
     25 # Or using generic tflearn function:
     26 print("Dense1 layer biases:")

IndexError: list index out of range

The example is being run in a Python 2 Jupyter Notebook.

**Comment by joedursun** [comment]
For what it's worth I do not get an error from that example.

My environment:
`Mac OS X 10.11.6`
`Python 2.7.10`
`Jupyter 4.1.0`
`Tflearn 0.2.1`

@bruceweir can you post some info about your setup to make it easier to reproduce?

**Comment by bruceweir** [comment]
Ubuntu 14.04.4 LTS 64-bit
2.7.11 |Anaconda 2.3.0 (64-bit)| (default, Dec  6 2015, 18:08:32) 

jupyter                   1.0.0                    py27_3
jupyter_client            4.2.2                    py27_0
jupyter_console           4.1.1                    py27_0
jupyter_core              4.1.0                    py27_0
tflearn 0.2.1
tensorflow 0.9.0rc0

The lines:

`print("Dense2 layer weights:")`
`print(model.get_weights(dense2.W))`
`print("Dense2 layer biases:")`
`with model.session.as_default():`
&nbsp;&nbsp;&nbsp;&nbsp;`print(tflearn.variables.get_value(dense2.b))`


All work fine (which is OK for a workaround)
