### ISSUE TITLE
ImportError: cannot import name titanic [from tflearn.datasets import titanic]

### ISSUE THREAD

**Issue by victoriastuart** [tflearn/tflearn#234]
Posted in case this helps someone else. I am operating using Arch Linux (64-bit), Python 2.7 in a tf-venv, Jupyter notebook.

ISSUE:

    import tflearn
    from tflearn.datasets import titanic

    ImportError: cannot import name titanic

SOLUTION:

    pip install git+https://github.com/tflearn/tflearn.git
    pip install tflearn
    pip install tflearn --upgrade

However, same import error (above). Next tried (per solution pisted in Issue #228):
 
    pip install --upgrade git+https://github.com/tflearn/tflearn.git

Import statement now works (after reloading Jyputer kernel).

**Comment by vsraptor** [comment]
I cant install:

pip install --upgrade git+https://github.com/tflearn/tflearn.git

=========

Requirement already up-to-date: six in /usr/local/lib/python2.7/dist-packages (from tflearn==0.2.2)
Downloading/unpacking Pillow from https://pypi.python.org/packages/46/4f/94f6165052774839b4a4af0c72071aa528d5dc8cb8bc6bb43e24a55c10cc/Pillow-3.4.2.tar.gz#md5=09ebb92ec5cbba13ff1acf139caf6b66 (from tflearn==0.2.2)
  Downloading Pillow-3.4.2.tar.gz (10.8MB): 10.8MB downloaded
  Running setup.py (path:/tmp/pip_build_root/Pillow/setup.py) egg_info for package Pillow
    
............
 
   ' using --disable-%s, aborting' % (f, f))

ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting

----------------------------------------
  Can't roll back Pillow; was not uninstalled
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Nscmod-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/Pillow
Storing debug log for failure in /root/.pip/pip.log
