### ISSUE TITLE
regression() got an unexpected keyword argument 'to_one_hot'

### ISSUE THREAD

**Issue by angrygoats** [tflearn/tflearn#242]
Hey,

I'm pretty sure I'm making a really simple mistake but I can't honestly figure out what is going on. My code looks like:

```
from tflearn.layers.estimator import regresion

# ... code to set up the DNN

net = regression(net, optimizer='adam', learning_rate=0.001, to_one_hot=True, n_classes=2, loss='categorical_crossentropy')

```

However, I see the error: `regression() got an unexpected keyword argument 'to_one_hot'` which would indicate that the argument doesn't exist.

Am I doing something wrong here? I am currently using tflearn 0.2.1.

Thank you!

**Comment by aymericdamien** [comment]
Hi, you just need to upgrade TFLearn to the latest version:
```
pip install --upgrade git+https://github.com/tflearn/tflearn.git
```
