### ISSUE TITLE
Bidirectional encoder for seq2seq in TFLearn

### ISSUE THREAD

**Issue by krayush07** [tflearn/tflearn#247]
Do we have support for implementing bidirectional encoder-decoder (for example: in machine translation use-case) in TFLearn?

**Comment by aymericdamien** [comment]
I think you should be able to do that, but we haven't a tutorial or example yet. but we should work on it soon, as it seems many people are interesting in it.

**Comment by krayush07** [comment]
Yes,  a tutorial for bidirectional encoder-decoder is very much required.

**Comment by aymericdamien** [comment]
you can check: https://github.com/tflearn/tflearn/blob/master/examples/nlp/seq2seq_example.py
