### ISSUE TITLE
Uninitialized session in autoencoder.py example

### ISSUE THREAD

**Issue by JohannesEbke** [tflearn/tflearn#25]
On trying out tflearn for the first time, I encountered a very misleading error in the autoencoder.py example:

At 
https://github.com/tflearn/tflearn/blob/14209862df6b2e1d929a82ee614098c55a7ef00f/examples/images/autoencoder.py#L46
a new tflearn.DNN is initialized with the encoder tensor. Unfortunately, it seems that this creates a new Session, where the weights of the tensor are not set to the values in the session where it was just trained.

This can be verified by adding the following debug statements after the predict():
```
print("bias in model:", model.get_weights(encoder.b))
print("bias in encoding_model:", encoding_model.get_weights(encoder.b))
```
The biases in the model are non-zero, whereas the biases in the encoding_model are zeroed.

I'd suggest replacing the DNN by an Evaluator sharing the session of the model, maybe:
```
ev = tflearn.Evaluator([encoder], session=model.session)
print(ev.predict({model.inputs[0]: [X[0]]}))
```
I am not 100% sure this is correct, since I just started out using this library.

**Comment by aymericdamien** [comment]
Thanks for reporting the issue! 
There is a problem here about session sharing, indeed, when defining the new DNN model class 'encoding_model', there were no way to tell it to re-use the old model weights ('model'). As a fix, I added a session parameter to TFLearn models (DNN and SequenceGenerator classes). So they can use any pre-trained weights simply by passing 'session' argument.
Note that your example will also works well, but for more simplicity in the example, I directly added a shared session when creating 'encoding_model'.
You can reinstall TFLearn, to apply the changes.

**Comment by aymericdamien** [comment]
You can check: https://github.com/tflearn/tflearn/blob/master/examples/images/autoencoder.py#L47
