### ISSUE TITLE
Order of multiple inputs is dependent on the order of their declaration instead of order in feed

### ISSUE THREAD

**Issue by dhwajr** [tflearn/tflearn#250]
suppose I have a multiple input network like this:

```
net0 = tflearn.input_data([None, 150],name="InputData0")
net0 = blah more layers blah
net1 = tflearn.input_data([None, 150],name="InputData1")
net1 = blah more layers blah
net = tflearn.merge([net1,net0],"concat",axis=2) # note the order here
```

Now if I call model.fit, it expects input in order of declaration, i.e. first net0 then net1 but I want to change the order of inputs on purpose and that is not working.

```
# fails
model.fit([X_train1,X_train0], y_train, validation_set=([X_test1,X_test0], y_test), batch_size=400) 
```

**Comment by dhwajr** [comment]
issue is with self.inputs in dnn.py
order of inputs is taken from GRAPHKEYS instead of order in merge : 
```
        self.inputs = tf.get_collection(tf.GraphKeys.INPUTS)
```

This need to be fixed. 
The better workaround for this problem is not to rely on list of inputs, better use a dictionary of inputs with keys as input layer names.

```
#works fine
model.fit({"InputData1":X_train1,"InputData0":X_train0}, y_train, validation_set=({"InputData1":X_test1,"InputData0":X_test0}, y_test),batch_size=400)
```

**Comment by aymericdamien** [comment]
I am not sure why you want to change the order? If you want so, as you pointed out, only using a dictionary can works.

**Comment by dhwajr** [comment]
yes it is not very important scenario. 
Just logged it in here so that anybody struggling with similar issue could find it.
