### ISSUE TITLE
bidirectional_rnn method is not suitable for MultiRNNCell

### ISSUE THREAD

**Issue by dhwajr** [tflearn/tflearn#257]
Can not pass MultiRNNCell in bidirectional_rnn method.

```
net = tflearn.bidirectional_rnn(net, MultiRNNCell([GRUCell(num_units)]*num_units), 
          MultiRNNCell([GRUCell(num_units)]*num_units))  #256=num_hidden, 3=num_layers
```

error in line     assert (rnncell_fw._num_units == rnncell_bw._num_units), with message that _num_units is not part of rnncell_fw

**Comment by aymericdamien** [comment]
This is due to the fact that TensorFlow 'MultiRNNCell' doesn;t have a _num_units attribute, but 'bidirectional_rnn' is expecting one.
As a workaround:
```
fw = MultiRNNCell([GRUCell(num_units)]*num_units)
fw._num_units = 0
bw = MultiRNNCell([GRUCell(num_units)]*num_units)
bw._num_units = 0
net = tflearn.bidirectional_rnn(net, fw, bw)  #256=num_hidden, 3=num_layers
```
