### ISSUE TITLE
Is it possible to get the validation error in DNN.fit?

### ISSUE THREAD

**Issue by ShownX** [tflearn/tflearn#264]
Hello, Thanks for this awesome work. 
I just transfer the work to tflearn from torch. So I am pretty new here.
A quick question: When I apply the validation set in the DNN.fit, how can I get the prediction when the TFlearn.DNN.fit and get the best model?
If not, is it possible to write the code in the loop to evaluate the model and save it likes follows?

for steps in xrange(MAX_STEPS):
     model.fit
     error = model.evaluate/predict
     if the error is the minimal:
           save model

**Comment by braddengross** [comment]
I haven't found a built in way to do this. My pull request here: #265 is a fix for this issue which will save the model every time the validation prediction is gets more accurate. Another option is a change like this: https://github.com/braddengross/tflearn/commit/0ba9848b265eb39331ba77b59b3e6611dee1d6e1 which will return the accuracies and then you can handle saving on your own. I haven't found a way with the current implementation of TFLearn to do what you want.

**Comment by ShownX** [comment]
@braddengross Thanks. I am not very sure what is the accuracy here if I do have a regression problem  on hand rather than a classification. I will check the code to see what is the accuracy defined.

**Comment by aymericdamien** [comment]
Actually, it is the best 'metric' score you are using. So if for a regression you are using R2, it will be R2 score.
