### ISSUE TITLE
3D Convolutional Layers not included in __init__ files 

### ISSUE THREAD

**Issue by oulutan** [tflearn/tflearn#277]
I am not able to import conv_3d and 3d pooling layers. When I checked the __ init __.py files for both the tflearn folder and the layers folder, I realized 3D layers aren't included in those files. Is this intentional? Are those layers ready to use?

**Comment by aymericdamien** [comment]
Yes they are working, we just forgot to add them into __init__.py! If you want, you can make a pull request to add it, and I will merge it :) Or I will update the code later.
