### ISSUE TITLE
bug? Feed two different size network

### ISSUE THREAD

**Issue by ShownX** [tflearn/tflearn#281]
Hello, there, 

I have two network: the first one: shape is (-1, 150, 150, 1) and the second one is (-1, 30, 30, 1)
I am getting confused that when I feed the data to the second network using model.fit().
I get error that list index out of range. So I debug it and find an interesting thing that it still call the first network.

feed_dict: InputDat/X:0 shape=(?, 150, 150, 1)

Do you have any ideas to solve this problem?

**Comment by aymericdamien** [comment]
When you fit, you have to give values for both network at the same time in fit: `fit([X1, X2], [Y1, Y2)`
Otherwise, you have to encapsulate each network by `with tf.Graph().as_default():` so that they do not share the same Graph.

**Comment by ShownX** [comment]
Interesting design. 
Maybe I understand wrong. The meaning you said is nesting the net definition from ```tflearn.input_data()``` to ```tflearn.DNN``. Is it right?

And I add ```with tf.Graph().as_default()``` in the beginging of both functions ```net1()``` and ```net2```, which return the variables ```net = tflearn.regression``` and ```model = tflearn.DNN```. But the ```model.save``` is  out of the function.
When I load the model using ```model.load()```, it gets the error ```Fetch argument u'save_1/restore_all' of u'save_1/restore_all' cannot be interpreted as a Tensor. ("The name 'save_1/restore_all' refers to an Operation not in the graph.")```

**Comment by aymericdamien** [comment]
I mean something like that:
```python
# Training in the same time:
net1 = input_data(...)
net1 = ...
net1 = regression(...)
net2 = input_data(...)
net2 = ...
net2 = regression(...)
network = tflearn.merge_outputs([net1, net2])
model = DNN(network)
model.fit([X1, X2], [Y1, Y2])
```

**Comment by ShownX** [comment]
I understand the first situation you said. I wrote the code like follows:
```
# train the first network => save the model
# load the model => test the first network
# train the second network
```

**Comment by aymericdamien** [comment]
Oh I see, this way is more tricky. Maybe you could try something like that:
```
def net1(...):
   ....

with tf.Graph().as_default():
   reg = regression(net1(), ...)
   # Here train your network1 and save it

with tf.Graph().as_default():
   net1 = net1()
   net2 = network2(net1)
   model = DNN(net2)
   model.load('model_net1')
   # Here train your network2
```

**Comment by ShownX** [comment]
Is it possible to construct two different graph in Tensorflow or TF? 
It is kind of hard to understand to put the ```net1``` into ```net2``` because of two different network.

**Comment by ShownX** [comment]
And for the line: ```net2 = network2(net1)```, how to write the code for ```network2```?
for the ```net2```, I defined as:
```
net = tflearn.input_data(shape=[None, 30, 30, 1])
net = tflearn.conv_2d(net, 32, 3)
...
net = tflearn.fully_connected(net, 2)
net = tfleran.regression(net, ...)
```
I do not know how to put the ```net1``` into ```net2```...

**Comment by ShownX** [comment]
@aymericdamien You are right. Putting each network and save/load function into the ```tf.Graph().as_default()``` solves the problem.
```
def net1(...):
    ....
    return model = tflearn.DNN(net)

def net2(...):
   ....
   return model = tflearn.DNN(net)

with tf.Graph().as_default():
    model = net1(...)
    model.save(...)

with tf.Graph().as_default():
    model = net1(...)
    model.load(...)

with tf.Graph().as_default():
    model = net2(...)
    model.fit(...)
    model.save(...)
```

Thanks for you help.
