### ISSUE TITLE
How to cite TFLearn?

### ISSUE THREAD

**Issue by ruizhaogit** [tflearn/tflearn#282]
Hi TFlearn Team,

Could you tell me how to cite TFlern library with bibtex or just mention using it in the literature?

Best,
Rui

**Comment by ShownX** [comment]
Maybe you can cite as website?

**Comment by aymericdamien** [comment]
Thanks for citing the project. For now, you can use that template:
```
@misc{tflearn2016,
       author = {Aymeric Damien and others},
       title = {TFLearn},
       year = {2016} ,
       publisher={GitHub},
       howpublished={\url{https://github.com/tflearn/tflearn}},
}
```
