### ISSUE TITLE
how to load  image data from files?

### ISSUE THREAD

**Issue by albertyou2** [tflearn/tflearn#286]
how to load  image data from files?
Is there a complete example of doing this ?

**Comment by ShownX** [comment]
It is not tflearn issue. You can use opencv, matplot or PIL to load image data.

**Comment by aymericdamien** [comment]
@albertyou2 you can have a look at: http://tflearn.org/data_utils/#image-preloader

**Comment by albertyou2** [comment]
@aymericdamien thank you ! I will have a try

**Comment by vikashg** [comment]
Hi everyone. 
Does the image preloader can only load jpeg images or it can load any type of images. Lets say I have Nifti images (http://nipy.org/nibabel/gettingstarted.html) Do I need to somehow write a loader for Nifti images. ? or can I store lot of numpy files and the image_preloader will automatically understand and load them.
Thanks 
Vikash
