### ISSUE TITLE
naming tensorboard log 

### ISSUE THREAD

**Issue by mbaniasad** [tflearn/tflearn#289]
is there a way to pass a name for tensorboard log?   
I have a system which I can set for running several experiments at once. I need a way to set the name of the output (at least a part of it) to the config that used. for example:
```
lstm_2000input_20epoch
```

**Comment by aymericdamien** [comment]
you can use 'tensorboard_dir' in `DNN` class

**Comment by mbaniasad** [comment]
thanks for the response. I did not know that tensorboard would pick up the data from subfolders as well. thanks
