### ISSUE TITLE
 list index out of range when training 2 models in sequenece

### ISSUE THREAD

**Issue by llealgt** [tflearn/tflearn#297]
Hi , im performing cross validation ,so i have my training call inside some loops(that vary the parameters) , in pseudocode its something like:

param1 = [1,2,3];
param2 = [5,6,7];

for i in param1:
    for j in param2:
        model = train_model(i,j);
        store_metrics(model);

model= select_best();

But for some reason ,the code just works for one iteration , if i mannually call train_model(param1,param2) in different python sessions ,it works fine, so i know my problemn is not related to parameter values, instead it looks as if some cache,temporary files, or session files break my code and as if only one train_model call can be done per python session, any ideas? something like clear_temps()  ?

**Comment by aymericdamien** [comment]
Yes, you may want to use `tf.reset_default_graph()` at the end of each iteration, if you are building the network inside the loop, to prevent from the code to always append ops to the existing  default graph instead of creating a new graph.

**Comment by llealgt** [comment]
Thank you so much! worked great.
