### ISSUE TITLE
"Coordinator stopped with threads still running" happens when using cross-validation

### ISSUE THREAD

**Issue by tuming1990** [tflearn/tflearn#313]
Hi,

I need to use deep neural network for regression (MSE cost function) to evaluate the performance on a dataset. The general idea is leave-one-out cross validation.

The code is as follows:
```python
# Building deep neural network
def make_model():
    input_layer = tflearn.input_data(shape=[None, input_dim])
    dense1 = tflearn.fully_connected(input_layer, 256, activation='relu',
                                 regularizer='L2', weight_decay=0.001)
    dropout1 = tflearn.dropout(dense1, 0.5)
    dense2 = tflearn.fully_connected(dropout1, 256, activation='relu',
                                 regularizer='L2', weight_decay=0.001)
    dropout2 = tflearn.dropout(dense2, 0.5)
    dense3 = tflearn.fully_connected(dropout2, 256, activation='relu')
    dropout3 = tflearn.dropout(dense2, 0.5)
    output = tflearn.fully_connected(dropout3, 5, activation='linear')

    # Regression using SGD with learning rate decay and Top-3 accuracy
    sgd = tflearn.SGD(learning_rate=0.01, lr_decay=0.99, decay_step=1000)
    mse = tflearn.metrics.EuclidianDistance()
    net = tflearn.regression(output, optimizer=sgd, metric=mse,
                                loss='mean_square')
    return net

# cross validation
Y_pred = np.zeros((0, 5))
for i in range(0, num_spk):

    trainX, trainY, testX, testY = make_train_data(All_data, Ytrain, i)

    # feature normalization
    stdnorm = StandardScaler()
    stdnorm.fit(trainX)
    trainX = stdnorm.transform(trainX)
    testX = stdnorm.transform(testX)

    # Training
    with tf.Graph().as_default():
        net = make_model()
        model = tflearn.DNN(net, tensorboard_verbose=0)
        model.fit(trainX, trainY, n_epoch=20, validation_set=(testX, testY),
            show_metric=True, batch_size=256, snapshot_epoch=1,
                shuffle=True, run_id="dense_model{}".format(i))
        Y_pred = np.append(Y_pred, np.reshape(np.mean(model.predict(testX), axis=0), (1,5)), axis=0)
```

The routine is that for each fold a new graph is built to do training. However, this code gives the error "Coordinator stopped with threads still running". I have no idea about how to solve this problem.

Another way I can think of is that all the training is done with same graph. But after each fold, the trained model should be reinitialized for new training data. I didn't find a way to reinitialize the mode.

Any help will be appreciated. Thanks.

**Comment by aymericdamien** [comment]
Could you send the error trace stack?
You can use `tf.reset_default_graph()` to reset the graph instead of using `with tf.Graph().as_default()`

**Comment by tuming1990** [comment]
Thanks @aymericdamien . I will try to use ```python tf.reset_default_graph()```. The error trace stack is:
```python
Exception in thread Thread-4151:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ming/.local/lib/python2.7/site-packages/tflearn/data_flow.py", line 236, in wait_for_threads
    self.coord.join(self.threads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 361, in join
    " ".join(stragglers))
RuntimeError: Coordinator stopped with threads still running: Thread-4150
```

**Comment by tuming1990** [comment]
@aymericdamien ```tf.reset_default_graph()``` works. Thanks again!

**Comment by AdivarekarBhumit** [comment]
Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\Users\Bhumit\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\Bhumit\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Bhumit\Anaconda3\lib\site-packages\tflearn\data_flow.py", line 187, in fill_feed_dict_queue
    data = self.retrieve_data(batch_ids)
  File "C:\Users\Bhumit\Anaconda3\lib\site-packages\tflearn\data_flow.py", line 222, in retrieve_data
    utils.slice_array(self.feed_dict[key], batch_ids)
  File "C:\Users\Bhumit\Anaconda3\lib\site-packages\tflearn\utils.py", line 187, in slice_array
    return X[start]
TypeError: only integer scalar arrays can be converted to a scalar index

Anyone, please suggest solutions for above error
