### ISSUE TITLE
deploy/serve model

### ISSUE THREAD

**Issue by llealgt** [tflearn/tflearn#316]
Hi, this instead of an issue its a question or request for advice. I have trained and tested a model and now i think its ready to deploy inside my application .But the resulting model its like 3gb ,and when i use "load" to read it from disk it takes a while, as well as predicting in new examples, so obviously im not doing it the right way , whats the correct way to deploy/serve a trained model so that it can be called inside your application and predict on new examples with high performance?

**Comment by aymericdamien** [comment]
By default, there are also training variables (such as moving averages, optimizers params, etc...) saved inside the model, but for deploying, you will not need them.
As a hack, you can do:
```
net = ...
model = tflearn.DNN(net)
model.load('your_model', weights_only=True)
model.save('your_model_weights_only')
```
Then only use your new model, it should be smaller.

**Comment by llealgt** [comment]
Thank  you so much, i tried this (and searched for it on the documentation) and it seems as it is what i need but when i add it to my code i get: got an unexpected keyword argument 'weights_only'. Any suggestions?

**Comment by llealgt** [comment]
Problem solved after installing "bleeding edge" version instead of stable version. Thank you so much!!
