### ISSUE TITLE
A proposal about the finetuning?

### ISSUE THREAD

**Issue by burness** [tflearn/tflearn#323]
According the finetuning example [finetuning](https://github.com/tflearn/tflearn/blob/master/examples/basics/finetuning.py), I use the vgg16.tflearn in my project, but I found that it is quite slow than the example in tensorflow [retrain](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/image_retraining/retrain.py). In the retrain.py, it only update the last layer, it calculates the bottleneck values of the images and only update the final layes weight, but in tflearn finetuning.py, the reason that why it is so slow is that it updates the all the layers weights (I'm not sure) after restore the layers' weights? 
It's quite a good method to update the all layers' weight. But in same tasks, we may only need to update the last layer with the new class num.
Could you offer a similar method with the retrain.py?

The layers weight in the model trained by ImageNet should be excellent in the feature representation and the method in retrain.py should be efficient in some tasks.

**Comment by aymericdamien** [comment]
Yes, you can use `trainable=False` for each layer, so that they will not be updated.

**Comment by burness** [comment]
@aymericdamien ,perfect!!!
