### ISSUE TITLE
Temp workaround for tensorflow 0.7.0 relative path issue causes an issue when path is specified correctly

### ISSUE THREAD

**Issue by braddengross** [tflearn/tflearn#333]
This comment and corresponding code in trainer.py at lines 369-370 checks the file path for if it starts with / or ~ and otherwise prepends ./ . However, this means that if the file_name actually starts with ./ you end up with ././ . Is this still needed and if so I think this case needs to be handled.

**Comment by aymericdamien** [comment]
True, we can remove that check, TensorFlow 0.7 is too old now.

**Comment by braddengross** [comment]
Pull request is here: https://github.com/tflearn/tflearn/pull/334/files
