### ISSUE TITLE
PReLU alphas should be channel not pixel wise

### ISSUE THREAD

**Issue by timmeinhardt** [tflearn/tflearn#335]
I think the current implementation of the PReLU layer initializes its alpha parameters for each pixel but as shown in the corresponding [paper](http://arxiv.org/pdf/1502.01852v1.pdf) it should be channel wise. Pixel wise initialization also restricts the input size during inference. 

If this is indeed an error I am happy to submit a pull request.

**Comment by aymericdamien** [comment]
Yes, it indeed seems to be the case. You can go forward and send a PR! Thanks!
