### ISSUE TITLE
Evaluator().predict()

### ISSUE THREAD

**Issue by aigujin** [tflearn/tflearn#336]
Hi,
I follow [extend_tensorflow/trainer.py](tflearn/examples/extending_tensorflow/trainer.py) example with the option of saving the ``best_checkpoint_path`` in  ``tflearn.Trainer``. My question is how do I apply ``Evaluator()`` on my saved model? I am doing the following:
`model = Evaluator([X,Y], model= "path_to_checkpoint")`
`predictions = model.predict(feed_dict={X: X_test})`
But I got an error: `InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_1' with dtype float`. I assume I need to feed values for `Y` in `.predict()` but those are the ones I'd like to get predicted. 
Could you help me this this?
Thanks

**Comment by aymericdamien** [comment]
It should be:
```
model = Evaluator(your_network, model= "path_to_checkpoint")
#model.evaluate({X: ..., Y: ....})
model.predict({feed_dict={X: X_test}})
```

**Comment by aigujin** [comment]
Thanks, that works!
