### ISSUE TITLE
Is it possible to change the tensor shape in the model define process

### ISSUE THREAD

**Issue by ShownX** [tflearn/tflearn#338]
Hello, there,

I want to define the data as
```
Input: 
    Images:(NxM) x height x width x channel, 
    label: N x L
```
Is that possible to change the shape of the tensor in the network definition such as
```
net = input_data(inputs, [-1, NxM, height, width, channel])    # inputs
net = conv_2d(net, 32, 3)    # convolutional neural network
net = do some things here    # change the shape of tensor, maybe tf.reshape(net, (N, -1))?
net = fully_connected(net, L)
```

**Comment by aymericdamien** [comment]
Yes, you can change any tensor shape with `tf.reshape`. Maybe something like that:
```python
net = input_data(inputs, [None, NxM, height, width, channel])    # inputs
net = conv_2d(net, 32, 3)    # convolutional neural network
net = do some things here    # change the shape of tensor, maybe tf.reshape(net, [None, N, -1])?
net = fully_connected(net, L)
```

**Comment by ShownX** [comment]
Unfortunately, it does not work as expected.
Error message:
```
TypeError: Expected int32, got None of type '_Message' instead.
```

**Comment by aymericdamien** [comment]
Oh yeah, my bad, you cannot use None in tf.reshape.
Can you try to give the full dimensions?
something like: `net = tf.reshape(net, [-1, N, M*height*width*channel])`

**Comment by ShownX** [comment]
Thanks. Will try that and will report back.
But how to deal with the problem in the ```fit``` function?
Supposed that using ```batch_size=128```, ```X[0:128]``` and ```Y[0:128]``` are fed to the graph together. But maybe ```X[0:64]``` is labeled as ```Y[0]``` not ```Y[0:68]```, when ```M=64``` here.
Is it possible to deal with this problem?
