### ISSUE TITLE
CNN kills Jupyter kernel

### ISSUE THREAD

**Issue by 4rtemi5** [tflearn/tflearn#339]
While running a normal feedforward Net works fine, when i try to run my own CNN or the simple MNIST-[example](https://github.com/tflearn/tflearn/blob/master/examples/images/convnet_mnist.py) my Jupyter kernel dies every time.
The last thing Jupyter prints is:
 `---------------------------------`
`Training samples: 55000`
`Validation samples: 10000`
`--`

Jupyter Output:
`KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel f3544594-bff6-4421-99fb-fca68b057632 restarted`

I have tried reinstalling tflearn, Jupyter and TensorFlow.
Any ideas what else I could try to fix this?

**Comment by aymericdamien** [comment]
I haven't run into any issue using jupyer notebook. Maybe it has to do with your jupyer notebook version? Can you try to update it?

**Comment by 4rtemi5** [comment]
The version of the notebook server is 4.2.2 and is running on Python 3.5.2.  IPython 5.1.0.

**Comment by 4rtemi5** [comment]
My minimal model looks something like this. Maybe there's something wrong with that...

```
tflearn.config.init_graph(seed=None, log_device=False, num_cores=0, gpu_memory_fraction=.8, soft_placement=True)

dropout = 0.75
dropout2 = .1
learningrate = 0.000045
batchsize = 64

ffIn = tflearn.input_data(shape=[None, len(X_match_train[0])])
ffnet = tflearn.fully_connected(ffIn, 1024, activation='ELU', weights_init=init.xavier())
ffnet = tflearn.dropout(ffnet, dropout)
ffnet = tflearn.fully_connected(ffnet, 1024, activation='ELU', weights_init=init.xavier())

convIn = tflearn.input_data(shape=[None, 11, 11, 78])
convnet = tflearn.conv_2d(convIn, 78, 11, regularizer='L2', weight_decay=0.0001)
convnet = tflearn.fully_connected(convnet, 128, activation='ELU', weights_init=init.xavier())

net = tflearn.merge([ffnet, convnet], mode='concat')
net = tflearn.fully_connected(net, 3, activation='ELU', weights_init=init.xavier())

net = tflearn.regression(net, optimizer='adam', learning_rate=learningrate)

tflearn.config.init_graph (seed=None, log_device=False, num_cores=0, gpu_memory_fraction=.8, soft_placement=True)

# Define model
model = tflearn.DNN(net, 
                    checkpoint_path='./Checkpoints/' + "conv",
                    max_checkpoints=3, 
                    tensorboard_verbose=0,
                    best_checkpoint_path='./Checkpoints/best/', 
                    best_val_accuracy=.46)

# Start training (apply gradient descent algorithm) on GPU
with tf.device("/job:localhost/replica:0/task:0/gpu:0"):
#with tf.device("/cpu:0"):
    model.fit([X_match_train, X_conv_train], 
              y_conv_train, 
              n_epoch=1000, 
              batch_size=batchsize, 
              show_metric=True,
              validation_set=([X_match_eval, X_conv_eval], y_conv_eval),
              shuffle=True,
              run_id="convnet: lr=" + str(learningrate) + "   dr1: " + str(dropout) + "   dr2: " + str(dropout2) + "   bs: " + str(batchsize))
    
eval_val = 100 * model.evaluate([np.array(X_conv_test), np.array(X_match_test)], np.array(y_conv_test), batch_size=128)[0]
print(eval_val)
```

**Comment by 4rtemi5** [comment]
This seems to be a Tensorflow issue. I have seemingly the same problem when building the network in Keras with Tensorflow backend. I'm all out of ideas now... :(

Anyway thanks for your help and please let me know if you have any idea of how i could understand/solve the problem.

**Comment by 4rtemi5** [comment]
PROBLEM SOLVED:
Running a Tensorflow MNIST model in the terminal i got the following error:
```
E tensorflow/stream_executor/cuda/cuda_dnn.cc:347] Loaded runtime CuDNN library: 5005 (compatibility version 5000) but source was compiled with 5103 (compatibility version 5100).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
```

So i updated CUDNN to 5.1 and now everything works.
Thanks again!

**Comment by yahyaeian** [comment]
I had the same problem.
For ANN, everything was fine, but when trying to fitting a CNN, Kernel died.
I tried "conda update conda" and then "conda install cudnn." It worked!

**Comment by chibube** [comment]
> I had the same problem. For ANN, everything was fine, but when trying to fitting a CNN, Kernel died. I tried "conda update conda" and then "conda install cudnn." It worked!

Thank you so much @yahyaeian, spent days trying to solve this issue and your solution worked like a charm

**Comment by Siraj454** [comment]
> I had the same problem. For ANN, everything was fine, but when trying to fitting a CNN, Kernel died. I tried "conda update conda" and then "conda install cudnn." It worked!

Thanks alot , i spent whole night and then find this one, it really solved my issue, i run 'conda update conda' in base enviroment while i run  'conda install cudnn'' in the env where tensorflow was installed on anconda.
