### ISSUE TITLE
Implement dynamic length RNNs

### ISSUE THREAD

**Issue by 50m30n3** [tflearn/tflearn#34]
Currently the use of RNNs in tflearn is quite limited by the fact that they can only operate on fixed length sequences. This limits real world applicability quite a bit since a lot of real world data doesn't have a fixed length, or has a length that exceeds the number of steps that can be unrolled on a normal GPU. 

Also, when training a network on a continuous sequence like in the shakespeare example this makes the training a lot slower and the training set a lot bigger than it needs to be since overlapping sequences need to be fed into the network on every step, instead of just continuing from the state where the network was at before. Of course the also severely limits the attention span of the RNN.

I realize that until a short while ago this was a limitation of tensorflow itself, but they recently implemented support for dynamic RNNs and the option to iterate over variable length data. More info can be found here: https://github.com/tensorflow/tensorflow/issues/208

I would really appreciate this feature since tflearn has been the first machine learning library I've actually been able to wrap my head around and easily get good results with.

**Comment by xoryouyou** [comment]
+1

**Comment by aymericdamien** [comment]
Yes, currently RNNs in TFLearn are a bit limited. It is planned to add a dynamic RNN support and a state saver, along with some usage examples (so that users can easily understand how to use it).
There is a beta implementation here: https://github.com/tflearn/tflearn/blob/master/tflearn/layers/recurrent.py#L291, but it haven't be tested yet (Using While and TensorArray).

**Comment by 50m30n3** [comment]
Ahh, that looks interesting. Is it possible to run the dynamic_rnn with single timesteps and keep the internal status in between steps so I can generate one output tensor for each input tensor?

**Comment by aymericdamien** [comment]
Should be possible by changing a bit the code, 
https://github.com/tflearn/tflearn/blob/master/tflearn/layers/recurrent.py#L344 here states should be saved, and add an initiale_state argument to RNNCell, so you can set custom state for 'initiale_state' of `_rnn` function.
In the future, we should incorporate that, so we could easily retrieve internal states and assign some custom states as well (ladding a 'return_states' and 'initial_states' arguments to RNNs).

**Comment by 50m30n3** [comment]
Cool. I'm gonna test the dynamic_rnn when I have time for that and see how far I get.

My goal is to implement a variable length seq2seq model, and while that should work with the current dynamic_rnn, training it seems really inefficient right now since the state of the network gets reset after every output sample, so you need to feed all the previous input samples plus the new one in just to get one more output sample. Or am I missing something important here?

**Comment by aymericdamien** [comment]
I updated RNN functions so that they support an initial state. So in seq2seq, you can feed your decoder with the encoder hidden states. About dynamic RNNs, only final state is returned (because your inputs has dynamic length).

**Comment by 50m30n3** [comment]
Super cool, thank you!

**Comment by brunoalano** [comment]
@50m30n3 did you figure out how to implement variable length seq2seq? Can you provide the code?
