### ISSUE TITLE
How many weights are learned?

### ISSUE THREAD

**Issue by ruizhaogit** [tflearn/tflearn#342]
Hi TFlearn Team,

Is it possible to know how many weight parameters are learned from the saved models?

For, example, file "-2000" means the parameters saved at the 2000 training step. It has 6.4 MB. Can we know how many parameters are there in the neural network? 

Best,
Rui

**Comment by aymericdamien** [comment]
You can use `tf.trainable_variables()` to retrieve all weights, and using their shape, you can calculate your total number of parameters. 

Also note that when you save a model, you also save some other values that are not weights (such as optimizer specific params, moving averages, etc...), if you want to get rid of it, you can load a model with 'load(..., weights_only=True)' to load weights only, and re-save your model (to have a model that only contains weights)
