### ISSUE TITLE
Example embedding -> conv_1d not working

### ISSUE THREAD

**Issue by grivescorbett** [tflearn/tflearn#345]
Using this code from https://github.com/tflearn/tflearn/blob/master/examples/nlp/cnn_sentence_classification.py#L45

    network = tfl.input_data(shape=[None, 100], name='input')
    network = tfl.embedding(network, input_dim=10000, output_dim=128)
    network = tfl.conv_1d(network, 128, 3, padding='valid', activation='relu', regularizer="L2")

I'm getting an error:

    AssertionError: Incoming Tensor shape must be 3-D

Any thoughts?

**Comment by grivescorbett** [comment]
Ahh, pulled the trigger too soon.  I had an old version.  My apologies.

**Comment by nishaa113** [comment]
i'm having this issue. can you please tell me what is the solution for this???
