### ISSUE TITLE
Using pre-trained word vectors in embedding layer

### ISSUE THREAD

**Issue by yzgysjr** [tflearn/tflearn#35]
Hi, thank you for creating such a wonderful project.

I am now wondering if there is an embedding layer using pre-trained weights of word vectors? Thank you!

**Comment by aymericdamien** [comment]
Yes, actually you can load pre-trained weights:
You can access the variable inside "tflearn.embedding" layer, and assign it any pre-trained value.

For example:
```python
# Network building
net = tflearn.input_data([None, 200])
# create embedding weights, set trainable to False, so weights are not updated
net = tflearn.embedding(net, input_dim=20000, output_dim=128, trainable=False, name="EmbeddingLayer")
net = tflearn.lstm(net, 128)
net = tflearn.dropout(net, 0.5)
net = tflearn.fully_connected(net, 2, activation='softmax')
net = tflearn.regression(net, optimizer='adam',
                         loss='categorical_crossentropy')

# Training
model = tflearn.DNN(net, clip_gradients=0., tensorboard_verbose=0)

# Retrieve embedding layer weights (only a single weight matrix, so index is 0)
embeddingWeights = tflearn.get_layer_variables_by_name('EmbeddingLayer')[0]
# Assign your own weights (for example, a numpy array [input_dim, output_dim])
model.set_weights(embeddingWeights, YOUR_WEIGHTS)

# Train with your custom weights
model.fit(trainX, trainY, validation_set=(testX, testY), show_metric=True,
          batch_size=128)
```

**Comment by yzgysjr** [comment]
@aymericdamien Thank you for your information :)

**Comment by jimmyangc** [comment]
@aymericdamien Thanks for your explain for the question(Using pre-trained word vectors in embedding layer). It was a great help! I just was wondering if you could help me with one more question as follows:

I already trained my own word embeddings with wikipedia corpus, but how could I use this as the initial word embedding for LSTM embedding layer? (I did not understand the meaning of input_dim=20000, output_dim=128, in _net = tflearn.embedding(net, input_dim=20000, output_dim=128, trainable=False, name="EmbeddingLayer")_)  Does it means that the tflearn randomly initialize the word embedding with 20000 dimension and 128 dimension)

Again, thanks a lot!

**Comment by aymericdamien** [comment]
For this purpose, you may design your own layer (in a similar way with `tflearn.embedding`), TensorFlow supplies `tf.nn.embedding_lookup` to achieve what you need (https://www.tensorflow.org/versions/r0.8/api_docs/python/nn.html#embedding_lookup).

**Comment by jrzaurin** [comment]
I know this is closed, but I am wondering, in the code @aymericdamien shows above, would it be possible to initialise weights with an embedding matrix and trainable False, for example:

    embedding_layer = input_data(shape=[None,max_seq_len], name='input')
    embedding_layer = embedding(
    	embedding_layer,
    	input_dim=vocab_size,
    	output_dim=embedding_dim,
            weights_init = embedding_matrix, # this would be a 2D tensor
    	trainable=False,
    	name="EmbeddingLayer")

 and the not having to use:

    # Retrieve embedding layer weights (only a single weight matrix, so index is 0)
    embeddingWeights = tflearn.get_layer_variables_by_name('EmbeddingLayer')[0]
    # Assign your own weights (for example, a numpy array [input_dim, output_dim])
    model.set_weights(embeddingWeights, YOUR_WEIGHTS)

is this possible? or correct?
