### ISSUE TITLE
How to get_weights from bidirectional_rnn(net, GRU(64), GRU(64)) ?

### ISSUE THREAD

**Issue by ruizhaogit** [tflearn/tflearn#350]
Hi Tflearn Team,

how to get weighs from bidirectional_rnn layer, which has cells inside?

......
BiRNN1 = tflearn.bidirectional_rnn(net, GRUCell(64), GRUCell(64), return_seq=True)
......
print model.get_weights(BiRNN1.W) 
AttributeError: 'list' object has no attribute 'W'

This also doesn't work:
model.get_weights(tflearn.get_layer_variables_by_name('BidirectionalRNN_1/BiRNN_FW//Gates')[0]) 
IndexError: list index out of range

Thanks,
Rui

**Comment by aymericdamien** [comment]
You can access them using `tflearn.get_layer_variables_by_name(LAYER_NAME)`
