### ISSUE TITLE
Is there any way to disable printing loss?

### ISSUE THREAD

**Issue by jyoungrok** [tflearn/tflearn#356]
when i use "fit" function, loss is printed on console each step
I guess if i can disable printing it, the speed of learning process will be faster
However, i don't know how to disable... (it's possible to disable printing accuracy though)
Is there any way?

**Comment by aymericdamien** [comment]
To modify this, you will have to change the source of tflearn. About your issue, it only may be an issue if you have really few features and a small batch size. So you could also simply try to use a larger batch size.

**Comment by jyoungrok** [comment]
Thanks for your reply
I'd better use a larger batch size.
