### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by benmohta** [tflearn/tflearn#360]
Hi,

I am trying to get into TFLearn at the moment. I am neither very experienced with TFLearn nor with Tensorflow itself. I encountered a problem, which I can't figure out myself. Maybe you could have a look and give me a pointer.

This is my code:

`import pandas as pd
import numpy as np

df = pd.read_csv('synthlog/csv/patterns.csv')

encode_problems = lambda x, series: np.where(series == x)[0][0]

series = df['problem'].unique()
df['encoded_problem'] = df['problem'].apply(lambda x: encode_problems(series,x))

import tflearn

from tflearn.data_utils import to_categorical

labels = to_categorical(df['encoded_problem'], 7)

data = df[list(range(300))]
#data = df.iloc[:, range(300)]

from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, labels, test_size=0.4)

net = tflearn.input_data(shape=[None, 300])
net = tflearn.fully_connected(net, 100)
net = tflearn.fully_connected(net, 100)
net = tflearn.fully_connected(net, 7, activation='softmax')
net = tflearn.regression(net)

model = tflearn.DNN(net)

model.fit(X_train, y_train, batch_size=len(X_train), n_epoch=1, show_metric=True)
`
I get the following output:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-15-878868a33789> in <module>()
      1 model = tflearn.DNN(net)
      2 
----> 3 model.fit(X_train, y_train, batch_size=len(X_train), n_epoch=1, show_metric=True)

/usr/local/lib/python3.5/dist-packages/tflearn/models/dnn.py in fit(self, X_inputs, Y_targets, n_epoch, validation_set, show_metric, batch_size, shuffle, snapshot_epoch, snapshot_step, excl_trainops, validation_batch_size, run_id, callbacks)
    179         # TODO: check memory impact for large data and multiple optimizers
    180         feed_dict = feed_dict_builder(X_inputs, Y_targets, self.inputs,
--> 181                                       self.targets)
    182         feed_dicts = [feed_dict for i in self.train_ops]
    183         val_feed_dicts = None

/usr/local/lib/python3.5/dist-packages/tflearn/utils.py in feed_dict_builder(X, Y, net_inputs, net_targets)
    287                 X = [X]
    288             for i, x in enumerate(X):
--> 289                 feed_dict[net_inputs[i]] = x
    290         else:
    291             # If a dict is provided

IndexError: list index out of range

I appended the notebook and the csv file here.
[viewing_the_synthetic_log_data.zip](https://github.com/tflearn/tflearn/files/498799/viewing_the_synthetic_log_data.zip)

If you have any further ideas for improvement, please let me know.

Thanks in advance.

**Comment by 4rtemi5** [comment]
From my experience this error usually happens when you run the notebook cell for multiple times. Try restarting the kernel and to run it again. Every time you build the network you have to restart the the kernel or otherwise the code will try to keep adding layers to it. Hope this helps!

**Comment by benmohta** [comment]
Thank you very much. It solved the issue.

**Comment by yoavram** [comment]
Thanks, restarting the kernel helped.
Any chance that TFLearn can output a better exception/error message?

**Comment by kevinushey** [comment]
Any chance that this will "just work" in a future iteration of `tflearn`? It would be greatly useful when attempting to build a model iteratively / in an interactive Python session.

**Comment by dorwalprateek** [comment]
Add these couple of lines at the start of your code, and it works just fine each time.

import tensorflow as tf
tf.reset_default_graph()

**Comment by Ather23** [comment]
This worked for me: 
import tensorflow as tf
tf.reset_default_graph()

Thank you

**Comment by allwaysLearner** [comment]
Very helpful!
Thanks a lot!
import tensorflow as tf
tf.reset_default_graph()

**Comment by aysebilgegunduz** [comment]
it didn't work for me i still get the same error. And i checked all my requirement and tflearn is up-to-date.

**Comment by gouthamand** [comment]
Hello All, 

Has this error been fixed ?. I have used tf.reset_default_graph().

call trace narrows to this code in /utils.py and feed_dict function.
/opt/conda/lib/python3.6/site-packages/tflearn/utils.py in feed_dict_builder(X, Y, net_inputs, net_targets)
    298                 X = [X]
    299             for i, x in enumerate(X):
--> 300                 feed_dict[net_inputs[i]] = x

update on this would be really appreciated.

**Comment by gouthamand** [comment]
One of things I observed is that following code created two separate input tensor
iname = input_data(shape= [None,name.shape[1]], name="iname" )
emb_name = embedding(iname, MAX_TEXT, 60//3)

[<tf.Tensor 'iname/X:0' shape=(?, 13) dtype=float32>,
<tf.Tensor 'netname/X:0' shape=(?, 13) dtype=float32>],

is that correct ?. Shouldn't it be create one only one tensor. When you provide one input for model.fit generates above stated error
list index out of range.

How to avoid generating two different input tensor.

Thanks in advance for the help.

**Comment by abd-ozos** [comment]
Thanks a lot..! It worked for me
