### ISSUE TITLE
WARNING:Passing a `GraphDef` to the SummaryWriter is deprecated. Pass a `Graph` object instead, such as `sess.graph`.

### ISSUE THREAD

**Issue by JohnAllen** [tflearn/tflearn#37]
When running an `lstm_generator*.py` and TensorFlow 0.8.

Guessing this an `0.8` issue and will go away once tflearn is upgraded but thought I would post it in case not.

**Comment by aymericdamien** [comment]
Yes, this is because GraphDef is deprecated in new TF version. We need to change SummaryWriter argument to a Graph instead of a GraphDef. This should be a quick fix, just have to be sure that TF 0.7  is still compatible with it.
