### ISSUE TITLE
Call the pre-trained model from C++

### ISSUE THREAD

**Issue by pxlong** [tflearn/tflearn#38]
Hi Aymeric,

First of all, thank you for creating such an amazing project, I really love this API, it makes my research projects much easier, many thanks!

I'd like to call the pre-trained (and saved on the disk)  model to predict new Y from C++ (that means I will load the saved model and pass X to the model in C++), I am just wondering which is the best way to do this?  Thanks.

**Comment by aymericdamien** [comment]
Hi, glad to hear :)
Yes, you can train a model and use TensorFlow C++ API to predict. Here is a link that tell you how to do:
https://tensorflow.googlesource.com/tensorflow/+/master/tensorflow/g3doc/api_docs/cc/index.md
Basically, you just need to load the graph model in the C++ API. Graph model are both compatible with Tensorflow python/c++ api.
