### ISSUE TITLE
Support for multiple DNN?

### ISSUE THREAD

**Issue by C-Pro** [tflearn/tflearn#381]
Hi!
I need to train and use two DNNs in parallel (kind of dueling DQN).
First DNN works ok, but when I try to call fit or predict on second one I get weird errors about input value shapes. Networks are identical, data format is identical too - so there is something wrong with defining second network.

Generic example:

```
import tflearn
import random

X = [[random.random(),random.random()] for x in range(1000)]
Y = [[x[1],x[0]] for x in X]

n = tflearn.input_data(shape=[None,2])
n = tflearn.fully_connected(n, 2)
n = tflearn.regression(n)
m = tflearn.DNN(n)

m.fit(X, Y, n_epoch = 20)
print(m.predict([[0.9,0.1]]))

n2 = tflearn.input_data(shape=[None,2])
n2 = tflearn.fully_connected(n2, 2)
n2 = tflearn.regression(n2)
m2 = tflearn.DNN(n2)

Y = [[x[0],x[0]] for x in X]

#Here I will get an error
m2.fit(X, Y, n_epoch = 20)
print(m2.predict([[0.9,0.1]]))
```

Produces error:

```
Traceback (most recent call last):
  File "2_dnn_test.py", line 25, in <module>
    m2.fit(X, Y, n_epoch = 20)
  File "/home/cpro/.pyenv/versions/3.5.1/lib/python3.5/site-packages/tflearn/models/dnn.py", line 157, in fit
    self.targets)
  File "/home/cpro/.pyenv/versions/3.5.1/lib/python3.5/site-packages/tflearn/utils.py", line 267, in feed_dict_builder
    feed_dict[net_inputs[i]] = x
IndexError: list index out of range
```

Is it possible to use two networks at the same time?

**Comment by C-Pro** [comment]
Looks like I should add

with tensorflow.Graph().as_default():
    #define model here
to prevent TFLearn to append both models to default graph. With this addition everything works.

Is it correct? If it is a recommended way, I think it should be added to documentation somewhere.

**Comment by rmno** [comment]
This should work.

graph = tensorflow.Graph()
tensorflow.reset_default_graph()
with graph.as_default():
      tflearn.config.init_training_mode()

**Comment by C-Pro** [comment]
It works, but now I get many warnings like:

```
WARNING:tensorflow:Error encountered when serializing data_preprocessing.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'NoneType' object has no attribute 'name'
WARNING:tensorflow:Error encountered when serializing data_preprocessing.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'NoneType' object has no attribute 'name'
WARNING:tensorflow:Error encountered when serializing data_augmentation.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'NoneType' object has no attribute 'name'
WARNING:tensorflow:Error encountered when serializing data_augmentation.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'NoneType' object has no attribute 'name'
WARNING:tensorflow:Error encountered when serializing summary_tags.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'dict' object has no attribute 'name'
WARNING:tensorflow:Error encountered when serializing summary_tags.
Type is unsupported, or the types of the items don't match field type in CollectionDef.
'dict' object has no attribute 'name'
```

**Comment by rmno** [comment]
Please post your updated code. Also, why would you want to train 2 concurrent models in one python process?

**Comment by C-Pro** [comment]
Here it is:
https://github.com/C-Pro/tictactoe_dqn_tf
I run learn.py to train networks. When they are saved, in https://github.com/C-Pro/tictactoe_dqn_tf/blob/master/simple_dqn.py#L37 I get warnings above.

**Comment by rmno** [comment]
My guess is that model.save is trying to get CollectionDef from the default graph.
https://github.com/tflearn/tflearn/blob/master/tflearn/helpers/trainer.py#L337

tflearn is built around the assumption of a single model in the default graph. It would be a big improvement if models er seperated by default. 

It would take some change here.
https://github.com/tflearn/tflearn/blob/master/tflearn/helpers/trainer.py#L70

helpers.trainer.Trainer__init__ could take some graph as input and the saver should we rewritten to access the right graph.

**Comment by aymericdamien** [comment]
Thanks for your help @rmno, you need to reset the default graph in your case at each model definition.
```python
import tensorflow as tf
import tflearn
import random

X = [[random.random(),random.random()] for x in range(1000)]
Y = [[x[1],x[0]] for x in X]

n = tflearn.input_data(shape=[None,2])
n = tflearn.fully_connected(n, 2)
n = tflearn.regression(n)
m = tflearn.DNN(n)

m.fit(X, Y, n_epoch = 20)
print(m.predict([[0.9,0.1]]))
m.save('test1')

tf.reset_default_graph()

n2 = tflearn.input_data(shape=[None,2])
n2 = tflearn.fully_connected(n2, 2)
n2 = tflearn.regression(n2)
m2 = tflearn.DNN(n2)

Y = [[x[0],x[0]] for x in X]

#Here I will get an error
m2.fit(X, Y, n_epoch = 20)
print(m2.predict([[0.9,0.1]]))
m2.save('test2')
```

This is running fine, I do not get any error about save() though.

**Comment by C-Pro** [comment]
Hi!
`tf.reset_default_graph()` will reset first dnn (m)? In this example it is ok, but in my task i need both models to be available. Is it possible, or I should create models in separate threads or even processes?

**Comment by aymericdamien** [comment]
Yes, it will reset first dnn too.
Without reseting graph, you can enclose them with a particular graph (also .save(), to fix the warning):
```python
import tensorflow as tf
import tflearn
import random

X = [[random.random(),random.random()] for x in range(1000)]
Y = [[x[1],x[0]] for x in X]

g1 = tf.Graph()
g2 = tf.Graph()

with g1.as_default():
  n = tflearn.input_data(shape=[None,2])
  n = tflearn.fully_connected(n, 2)
  n = tflearn.regression(n)
  m = tflearn.DNN(n)

with g2.as_default():
  n2 = tflearn.input_data(shape=[None,2])
  n2 = tflearn.fully_connected(n2, 2)
  n2 = tflearn.regression(n2)
  m2 = tflearn.DNN(n2)

Y = [[x[0],x[0]] for x in X]

m.fit(X, Y, n_epoch = 20)
print(m.predict([[0.9,0.1]]))
with g1.as_default():
  m.save('test1')

m2.fit(X, Y, n_epoch = 20)
print(m2.predict([[0.9,0.1]]))
with g2.as_default():
  m2.save('test2')
```

**Comment by C-Pro** [comment]
Oh, excellent! Now all works flawless!

**Comment by AAvi** [comment]
why dont you loop it?
