### ISSUE TITLE
Unable to import image_preloader

### ISSUE THREAD

**Issue by Vikramank** [tflearn/tflearn#382]
I pip installed tflearn and found there is no function named inside "data_utils". However, the same function is present in data_utils.py found in the official github page
https://github.com/tflearn/tflearn/blob/4ba8c8d78bf1bbdfc595bf547bad30580cb4c20b/tflearn/data_utils.py

**Comment by aymericdamien** [comment]
Can you try to install latest version?
```
pip install --upgrade git+https://github.com/tflearn/tflearn.git
```

**Comment by Vikramank** [comment]
I did try that too! still the function was missing. maybe its a bug

**Comment by aymericdamien** [comment]
How are you importing image_preloader? Maybe it is the issue, you should:
```
from tflearn.data_utils import image_preloader
```
Or also, verify that you do not have multiple python, and that you updated the correct lib

**Comment by Vikramank** [comment]
I reinstalled tflearn and it works fine ! thanks
