### ISSUE TITLE
Weight sharing documentation mistake?

### ISSUE THREAD

**Issue by psmaragdis** [tflearn/tflearn#385]
Hello,
First of all thanks for this very useful project! It's great to have it.

I've been working on sharing weights and I'm stuck with the code example in: 

http://tflearn.org/getting_started/#scopes-weights-sharing

There's mention of the function ``tf.arg_ops()``, but I can't find any mention of this function anywhere in the TensorFlow documentation. Am I missing something, or is this a mistake in the TFLearn documentation?

Thanks!

**Comment by aymericdamien** [comment]
Sorry, it is a typo, it should be `tf.arg_scope`

**Comment by psmaragdis** [comment]
Thanks, it looks like it should be ``tf.contrib.framework.arg_scope`` though, not ``tf.arg_scope``

**Comment by ashishkr23** [comment]
@psmaragdis Hi, i am stuck with the same weight sharing issue, were you able to get this example to work ?
Thanks

**Comment by psmaragdis** [comment]
Yes, here's what I ended up using:

```
            # Split the input data to one batch per GPU
            self.ins = tf.split( 0, ngpu, x)
            self.out = tf.split( 0, ngpu, y)

            # Get a cost and gradient from each GPU's batch
            grads = []
            cost = 0
            for i in range( ngpu):
                if i > 0:
                    tf.get_variable_scope().reuse_variables()
                with tf.device('/gpu:' + str( i)):
                    with tf.contrib.framework.arg_scope([tflearn.variables.variable], device='/cpu:0'):
                        costs = cost_fun( self.model( self.ins[i]), self.out[i])
                        grads.append( opt.compute_gradients( costs))

                    # Keep track of overall cost
                    cost += costs

            # Average the gradients over all GPUs
            avgrad = []
            for gv in zip( *grads):
                gg = []
                for g,_ in gv:
                    gg.append( tf.expand_dims( g, 0))
                gr = tf.reduce_sum( tf.concat( 0, gg), 0)
                avgrad.append( (gr, gv[0][1]))

            # Return ops to update the weights and report the cost
            return [opt.apply_gradients( avgrad),cost]
```

**Comment by ashishkr23** [comment]
thanks @psmaragdis  i was doing the same thing , turns out i was using a slightly older verison of tflearn
still haven't gotten it to work with tf slim though
