### ISSUE TITLE
How to avoid displaying "zero" accuracy values

### ISSUE THREAD

**Issue by OlivierData** [tflearn/tflearn#386]
For instance, there is sometimes a problem computing correct Accuracy or Loss value like this : 

Wall time,Step,Value
1476095817.139799,101,0.5328580141067505
1476095822.768647,202,0.528208315372467
1476095828.310494,303,0.5269683599472046
1476095833.724291,404,0.5378177165985107
1476095839.298664,505,0.5402975678443909
**1476095843.776616,606,0.0**
1476095849.210967,707,0.551146924495697
1476095854.313135,808,0.554246723651886

![incorrect-accuracy-value-bad-display-tensorboard](https://cloud.githubusercontent.com/assets/22744273/19234424/ea764330-8eeb-11e6-8f09-a4eb459b0d4e.png)

You can see in Accuracy / Validation that this "zero value" has nothing to do here and should be ignored.
Is there a simple way to avoid displaying zero accuracy values in TensorBoard or is is possible to avoid writing summary when accuracy or loss equals zero ?

Thanks

**Comment by jakubsimanek** [comment]
I have also encountered this issue. During my run, I was also monitoring some sanity-checks in `validation_monitors` including `sum(y_true)`. At this "zero-accuracy/validation" step, the `sum(y_true)` was zero (it was constant and positive in all other steps). Therefore, I think that somehow the data didn't get into the placeholders.

This occurred only once in thousands of validation steps and both the training and validation continued normally.

I think it is correct, that TensorBoard displays these values by default. Not sure if there is a way to avoid it.

**Comment by OlivierData** [comment]
I agree with you that TensorBoard is right displaying these zero values by default. It is useful to know there is sometimes exploding gradient or computing mistakes.

On the other hand it would be useful to be able to hide these points because it is really annoying when you want to monitor precisely your accuracy or compare it with other runs without always zooming/resizing charts.

In my case this issue occurres 1% - 2% of the time (so often once each run). I suppose it depends on your data. 

I hope there will be an option (checkbox) in future TensorBoard releases or maybe that could be an improvement in tflearn with a kind of option like tensorboard_only_positive=true to avoid writing accuracy result in the summary when value equals zero.

**Comment by OlivierData** [comment]
@aymericdamien 
I noticed a tiny bug : the last epoch validation accuracy is not added to the summary. 

It would be also great to add an ["tensorboard_only_positive=true" option to avoid writing accuracy result in the summary when value accuracy equals zero] while fixing this bug.

**Comment by OlivierData** [comment]
I share my solution to fix this issue. If you want to avoid TensorBoard to display "zero" validation accuracy values, simply add this line in [trainer.py](https://github.com/tflearn/tflearn/blob/master/tflearn/helpers/trainer.py)  at the end of `if validation_set is not None:` block : 

`self.val_summary_op = tf.case([(tf.less_equal(self.val_acc_T, 0), lambda: tf.constant(""))], default=lambda: self.val_summary_op)`
