### ISSUE TITLE
Question: how to use rnn in context of image sequence classification in TFLearn?

### ISSUE THREAD

**Issue by amirbar** [tflearn/tflearn#387]
Hi,

I saw the example code of using LSTM cells in TFLearn, classifying mnist images.
I want to classify an image sequence. I'm not sure though how to achieve this in TFLearn, but I thought maybe to go for this architecture:

1) Conv
2) Max Pooling
.... repeat
3) Fully connected
4) LSTM
5) SoftMax

From what I understand normal layers receive this shape type: 
(batch_size, height, width, depth)
while LSTM: 
(batch_size, sequence_length, input_length)

I thought of reshaping the input 
from: 
(batch_size, height, width, depth) 
to: 
(batch_size, sequence_length, height \* width \* depth) 

but i'm not sure this how this should work.
Am I missing something? Any advice?

**Comment by OlivierData** [comment]
You just have to add a reshape op before lstm() : 
network = tflearn.reshape(network, [-1, fully_connected_dim, 1])

Technically it works but I don't know if it makes sense to combine CNN and RNN in this way. Actually you can just use one lstm to directly classify images.

**Comment by amirbar** [comment]
Actually I want to classify an image sequence.. So I treat every image as occurring in a different time step and every image in the sequence is attached with a label
 
So i'm trying to achieve one of these architectures:

a) Decision for a whole sequence
b) Decision for every image in the sequence, taking into account the past


I edited the post because I see it wasn't clear enough..

**Comment by OlivierData** [comment]
In my opinion you can achieve it using just a RNN following [RNN Pixels example](https://github.com/tflearn/tflearn/blob/master/examples/images/rnn_pixels.py) and modifying input data in order to put each image pixels in the last dimension.

Another way would be to feed a RNN direclty with a sequence of labels.

**Comment by amirbar** [comment]
Ok I came up with this model definition:

```python
def rnn_conv_lstm_model(width, height, sequence_length):`
    network = tflearn.input_data(shape=[None, sequence_length, height, width, 1])
    network = tflearn.reshape(network, [-1, height, width, 1])`
    network = tflearn.conv_2d(network, 32, 3, activation='relu')
    network = tflearn.max_pool_2d(network, 2)
    network = tflearn.conv_2d(network, 64, 3, activation='relu')
    network = tflearn.conv_2d(network, 64, 3, activation='relu')
    network = tflearn.max_pool_2d(network, 2)
    network = tflearn.reshape(network, [-1, sequence_length, (height/2**2)*(width/2**2)*64])
    network = tflearn.lstm(network, 512)
    network = tflearn.fully_connected(network, 2, activation='softmax')
    network = tflearn.regression(network, optimizer='adam', loss='categorical_crossentropy', learning_rate=0.001, name="output1")
    return network
```
Basically I think the CNN should extract the image feature and then feed it to the RNN as a sequence, identified by one label.

@OlivierData what do you think?

**Comment by OlivierData** [comment]
Well, I guess it's not the best way to do what you want. As I said it works technically if you reshape your tensor with a good shape (you can use a fully_connected layer before reshaping or even [flatten](http://tflearn.org/layers/core/#flatten) the tensor).
As I understand your problem, you should try a [Time Distributed layer](http://tflearn.org/layers/core/#time-distributed) and apply conv_2d and max_pool to every timestep.
`network = time_distributed(network, conv_2d, [64, 3], scope='tconv')`
Then you can feed a lstm layer with sequences of images already "conved" and "pooled".

**Comment by amirbar** [comment]
ok so I modified to the following model using _time distributed layer_:
```python
def rnn_conv_lstm_model(width, height, sequence_length):
    network = tflearn.input_data(shape=[None, sequence_length, height, width, 1])
    network = tflearn.time_distributed(network, tflearn.conv_2d, [32, 3])
    network = tflearn.time_distributed(network, tflearn.max_pool_2d, [2])
    network = tflearn.time_distributed(network, tflearn.conv_2d, [64, 3])
    network = tflearn.time_distributed(network, tflearn.conv_2d, [64, 3])
    network = tflearn.time_distributed(network, tflearn.max_pool_2d, [2])
    network = tflearn.reshape(network, [-1, sequence_length, (height/2**2)*(width/2**2)*64])
    network = tflearn.lstm(network, 512)
    network = tflearn.fully_connected(network, 2, activation='softmax')
    network = tflearn.regression(network, optimizer='adam', loss='categorical_crossentropy', learning_rate=0.001, name="output1")
    return network
```

then I got the following error:

>   File "/usr/local/lib/python2.7/dist-packages/tflearn/layers/core.py", line 631, in time_distributed
    x = [fn(x[i], *args) for i in range(timestep)]
  File "/usr/local/lib/python2.7/dist-packages/tflearn/layers/conv.py", line 65, in conv_2d
    assert len(input_shape) == 4, "Incoming Tensor shape must be 4-D"
AssertionError: Incoming Tensor shape must be 4-D

Looks like it happens in core.py, inside time_distributed function:
```python
    x = tf.split(1, timestep, incoming)
```

so this line actually create tensors of shape (?, 1, height, width, 1) which do not fit the conv operator.

I fixed it locally by changing to tf.unpack which acts as the current code + squeeze and used tf.reshape on the output so we're able to concatinate in the end.. I propose the pull request above, @aymericdamien what do you think?

**Comment by OlivierData** [comment]
conv_2d layer expects a 4 dimensional tensor. 
You can use a conv_3d layer if your input tensor has 5 dimensions.

**Comment by OlivierData** [comment]
There is a Google paper about combination of CNN+LSTM+DNN (called CLDNN). They describe a possible architecture. 
http://static.googleusercontent.com/media/research.google.com/fr//pubs/archive/43455.pdf

![capture d ecran 2016-10-19 a 10 51 40](https://cloud.githubusercontent.com/assets/22744273/19512095/8f0ab49e-95ea-11e6-8332-a855cadd3161.png)

**Comment by amirbar** [comment]
This one is also relevant:
https://arxiv.org/pdf/1411.4389v4.pdf

2016-10-19 11:56 GMT+03:00 OlivierData <notifications@github.com>:

**Comment by matthewswogger** [comment]
So has anyone been able to get either one of these Recurrent/Convolutional nets to actually work with tflearn?

**Comment by amirbar** [comment]
yes
what architecture are you interested in?

2017-01-06 2:05 GMT+02:00 Matthew Swogger <notifications@github.com>:

**Comment by despoisj** [comment]
Hi, I'm also interested as I'm trying to get a CNN-LSTM to work in Tflearn.
What is the final code you came up with ?

**Comment by yossineo** [comment]
Me 2. any one has code with tflearn for cnn-lstm? for instance to integrate it with  vgg-16 or a toy example.

**Comment by despoisj** [comment]
Hi. Try this https://github.com/despoisj/DeepEyeControl/blob/master/model.py
Note that I had trouble with the LSTM padding so ended up doing manually/change the base padding function.

**Comment by amirbar** [comment]
I think something like this should work:

network = input_data(shape=[None, sequence_length, FLAGS.IMAGE_SIZE,
FLAGS.IMAGE_SIZE, 1])
network = tflearn.reshape(network, [-1, FLAGS.IMAGE_SIZE, FLAGS.IMAGE_SIZE, 1])
network = tflearn.conv_2d(network, 32, 3, activation='relu', name='conv1')
network = tflearn.max_pool_2d(network, 2, name='maxpool1')
network = tflearn.dropout(network, 0.3)
network = tflearn.conv_2d(network, 64, 3, activation='relu', name='conv2')
network = tflearn.conv_2d(network, 64, 3, activation='relu', name='conv3')
network = tflearn.max_pool_2d(network, 2, name='maxpool2')
network = tflearn.dropout(network, 0.3)
network = tflearn.conv_2d(network, 128, 3, activation='relu', name='conv4')
network = tflearn.conv_2d(network, 128, 3, activation='relu', name='conv5')
network = tflearn.max_pool_2d(network, 2, name='maxpool3')
network = tflearn.dropout(network, 0.3)
network = tflearn.reshape(network, [-1, sequence_length,
                                    int((FLAGS.IMAGE_SIZE / 2 ** 3) *
(FLAGS.IMAGE_SIZE / 2 ** 3) * 128)])
network = tflearn.lstm(network, 512)
network = tflearn.dropout(network, 0.5)
network = fully_connected(network, 2, activation='softmax', name="fc1")
network = regression(network, optimizer=FLAGS.OPTIMIZER,
loss='categorical_crossentropy', learning_rate=FLAGS.LR)


2017-03-02 14:35 GMT+02:00 Julien Despois <notifications@github.com>:

**Comment by yossineo** [comment]
@amirbar 

Hi amir thaks a lot , trying to understand the code.

can u explain those lines?

network = input_data(shape=[None, sequence_length, FLAGS.IMAGE_SIZE,
FLAGS.IMAGE_SIZE, 1])
network = tflearn.reshape(network, [-1, FLAGS.IMAGE_SIZE, FLAGS.IMAGE_SIZE, 1])

1. why 5-d tensor in the shape?

2. how can u reshape what looks a 5 -d tensor to 3 -d ?
what about batch size ?
suppose you have a batch of 10 of 32 by 32 pics with 1 channel for gray levels??
how can they be reshaped to 32x32x1?

3. and here
network = tflearn.reshape(network, [-1, sequence_length,
                                    int((FLAGS.IMAGE_SIZE / 2 ** 3) *
(FLAGS.IMAGE_SIZE / 2 ** 3) * 128)])

looks like recreating it.

4. is batch size= sequence_length

sorry about all  the questions.

joseph

**Comment by SadeghMSalehi** [comment]
Hey Joseph,

In @amirbar 's code, at the first line, you need to feed all of your images in one sequence to the network. But, in CNN part, you want to apply one specific CNN to all images and then use the output of them in your LSTM part. in this case, you need to behave with your images in one sequence as a batch input. that's why amir useed reshape in the second line.

**Comment by Hatinennshiro** [comment]
hello, 
How to read pictures into [batch_size, sequence_length, height, width, depth]? @amirbar

**Comment by amirbar** [comment]
@Hatinennshiro - say every image is of size `(32,32,3)` then you have a an array of shape `(100,32,32,3)`.

now you can just form a batch:
`frames_batch = [frames[i:i+24] for i in range(76)]`
it is now of shape ` (76, 24, 32, 32, 3)`. now you can start feeding mini batches of it to your network.

**Comment by shayan09** [comment]
Hey! How can you use this for lip reading? Need to classify a sequence of frames for each word.

**Comment by despoisj** [comment]
I think you can use the very same kind of model, only focusing on the mouth
instead of the eye. You can take a look at specific models for this task:
https://arxiv.org/pdf/1703.04105.pdf

Good luck!

2018-02-03 12:05 GMT+01:00 Shayan Sadar <notifications@github.com>:

**Comment by siyazingca** [comment]
@despoisj , I would like to know how to connect my trained CNN to LSTM . the final goal is to check whether the person is awake or sleeping by monitoring the eyes. I have images of closed and open eyes that I have trained my CNN on now i want to make a prediction using the LSTM
