### ISSUE TITLE
How to save model and retrain it?

### ISSUE THREAD

**Issue by lfwin** [tflearn/tflearn#39]
Hi,
Is there some APIs to be used to save model and restore it for retraining?

**Comment by aymericdamien** [comment]
You can follow this example:
https://github.com/tflearn/tflearn/blob/master/examples/basics/weights_persistence.py

It is very easy, just call save() and load() methods of `DNN` class

**Comment by Niko2756** [comment]
When trying to use the load function in TF learn I get this error:

> NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model_us_cities
> 	 [[Node: save_1/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2/tensor_names, save_1/RestoreV2/shape_and_slices)]]


I've tried several other different ways of referring to the save files including the checkpoint, the meta, and the index.


I believe the load function in TFlearn does not work, regardless of how you refer to the saved weights or checkpoints TFlearn will repeatedly be on able to recognize the saved file.

If anyone can help out with this I would truly appreciate it, as this issue is holding up an experiment I am conducting.

If there's any more information that you need I will be more than happy to provide that just ask.


I have used the example from above, https://github.com/tflearn/tflearn/blob/master/examples/basics/weights_persistence.py
but still the same error persists.

**Comment by dorwalprateek** [comment]
I was able to save and load model using the method mentioned in that link.

# Manually save model
model.save("model.tfl")

# Load a model
model.load("model.tfl")

**Comment by Noahyt** [comment]
I am also encountering the same(?) problem as @Niko2756 of not being able to use model.load

The error I get is: 

NotFoundError (see above for traceback): ... /8_10/model.tfl.data-00000-of-00001

I am training my network on another computer but want to load the trained network on my local machine for testing.  

In my training script I have included both checkpoint saves and a final "model.save".  

The checkpoint saves generate pairs of files, for example 
`model.tfl.ckpt-375` and `model.tfl.ckpt-375.meta` are a representative checkpoint files. 

The final model.load() in the training script generates two other files:

1.  model.tfl
2. model.tfl.meta

However when I use model.load() and model.save() on my local computer it creates 3 files: 

1.  model.tfl.data-00000-of-00001
2. model.tfl.meta
3. model.tfl.index

Is it possible that the training computer is using an outdated version of tflearn or tensorflow?  

Can i still load a model from any set of (two?) files created on the training computer?

**Comment by willduan** [comment]
@Noahyt I meet the same error that cannot load model, so have you solved it?

**Comment by Noahyt** [comment]
@willduan I have found that I can load as long as I load only weights:

`model.load(PATH, weights_only=True)`

**Comment by bhavikajalli** [comment]
I have a similar problem. I tried to load the model after saving it. It says model not defined.
I then tried model = tflearn.DNN(network, tensorboard_verbose=2)
It then says network is not defined. How do I define the network again?

**Comment by samshipengs** [comment]
@bhavikajalli  ```network = ...

model = DNN(network)
model.load('./model.tflearn')
model.predict(X)```

Change 'model.tflearn' to './model.tflearn' worked for me.

**Comment by SaumilShah66** [comment]
@Noahyt Did you get the answer, how model.load() can be used across multiple machines?

I trained my model on cloud and model.load() work directly on that machine. But how can I use that .meta, .index and .data files to run that tflearn model on my local machine?

**Comment by Noahyt** [comment]
@SaumilShah66 I found that my error was initially due to a difference in tensorflow and tflearn version between my cloud and desktop instances.  After making sure those are the same and using the code outlined by @samshipengs everything should work (also, I found I had to use model.load(PATH, weights_only=True)) as I mentioned in a previous comment.  

If this does not work, what is your error?

**Comment by SaumilShah66** [comment]
@Noahyt  Thank you very much... Actually tflearn and tensorflow weren't updated in my local machines.

**Comment by Isabella-China** [comment]
how to reload the network  and I have 3 files ? Would U like to give me a complete example? @Noahyt 
1、model.tfl.data-00000-of-00001
2、model.tfl.meta
3、model.tfl.index

**Comment by ChanheeJang** [comment]
@Isabella-China  
just pass the path+filename to model.load()  instead of pretrained model.
ex) 
if you have following files generated in C:/myModel/
1、model.tfl.data-00000-of-00001
2、model.tfl.meta
3、model.tfl.index
==> model.load(C:/myModel/model.tfl)

**Comment by Red-Night-Aria** [comment]
@ChanheeJang 
Thanks u~It works！

**Comment by LeonMLh** [comment]
Does anyone encounter the 'Resource exhausted' during loading the model?
It seems like that the layer sizes are too large. 
However, I cannot change my model for some reasons.
Do we have any other method, which takes less memory, to restore the model?

**Comment by SepehrV** [comment]
Is there any way to create a tflearn DNN class from the .meta file that is stored alongside the model weights?

**Comment by Noahyt** [comment]
@SepehrV  I believe this is implemented in TensorFlow but not in Tflearn.  
see: http://cv-tricks.com/tensorflow-tutorial/save-restore-tensorflow-models-quick-complete-tutorial/

you may be able to use this in tflearn, I am not sure.

**Comment by SepehrV** [comment]
Thanks, @Noahyt. I ended up doing something similar. But I also had to freeze the model (or delete optimization tensors) before saving otherwise there will be some conflict when tf tries to restore a tflearn saved model. 

I think it is kinda inconvenient to not be able to restore a tflean model directly to a DNN from just meta and weights. Maybe it should be added as a feature.

**Comment by mbertalan** [comment]
Hey @samshipengs ! Thanks for your reply. I think is very useful, but I am still a bit confused with tflearn model.load. Can the function load the meta graph or we have to do it manually ? Or do I have to use tensorflow to load the meta graph first ?  

You wrote:
"network = ...
model = DNN(network)
model.load('./model.tflearn')
model.predict(X)"

**Comment by AniketDhar** [comment]
I still get the error even after adding file path. I tried both absolute and relative file paths but doesn't work for me. Any suggestions?

**Comment by panuganti** [comment]
@Noahyt thanks for the 'weights_only=True'. It works with that. But, any idea, why is it designed that way ?

**Comment by jurner** [comment]
I've got the same problem. Loading a model is not possible. I always get a NotFoundError even if I use absolute paths and 'weights_only=True'. I updated tensorflow and tflearn but it still does not work. Any suggestions?



    if not trained_model:
        model = neural_network_model(input_size = len(x[0]), nr_classes=len(y[0]))
    else:
        model = neural_network_model(input_size = len(x[0]), nr_classes=len(y[0]))
        model.load('../models/'+MODEL_NAME)


    model.fit({'input': x}, {'targets': y}, n_epoch=1, validation_set=({'input': test_x}, {'targets': test_y}),
              snapshot_step=500,  show_metric=True, run_id=MODEL_NAME)

    model.save('../models/'+MODEL_NAME)`
The model is correctly saved, the files are there, but when I try loading it can't be found. Also the input size and the nr of classes does not change.
