### ISSUE TITLE
autoformat_kernel_3d in utils.py

### ISSUE THREAD

**Issue by iwyoo** [tflearn/tflearn#390]
Hi, guys.
I found a problem in `autoformat_kernel_3d` in `utils.py`.

```
def autoformat_kernel_3d(kernel):
    if isinstance(kernel, int):
        return [1, 1, kernel, kernel, kernel]
    elif isinstance(kernel, (tuple, list)):
        if len(kernel) == 3:
            return [1, 1, kernel[0], kernel[1], kernel[2]]
        elif len(kernel) == 5:
            assert kernel[0] == kernel[1] == 1, "Must have kernel_size[0] = kernel_size[1] = 1"
            return [kernel[0], kernel[1], kernel[2], kernel[3], kernel[4]]
        else:
            raise Exception("kernel length error: " + str(len(kernel))
                            + ", only a length of 3 or 5 is supported.")
    else:
        raise Exception("kernel format error: " + str(type(kernel)))
```

The original TensorFlow requires 3d-kernel with \[1, d, h, w, 1\] shape for max_pool_3d.
However, in TFlearn, it must be \[1, 1, d, h, w\] (if not, TFlearn throws assertion error) and it doesn't work in TensorFlow part.
(Also in document, recommended kernel_size is in wrong format.
`kernel_size: 'intorlist of int'. Pooling kernel size.Must have kernel_size[0] = kernel_size[1] = 1`)

Please check it.

**Comment by tgallice** [comment]
@iwyoo you right, here the related issue on TF which fix the incorrect documentation https://github.com/tensorflow/tensorflow/issues/2573
