### ISSUE TITLE
ImportError: cannot import name tensor_array_ops

### ISSUE THREAD

**Issue by reedlaw** [tflearn/tflearn#4]
This is with `tensorflow-0.7.1-cp27-none-linux_x86_64.whl` installed on Arch Linux. `tensorflow` itself works fine.

```
reed@4k ~ % python2
Python 2.7.11 (default, Mar 31 2016, 06:18:34) 
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tflearn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/tflearn/__init__.py", line 44, in <module>
    from . import layers
  File "/usr/lib/python2.7/site-packages/tflearn/layers/__init__.py", line 8, in <module>
    from .recurrent import lstm, gru, simple_rnn, bidirectional_rnn, dynamic_rnn, RNNCell, BasicLSTMCell, GRUCell, BasicRNNCell
  File "/usr/lib/python2.7/site-packages/tflearn/layers/recurrent.py", line 14, in <module>
    from tensorflow.python.ops import tensor_array_ops
ImportError: cannot import name tensor_array_ops
```

**Comment by aymericdamien** [comment]
It seems your tensorflow package doesn't have 'tensor_array_ops'.
Can you run:
```
import tensorflow.python.ops.tensor_array_ops
```
And see if it is working or not.

If it is not working, it is likely tensorflow has some issues or is too old. So, maybe you can try to reinstall it.
You can follow 'Upgade TensorFlow' procedure: http://tflearn.org/installation/#upgrade-tensorflow

**Comment by fayimora** [comment]
Had this issue and I was able to resolve it by uninstalling and re-installing tensorflow(and perhaps tflearn). The link @aymericdamien provides above has the instructions on how to do this.

**Comment by yotam180** [comment]
I'm experiencing the same problem, and reinstalling/upgrading TensorFlow did not work.
Ubuntu 14.04 with TensorFlow CPU only.

Did you find any other solutions to that problems?

Thanks.
