### ISSUE TITLE
multigpu and scopes

### ISSUE THREAD

**Issue by MInner** [tflearn/tflearn#402]
Hi,

I'm using `contrib.layers` (which is basically `tflean.layers`, right?) in multigpu setting (multiple "towers" in separate name scopes) and that leads to scope errors; using ordinary `tf.get_variable(..)` works just fine, though.

tensorflow 0.10.0
cuda 7.5

basic fully connected network to classify mnist: 
```
def build_fc_dnn():
    X = tf.placeholder(tf.float32, [None, 784])
    y = tf.placeholder(tf.float32, [None, 10])

    depth = 5
    
    last_layer = X
    argkw = dict(num_outputs=20, activation_fn=tf.nn.relu)
    for _ in range(depth):
        last_layer = tf.contrib.layers.fully_connected(last_layer, **argkw)
    logits = tf.contrib.layers.fully_connected(last_layer, num_outputs=10)
    
    loss = tf.nn.softmax_cross_entropy_with_logits(logits, y)
    y_train_eq_pred = tf.equal(tf.argmax(y,1), tf.argmax(logits,1))
    acc = tf.reduce_mean(tf.cast(y_train_eq_pred, tf.float32))
    
    return X, y, loss, acc
```

and the code that builds graph (analogues to cifar multigpu example):

        ...
        tower_vars = []
        for tower_id in range(len(device_id_list)):
            with tf.device('/gpu:%d' % tower_id):
                with tf.name_scope('tower_%d' % tower_id) as scope:
                    X, y, loss, acc = build_model()
                    tower_vars.append([gd.compute_gradients(loss), loss, acc, (X, y)])
                    tf.get_variable_scope().reuse_variables()

        tower_grads, tower_loss, tower_acc, xy_pairs = zip(*tower_vars)
        train_op = gd.apply_gradients(average_gradients(tower_grads))
        loss = tf.reduce_mean(tower_loss)
        acc = tf.reduce_mean(tower_acc)
        init_op = tf.initialize_all_variables()

if I do that, I get an error: `ValueError: Variable fully_connected_6/weights does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?`

[docs](http://tflearn.org/getting_started/#scopes-weights-sharing) suggest building multigpu code as follows:

```
with tf.device('/gpu:0'):
    # Force all Variables to reside on the CPU.
    with tf.arg_ops([tflearn.variables.variable], device='/cpu:0'):
        model1 = my_model(placeholder_X)
# Reuse Variables for the next model
tf.get_variable_scope().reuse_variables()
with tf.device('/gpu:1'):
    with tf.arg_ops([tflearn.variables.variable], device='/cpu:0'):
        model2 = my_model(placeholder_X)
```
but that is probably somewhat outdated, because `tf.arg_ops` is not there anymore; the closest thing I could find is the following:

        arg_scope = tf.contrib.framework.arg_scope
        create_var_op = tf.contrib.framework.python.ops.variables.variable
        ...
        tower_vars = []
        for tower_id in range(len(device_id_list)):
            with tf.device('/gpu:%d' % tower_id):
                with tf.name_scope('tower_%d' % tower_id) as scope:
                    variables_on_cpu = arg_scope([create_var_op], device='/cpu:0')
                    with variables_on_cpu:
                         X, y, loss, acc = build_model()
                         tower_vars.append([gd.compute_gradients(loss), loss, acc, (X, y)])
                         tf.get_variable_scope().reuse_variables()

        tower_grads, tower_loss, tower_acc, xy_pairs = zip(*tower_vars)
        train_op = gd.apply_gradients(average_gradients(tower_grads))
        loss = tf.reduce_mean(tower_loss)
        acc = tf.reduce_mean(tower_acc)
        init_op = tf.initialize_all_variables()

but it also does not help (same error).

an [issue](https://github.com/tensorflow/serving/issues/136) with similar error message
another [one](https://github.com/tensorflow/tensorflow/issues/1325) (mentions tflearn)
full [code](https://gist.github.com/MInner/58fa334574138f1ce1359258f27af19a) that reproduces error

**Comment by aymericdamien** [comment]
There is a typo, you should use `tf.arg_scope` instead of `tf.arg_ops`.

**Comment by MInner** [comment]
@aymericdamien , I'm an idiot, I forgot to set unique `scope=` values, sorry, closing this issue.

**Comment by ecsark** [comment]
@MInner Could you show what you modified to solve this? Thanks!

**Comment by ashishkr23** [comment]
@MInner  Hi , i am dealing with the exact same issue, was this resolved ? Appreciate any help.

**Comment by MInner** [comment]
@ashishkr23 sure, when you call `tf.contrib.layers.fully_connected()`, you can specify `scope=` argument (string, ~ `name=` in tensorflow) - if you do scopes and want to reuse one of your `tf.contrib.layers`, you should specify it, so that tf could know how to set the "alignment" between "reused" parts.

https://www.tensorflow.org/versions/r0.11/api_docs/python/contrib.layers.html#fully_connected
