### ISSUE TITLE
openai gym render and tflearn, can't load any more object with static TLS

### ISSUE THREAD

**Issue by gabrieledcjr** [tflearn/tflearn#403]
when using tflearn and rendering game in openAI gym, it gives me an error,

Unexpected error loading library libGL.so.1: dlopen: cannot load any more object with static TLS

**Comment by aymericdamien** [comment]
You may try to reinstall `nvidia-libgl` package.

**Comment by gabrieledcjr** [comment]
don't have nvidia. just running it on CPU.

**Comment by lizeyu4444** [comment]
@gabrieledcjr is it solved? I met same question, and I am afraid that its out of memory.

**Comment by farscape2012** [comment]
I met the same issue. 

Unexpected error loading library libGL.so.1: dlopen: cannot load any more object with static TLS
Traceback (most recent call last):
  File "random_agent_3.py", line 52, in <module>
    observation = env.reset()
.....

OSError: dlopen: cannot load any more object with static TLS

**Comment by gabrieledcjr** [comment]
@lizeyu4444 it is not solved. Still looking for a solution on this.

**Comment by gabrieledcjr** [comment]
I found a solution by upgrading to Ubuntu 16.04. I posted this question to openai gym issues and they mention about the version of glibc that is used in Ubuntu 14 that has a small limit on the number of shared libraries with TLS [https://github.com/openai/gym/issues/396#issuecomment-257028923]. Before upgrading, I tried looking for ways to upgrade glibc but couldn't find anything unless if you upgrade it using the source files. I hope this helps.

**Comment by TolgaOk** [comment]
Hi there, i am using Ubuntu 14.04 and i get the same issue when ever i use tflearn and open ai gym's box2D environments together. For example:

import tflearn
import gym
gym.make("BipedalWalker-v2")

But when i change the order of these two lines like below, i don't get any error.

import gym
gym.make("BipedalWalker-v2")
import tflearn
