### ISSUE TITLE
Why do labels need to be ints?

### ISSUE THREAD

**Issue by l-hendriks** [tflearn/tflearn#406]
I have a dataset with 2 sets of labels: the first set of labels is categorical, but the values are numbers. The only possible values are `1.05` and `0.95`.

When I want to load the data (as csv, build hdf5, anything), I get the error 

`ValueError: invalid literal for int() with base 10: '1.10'`

However, they are categorical. Why is this important? They are actually cast as an int in for example data_utils.py:

`labels.append(int(l[1]))`

The second set of labels are not categorical but continuous between `0` and `1`. Creating a hdf5 dataset still doesn't work, because I get the same error. However, these labels are never ints...

Is it possible to have non-integer labels when creating a hdf5 dataset?

**Comment by aymericdamien** [comment]
Yes, it is not really necessary because they are cast. Can you send the error line?

**Comment by l-hendriks** [comment]
This is the full error:

```
Traceback (most recent call last):
  File "create_hdf5.py", line 6, in <module>
    build_hdf5_image_dataset('labels_gamma_small.dat', grayscale=True, image_shape=(60, 60), mode='file', output_path='data_gamma.h5', categorical_labels=True, normalize=True)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/data_utils.py", line 382, in build_hdf5_image_dataset
    labels.append(int(l[1]))
ValueError: invalid literal for int() with base 10: '1.10'
```


The line in the file would be

`/some/image.jpg 1.10`

**Comment by newOnahtaN** [comment]
@l-hendriks Did this ever get resolved?

**Comment by l-hendriks** [comment]
I don't think so. However I circumvented the problem to create hdf5 datasets which have ints as lables and keep track somewhere what int represents what.

**Comment by newOnahtaN** [comment]
I ended up doing the same solution - this seems like a very fixable problem however!
