### ISSUE TITLE
Shape issue with data

### ISSUE THREAD

**Issue by ankuj** [tflearn/tflearn#410]
Hello,

In my dataset, I am given in the input is  a set of action sequences, each of which are executed with a different objective or goal in mind (example: if a person wants to transport an object from one place to another, they perform a sequence of actions which consists of 'initial state->lift(object, person)->load(object, car)-> lift(..) -> drive(...)-> load(...)->drop(...)->goal'). This sequence of actions constitutes a single trace for me. Each action can, however be applied in specific world states (i.e. the action 'load' can only execute when there is a car to carry it in; i.e. predicate 'isCar' is true; these predicates are otherwise called preconditions) and on execution result in a different world state (e.g. after the action 'load', the box has been loaded into the car; i.e. predicate 'boxInCar' is true; these predicates are otherwise called effects). My task here is given these traces of action sequences, to 'learn'  the underlying action model i.e. blueprint of preconditions and effects for each action. Example of an action model for action 'load' can be:

preconditions: isCar(), isDriver(),isCarRunning().. etc.
effects: onCar(), carMoving().. etc.

In tensorflow, assuming that I have 4 actions to learn, I am representing each action of each trace in the form of a sequence of 16 dimensional input vector representing each action. Here I construct a superset of all possible action models (i.e. all possible permutations of predicates representing preconditions and effects), and wish to test them one by one to see which is more accurate.

Input Vector (assuming action1 is executed):
[action1 (1)
action2 (0)
action3 (0)
action4 (0)
(preconditions of action1) (1)
(effects of action1) (1)

.
(preconditions of action2) (0)
(effects of action2) (0)
.
(preconditions of action3) (0)
(effects of action3) (0)
.
(preconditions of action4) (0)
(effects of action4) (0)
.
]

and trying to predict the next action in the sequence in a one-hot encoded fashion:
Output Vector:
[first_action (0)
secondAction (1)
ThirdAction (0)
ForthAction (1)]

 This vector is 16 dimensional (4 rows for each of the actions, rest 12 for each of the preconditions and effects of all (3 per action, thus 12 in all) ). Each time an action is executed, the vector position corresponding to the action name is set to 1, and the positions corresponding to its preconditions and effects is set to 1 as well. The rest are kept at 0.

My code is as follows:

`   #code to add padded data

    train_input, train_output, maxTraceLength = reader_pddlCodeIssueRep.loadData()

    #80% of examples in training, 20% for testing
    train_input, test_input = train_input[:int(len(train_input)*0.8)], train_input[int(len(train_input)*0.8):]
    train_output, test_output = train_output[:int(len(train_output)*0.8)], train_output[int(len(train_output)*0.8):]`

    # Network building
    net = tflearn.input_data([None, 1, 16])
    net = tflearn.lstm(net, 128, dropout=0.8)
    net = tflearn.fully_connected(net, 4, activation='softmax')
    net = tflearn.regression(net, optimizer='adam', learning_rate=0.001,
                             loss='categorical_crossentropy')
    # Training
    model = tflearn.DNN(net, tensorboard_verbose=0)
    model.fit(train_input, train_output, validation_set=(test_input, test_output), show_metric=True,
              batch_size=maxTraceLength)

Also attached here:
[codeIssueRep.txt](https://github.com/tflearn/tflearn/files/544475/codeIssueRep.txt)

Issue: I seem to be falling prey to a shape issue which says `ValueError: Cannot feed value of shape (13, 16) for Tensor 'InputData/X:0', which has shape '(?, 1, 16)'`. 

I am a relative newbie at tensorflow and tflearn and don't have too much of ML experience behind me. I have read similar issues in the tflearn issue page (thanks to @aymericdamien for his answers, they have been very useful in clearing doubts that I have had )and ones on TensorFlow too, and feel that I am representing it correctly but my data might not be in the correct format somehow.

Lastly, sorry for the long post, I just tried to clarify my problem in general to give better context :)
Would be very obliged if someone could help!

**Comment by aymericdamien** [comment]
It seems your input_data tensor has a wrong shape, you can try:
```
net = tflearn.input_data([None, 16])
```

**Comment by ankuj** [comment]
@aymericdamien thanks for the answer, however it now throws me an error that my input dimension should be atleast 3:

`   assert ndim >= 3, "Input dim should be at least 3."
AssertionError: Input dim should be at least 3.
`
appreciate the help!

**Comment by OlivierData** [comment]
[lstm](http://tflearn.org/layers/recurrent/#lstm) needs a 3D tensor. So `net = tflearn.input_data([None, 1, 16])` is correct in your example but you need to reshape 'train_input' before feeding your network with it. For example, with a numpy array : `train_input = train_input.reshape((-1, 1, 16))`

**Comment by aymericdamien** [comment]
That is right! Haven't notice it was a lstm layer. Please follow @OlivierData solution, it should be working.

**Comment by ankuj** [comment]
@aymericdamien @OlivierData thanks for your responses! However upon implementing the shape change that you guys suggested the code seems to run fine till a certain point (training step 79) after which it throws the same error:
`Training Step: 79  | total loss: [1m[32m0.51636[0m[0m
[2K| Adam | epoch: 001 | loss: 0.51636 - acc: 0.1779 -- iter: 1027/1040
ValueError: Cannot feed value of shape (13, 16) for Tensor InputData/X:0, which has shape (?, 1, 16)`

The code after the modification:

    ` //Network building
    net = tflearn.input_data([None, 1, 16])
    train_input = numpy.reshape(train_input, (-1, 1, 16))
    net = tflearn.lstm(net, 128, dropout=0.8)
    net = tflearn.fully_connected(net, 4, activation='softmax')
    net = tflearn.regression(net, optimizer='adam', learning_rate=0.001,
                             loss='categorical_crossentropy')
    //Training
    model = tflearn.DNN(net, tensorboard_verbose=0)
    //maxTraceLength=13, i.e. each of the traces is padded to an equal length of 13 actions each
    model.fit(train_input, train_output, validation_set=(test_input, test_output), show_metric=True,
              batch_size=maxTraceLength`
Any ideas what could be messing it up?!

**Comment by OlivierData** [comment]
You must do a reshape operation for 'test_input' too.

**Comment by ankuj** [comment]
Thank you @OlivierData  and @aymericdamien for that, its working now! :)

**Comment by r1239105** [comment]
sorry,could anyone help solving my quastion?

this is my code:
------------------------------------------------------------------------------------------------------
create a data structure to hold user context

context = {}

ERROR_THRESHOLD = 0.25
def classify(sentence):
# generate probabilities from the model
results = model.predict([bow(sentence, words)])[0]
# filter out predictions below a threshold
results = [[i,r] for i,r in enumerate(results) if r>ERROR_THRESHOLD]
# sort by strength of probability
results.sort(key=lambda x: x[1], reverse=True)
return_list = []
for r in results:
return_list.append((classes[r[0]], r[1]))
# return tuple of intent and probability
return return_list

def response(sentence, userID='123', show_details=False):
results = classify(sentence)
# if we have a classification then find the matching intent tag
if results:
# loop as long as there are matches to process
while results:
for i in intents['intents']:
# find a tag matching the first result
if i['tag'] == results[0][0]:
# set context for this intent if necessary
if 'context_set' in i:
if show_details: print ('context:', i['context_set'])
context[userID] = i['context_set']

                # check if this intent is contextual and applies to this user's conversation
                if not 'context_filter' in i or \
                    (userID in context and 'context_filter' in i and i['context_filter'] == context[userID]):
                    if show_details: 
                        print ('tag:', i['tag'])
                    # a random response from the intent
                    return(random.choice(i['responses']))

        results.pop(0)
----------------------------------------------------------------------------------------------------
classify('is your shop open today?')

-----------------------------------------------------------------------------------------------------

but i got the error:

ValueError Traceback (most recent call last)
in ()
----> 1 classify(u'is your shop open today?')

in classify(sentence)
5 def classify(sentence):
6 # generate probabilities from the model
----> 7 results = model.predict([bow(sentence, words)])[0]
8 # filter out predictions below a threshold
9 results = [[i,r] for i,r in enumerate(results) if r>ERROR_THRESHOLD]

/Library/Python/2.7/site-packages/tflearn/models/dnn.pyc in predict(self, X)
255 """
256 feed_dict = feed_dict_builder(X, None, self.inputs, None)
--> 257 return self.predictor.predict(feed_dict)
258
259 def predict_label(self, X):

/Library/Python/2.7/site-packages/tflearn/helpers/evaluator.pyc in predict(self, feed_dict)
67 prediction = []
68 if len(self.tensors) == 1:
---> 69 return self.session.run(self.tensors[0], feed_dict=feed_dict)
70 else:
71 for output in self.tensors:

/Library/Python/2.7/site-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
776 try:
777 result = self._run(None, fetches, feed_dict, options_ptr,
--> 778 run_metadata_ptr)
779 if run_metadata:
780 proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/Library/Python/2.7/site-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
959 'Cannot feed value of shape %r for Tensor %r, '
960 'which has shape %r'
--> 961 % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
962 if not self.graph.is_feedable(subfeed_t):
963 raise ValueError('Tensor %s may not be fed.' % subfeed_t)

ValueError: Cannot feed value of shape (48,) for Tensor u'InputData/X:0', which has shape '(?, 48)'

please could someone tell me how to fix it?
