### ISSUE TITLE
How to set global seed

### ISSUE THREAD

**Issue by CCXD** [tflearn/tflearn#419]
Setting global seed using init_graph or tf.set_random_seed() seems to have no effect. Tests are totally not reproducible.

**Comment by aymericdamien** [comment]
You can set a seed using: http://tflearn.org/config/#init_graph

**Comment by emilwallner** [comment]
Having the same problem, posted a test here: https://github.com/tflearn/tflearn/issues/757

Is it a bug or am I using it the wrong way?

**Comment by SaadSen** [comment]
I can't reproduce the same results with tflearn.init_graph :(
