### ISSUE TITLE
Improper initialization of bilinear filter for Upscore

### ISSUE THREAD

**Issue by bcarpenter-pub** [tflearn/tflearn#424]
If I am correct, the Deconv/Upscore as described in https://arxiv.org/pdf/1409.1556.pdf wants each filter to be a bilinear filter.

line 472 of https://github.com/tflearn/tflearn/blob/master/tflearn/layers/conv.py properly performs the creation of the filter for a given size.  However id does not properly place it in the initializtion array 'weights'

it does:

```
            for i in range(f_shape[2]):
                weights[:, :, i, i] = bilinear
```

f_shape[2] and f_shape[3] may not be the same size and as a result, the weights are improperly initialized.

I propose:

```
            for i in range(f_shape[2]):
                for j in range(f_shape[3]):
                    weights[:, :, i, j] = bilinear

```

If this makes sense, I will make a pull request for it.

**Comment by bcarpenter-pub** [comment]
I replicated the code for the similar BVLC filter and have confirmed my proposed method is the same.

https://github.com/tnarihi/caffe/commit/4f249a00a29432e0bb6723087ec64187e1506f0f

```
filt = np.zeros([2,1,8,8])
filt2 = np.reshape(filt,[-1])
width,height=(8,8)
f = math.ceil(width / 2.);
c = (2 * f - 1 - f % 2) / (2. * f);
for i in range(len(filt2)):
    x = i %width
    y = (i / width)% height;
    filt2[i] = (1 - abs(x / f - c)) * (1 - abs(y / f - c));
filt3=np.reshape(filt2,[2,1,8,8])
filt3[0][0].shape
```

**Comment by aymericdamien** [comment]
Hi, it indeed make sense, current implementation is only viable if f_shape[2] = f_shape[3] which do not works in every cases. Please send a PR, I will be happy to review and merge it! :)

**Comment by bcarpenter-pub** [comment]
actually, i realize I am wrong.  The current implementation is correct as it is being used with the tensorflow conv2d_transpose which does a convolution across all channels.  The current creation of the filiter accounts for this as to only enable per channel upsampling.  Good job all! :D
