### ISSUE TITLE
mnist.load_data(one_hot=True) ValueError

### ISSUE THREAD

**Issue by migueldsw** [tflearn/tflearn#429]
I'm facing:
`ValueError: too many values to unpack` 

when run
`import tflearn.datasets.mnist as mnist`
`X, Y = mnist.load_data(one_hot=True)`

**Comment by aymericdamien** [comment]
It should be:
```
X, Y, testX, testY = mnist.load_data(one_hot=True)
```

**Comment by migueldsw** [comment]
Thanks! Just realized!
Btw, what about a pattern in all <dataset>.load_data() return? 
Could this be usefull and avoid misuses?
