### ISSUE TITLE
conv3D_transpose Layer (Feature Request)

### ISSUE THREAD

**Issue by dhelma** [tflearn/tflearn#432]
Helllo,

Newer versions of TensorFlow implement a transpose for 3D convolution like older ones have for 2D operations.  #@142 implements the other 3D operations, and I was hoping this one could get added too!

https://www.tensorflow.org/versions/r0.11/api_docs/python/nn.html#conv3d_transpose

**Comment by Marigold** [comment]
I'm looking into it too, seems like the implementation should be pretty straightforward.

A related question - I was comparing differences between `conv_2d` and `conv_3d` methods and it looks like `conv_3d` is basically a copy of `conv_2d` with just a few lines changed. I was thinking this could be perhaps DRYed up (by extracting common functionality into separate methods). What do you think @aymericdamien?

**Comment by burness** [comment]
@aymericdamien If it is ok, I would try to implements the conv_3d_transpose

**Comment by dhelma** [comment]
Thanks burness!
