### ISSUE TITLE
Is it possible to have multiple classes with build_hdf5_image_dataset?

### ISSUE THREAD

**Issue by PaulMulligan** [tflearn/tflearn#449]
Hi,

I've used tflearn for image analysis with mutually-exclusive classes and it has gone really well, but now I'm looking into doing an analysis with sigmoid instead of softmax, on images that can have multiple valid classes on them, instead of just one.
I'm using build_hdf5_image_dataset in file mode to prepare my data and I just wanted to ask if there is any way to specify multiple classes per image, with this or any other function?

Thanks very much for creating such a great project

**Comment by aymericdamien** [comment]
It doesn't support multi-label. But you can easily adapt the function here: https://github.com/tflearn/tflearn/blob/master/tflearn/data_utils.py#L382

**Comment by PaulMulligan** [comment]
Thanks, that looks straightforward enough. I will give it a shot
