### ISSUE TITLE
NLP examples broken?

### ISSUE THREAD

**Issue by fayimora** [tflearn/tflearn#47]
All the examples in the nlp folder are returning an error of the form:
`1524438 inputs feeded, but expected: 2`

Any idea why?

**Comment by aymericdamien** [comment]
What TensorFlow version are you using? Can you copy all error message?
I ran again the examples with TensorFlow 0.7.1 and didn't have any issue. I will try with TF v0.8 to see if it has any new issue.

**Comment by fayimora** [comment]
@aymericdamien i think I just needed to restart my ipython session. Everything looks fine now.
