### ISSUE TITLE
'module' object has no attribute 'scalar_summary'

### ISSUE THREAD

**Issue by ZejiaZheng** [tflearn/tflearn#510]
I just installed the most recent version of tensorflow and tflearn.
Tensorflow runs fine with its give examples and notebooks.
When using tflearn however I got the following error on summaries.py:
File "build/bdist.linux-x86_64/egg/tflearn/summaries.py", line 46, in get_summary
AttributeError: 'module' object has no attribute 'scalar_summary'

The exact output is attached blow:
`~/Documents/tflearn/tutorials/intro$ python quickstart.py 
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so.8.0 locally
Downloading Titanic dataset...
Succesfully downloaded titanic_dataset.csv 82865 bytes.
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:909] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 745
major: 5 minor: 0 memoryClockRate (GHz) 1.0325
pciBusID 0000:01:00.0
Total memory: 3.95GiB
Free memory: 3.71GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 745, pci bus id: 0000:01:00.0)
Traceback (most recent call last):
  File "quickstart.py", line 41, in <module>
    model = tflearn.DNN(net)
  File "build/bdist.linux-x86_64/egg/tflearn/models/dnn.py", line 63, in __init__
  File "build/bdist.linux-x86_64/egg/tflearn/helpers/trainer.py", line 121, in __init__
  File "build/bdist.linux-x86_64/egg/tflearn/helpers/trainer.py", line 651, in initialize_training_ops
  File "build/bdist.linux-x86_64/egg/tflearn/summaries.py", line 243, in add_loss_summaries
  File "build/bdist.linux-x86_64/egg/tflearn/summaries.py", line 46, in get_summary
AttributeError: 'module' object has no attribute 'scalar_summary'`

**Comment by awesomebytes** [comment]
I get the same. I have the latest Tensorflow with CUDA 8.0 and CuDNN 5.1. You can find a full guide of my installation for a 1070 GTX [here](https://github.com/awesomebytes/alienware15r3_ubuntu14) in case of doubts of what it is installed.

**Comment by aymericdamien** [comment]
TFLearn does not fully support TensorFlow 0.12 yet. But most of the error/warnings have been fix. Please update tflearn and that should be working, or downgrade to TF 0.11.
