### ISSUE TITLE
ValueError: Parent directory of test_dnn.tflearn doesn't exist, can't save.

### ISSUE THREAD

**Issue by HWiese1980** [tflearn/tflearn#524]
I'm trying to run the tests on a Windows 10 64bit system within a WinPython 3.5.2 based `virtualenv` specifically created for `tflearn`. Some of the tests fail with the following error message at the end of this issue. 

Currently checked out commit: 

	commit 334889b15ee80051b9fb97bf312fc52184c85f97
	Author: aymericdamien <aymeric.damien@gmail.com>
	Date:   Thu Dec 15 01:38:15 2016 +0000

	    fix batchnorm for TF 0.12

I've investigated this and it seems that the `head` part of the `split` full path of `test_dnn.tflearn` (in this test case) is empty. The string is empty. There is no parent path given. It seems to be all relative with just a file name and nothing more. Turning it into an absolute path manually by prefixing the file with the `cwd` (which I assume usually happens automatically anyway when giving relative paths) solves the problem.
 

    self = <tests.test_models.TestModels testMethod=test_dnn>

        def test_dnn(self):
        
            with tf.Graph().as_default():
                X = [3.3,4.4,5.5,6.71,6.93,4.168,9.779,6.182,7.59,2.167,7.042,10.791,5.313,7.997,5.654,9.27,3.1]
                Y = [1.7,2.76,2.09,3.19,1.694,1.573,3.366,2.596,2.53,1.221,2.827,3.465,1.65,2.904,2.42,2.94,1.3]
                input = tflearn.input_data(shape=[None])
                linear = tflearn.single_unit(input)
                regression = tflearn.regression(linear, optimizer='sgd', loss='mean_square',
                                                metric='R2', learning_rate=0.01)
                m = tflearn.DNN(regression)
                # Testing fit and predict
                m.fit(X, Y, n_epoch=1000, show_metric=True, snapshot_epoch=False)
                res = m.predict([3.2])[0]
                self.assertGreater(res, 1.3, "DNN test (linear regression) failed! with score: " + str(res) + " expected > 1.3")
                self.assertLess(res, 1.8, "DNN test (linear regression) failed! with score: " + str(res) + " expected < 1.8")
        
                # Testing save method
    >           m.save("test_dnn.tflearn")

    test_models.py:28: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
    ..\tflearn\models\dnn.py:242: in save
        self.trainer.save(model_file)
    ..\tflearn\helpers\trainer.py:367: in save
        self.saver.save(self.session, model_file, global_step=global_step)
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    self = <tensorflow.python.training.saver.Saver object at 0x000001176BFB3E10>
    sess = <tensorflow.python.client.session.Session object at 0x000001176BF96CF8>
    save_path = 'test_dnn.tflearn', global_step = None
    latest_filename = 'checkpoint', meta_graph_suffix = 'meta'
    write_meta_graph = True, write_state = True

        def save(self,
                 sess,
                 save_path,
                 global_step=None,
                 latest_filename=None,
                 meta_graph_suffix="meta",
                 write_meta_graph=True,
                 write_state=True):
          """Saves variables.
        
            This method runs the ops added by the constructor for saving variables.
            It requires a session in which the graph was launched.  The variables to
            save must also have been initialized.
        
            The method returns the path of the newly created checkpoint file.  This
            path can be passed directly to a call to `restore()`.
        
            Args:
              sess: A Session to use to save the variables.
              save_path: String.  Path to the checkpoint filename.  If the saver is
                `sharded`, this is the prefix of the sharded checkpoint filename.
              global_step: If provided the global step number is appended to
                `save_path` to create the checkpoint filename. The optional argument
                can be a `Tensor`, a `Tensor` name or an integer.
              latest_filename: Optional name for the protocol buffer file that will
                contains the list of most recent checkpoint filenames.  That file,
                kept in the same directory as the checkpoint files, is automatically
                managed by the saver to keep track of recent checkpoints.  Defaults to
                'checkpoint'.
              meta_graph_suffix: Suffix for `MetaGraphDef` file. Defaults to 'meta'.
              write_meta_graph: `Boolean` indicating whether or not to write the meta
                graph file.
              write_state: `Boolean` indicating whether or not to write the
                `CheckpointStateProto`.
        
            Returns:
              A string: path at which the variables were saved.  If the saver is
                sharded, this string ends with: '-?????-of-nnnnn' where 'nnnnn'
                is the number of shards created.
              If the saver is empty, returns None.
        
            Raises:
              TypeError: If `sess` is not a `Session`.
              ValueError: If `latest_filename` contains path components, or if it
                collides with `save_path`.
              RuntimeError: If save and restore ops weren't built.
            """
          if not self._is_built:
            raise RuntimeError(
                "`build()` should be called before save if defer_build==True")
          if latest_filename is None:
            latest_filename = "checkpoint"
          if self._write_version != saver_pb2.SaverDef.V2:
            logging.warning("*******************************************************")
            logging.warning("TensorFlow's V1 checkpoint format has been deprecated.")
            logging.warning("Consider switching to the more efficient V2 format:")
            logging.warning("   `tf.train.Saver(write_version=tf.train.SaverDef.V2)`")
            logging.warning("now on by default.")
            logging.warning("*******************************************************")
        
          if os.path.split(latest_filename)[0]:
            raise ValueError("'latest_filename' must not contain path components")
        
          if global_step is not None:
            if not isinstance(global_step, compat.integral_types):
              global_step = training_util.global_step(sess, global_step)
            checkpoint_file = "%s-%d" % (save_path, global_step)
            if self._pad_step_number:
              # Zero-pads the step numbers, so that they are sorted when listed.
              checkpoint_file = "%s-%s" % (save_path, "{:08d}".format(global_step))
          else:
            checkpoint_file = save_path
            if os.path.basename(
                save_path) == latest_filename and not self.saver_def.sharded:
              # Guard against collision between data file and checkpoint state file.
              raise ValueError(
                  "'latest_filename' collides with 'save_path': '%s' and '%s'" %
                  (latest_filename, save_path))
        
          if not gfile.IsDirectory(os.path.dirname(save_path)):
            raise ValueError(
    >           "Parent directory of {} doesn't exist, can't save.".format(save_path))
    E       ValueError: Parent directory of test_dnn.tflearn doesn't exist, can't save.

    ..\..\virtualenvs\tensorenv\lib\site-packages\tensorflow\python\training\saver.py:1314: ValueError

**Comment by aymericdamien** [comment]
I believe this is due to TF 0.12.0. You may downgrade to TF 0.11 rc2 while we are releasing a full patch to support TF 0.12.0.

**Comment by HWiese1980** [comment]
Well, I've tried downgrading... I think I'll rather wait for you to finish 0.12 support. Thanks! In the meantime a quick'n'dirty workaround is to check before the line

    if not gfile.IsDirectory...

whether `save_path` is merely a filename and if it is to turn it into an absolute path by means of 

    if not os.path.isabs(save_path):
        save_path = os.path.abspath(os.path.join(os.getcwd(), save_path))

or something like that.

**Comment by aymericdamien** [comment]
Thanks! I fixed it. I think most errors linked to TF 0.12 should be gone by now. You can update TFLearn and let me know if it is working :)

**Comment by HWiese1980** [comment]
It somehow broke other things... I've again tried running the tests and now I'm getting fails like this one: 

    self = <tests.test_models_loading_scope.TestModelsLoadingScope testMethod=test_dnn_loading_scope>

        def test_dnn_loading_scope(self):

            with tf.Graph().as_default():
                X = [3.3,4.4,5.5,6.71,6.93,4.168,9.779,6.182,7.59,2.167,7.042,10.791,5.313,7.997,5.654,9.27,3.1]
                Y = [1.7,2.76,2.09,3.19,1.694,1.573,3.366,2.596,2.53,1.221,2.827,3.465,1.65,2.904,2.42,2.94,1.3]
                input = tflearn.input_data(shape=[None])
                linear = tflearn.single_unit(input)
                regression = tflearn.regression(linear, optimizer='sgd', loss='mean_square',
                                                metric='R2', learning_rate=0.01)
                m = tflearn.DNN(regression)
                # Testing fit and predict
                m.fit(X, Y, n_epoch=1000, show_metric=True, snapshot_epoch=False)
                res = m.predict([3.2])[0]
                self.assertGreater(res, 1.3, "DNN test (linear regression) failed! with score: " + str(res) + " expected > 1.3")
                self.assertLess(res, 1.8, "DNN test (linear regression) failed! with score: " + str(res) + " expected < 1.8")

                # Testing save method
                m.save("test_dnn.tflearn")
    >           self.assertTrue(os.path.exists("test_dnn.tflearn"))
    E           AssertionError: False is not true

That looks like something with the path has gone awry.

**Comment by HWiese1980** [comment]
Alright, dug a little deeper into this and it seems not to be your respectively tflearn's fault, @aymericdamien. I have opened a corresponding issue in the tensorflow project. It seems to be some kind of *bug* in TF.

**Comment by Viscoo** [comment]
I found the gfile.Isdirectory method at the  version 1.2 of tensorflow doesn't support the Chinese directory, when I change the project directory at a full English word, the code works!
