### ISSUE TITLE
How to initializer the weights by using a tensor

### ISSUE THREAD

**Issue by zluo-miovision** [tflearn/tflearn#53]
self.Fea_In_C3 = tflearn.conv_2d(vgg.pool5, 256, 11,
                                         weights_init= tf.random_normal_initializer(stddev=0.0001),
                                         padding='valid',
                                         activation= 'relu',
                                         name='Fea_In_C3')

I want to initializer the weights by using a small deviation, and I use the code showing above, but it gives error.

  File "/home/zluo/PycharmProjects/DeepActiveContour/deepnet/Model.py", line 25, in build_model
    name='Fea_In_C3')
  File "/usr/local/lib/python2.7/dist-packages/tflearn/layers/conv.py", line 64, in conv_2d
    W_init = initializations.get(weights_init)()
TypeError: _initializer() takes at least 1 argument (0 given)

**Comment by aymericdamien** [comment]
I fixed the issue, for some reasons it wasn't accepting custom tf initializer. 
You can update TFLearn and it should work fine:
```
pip uninstall tflearn
pip install git+https://github.com/tflearn/tflearn.git
```
