### ISSUE TITLE
[Tutorial] I can't import 'titinic'

### ISSUE THREAD

**Issue by bonjune** [tflearn/tflearn#538]
I run the exact same code as [Quickstart](http://tflearn.org/tutorials/quickstart.html#source-code). But I got a problem here. 

`Traceback (most recent call last):
  File "F:\Programming\MachineLearning\tflearn-master\tutorials\intro\quickstart.py", line 7, in <module>
    from tflearn.datasets import titanic
ImportError: cannot import name 'titanic'`

I'm very new to python, so, if you can, tell me how to solve this problem in detail please. Thank you. :)

: if you need more information on this error, you can ask me here.

**Comment by aymericdamien** [comment]
Please use latest version of TFLearn:
```
pip install git+https://github.com/tflearn/tflearn.git
```

**Comment by robbiewu007** [comment]
titanic dataset come with v_0.2.2, but Pypi pip package is outdated v_0.2.1, does anybody maintain the Pypi pip package?

**Comment by robbiewu007** [comment]
(tensorflow_py35_builder) buildslave@byws19:~/happy_times/tflearn$ pip search tf                              learn
tflearn (0.2.2)  - Deep Learning Library featuring a higher-level API for
                   Tensorflow
(tensorflow_py35_builder) buildslave@byws19:~/happy_times/tflearn$ pip install t                              flearn
Collecting tflearn
Requirement already satisfied: Pillow in /home/buildslave/miniconda3/envs/tensor                              flow_py35_builder/lib/python3.5/site-packages (from tflearn)
Requirement already satisfied: numpy in /home/buildslave/miniconda3/envs/tensorf                              low_py35_builder/lib/python3.5/site-packages (from tflearn)
Requirement already satisfied: six in /home/buildslave/miniconda3/envs/tensorflo                              w_py35_builder/lib/python3.5/site-packages (from tflearn)
Requirement already satisfied: olefile in /home/buildslave/miniconda3/envs/tenso                              rflow_py35_builder/lib/python3.5/site-packages (from Pillow->tflearn)
Installing collected packages: tflearn
Successfully installed tflearn-0.2.1
(tensorflow_py35_builder) buildslave@byws19:~/happy_times/tflearn$ pip install t                              flearn=0.2.2
Invalid requirement: 'tflearn=0.2.2'
= is not a valid operator. Did you mean == ?
(tensorflow_py35_builder) buildslave@byws19:~/happy_times/tflearn$ pip install t                              flearn==0.2.2
Collecting tflearn==0.2.2
  Could not find a version that satisfies the requirement tflearn==0.2.2 (from v                              ersions: 0.2.1)
No matching distribution found for tflearn==0.2.2
