### ISSUE TITLE
[siamese network] Help & Error

### ISSUE THREAD

**Issue by mairasaboia** [tflearn/tflearn#544]
I'm trying to implement a Siamese network, where I have 2 image patches of Shape=(16,16) as input and the output is whether they are the same patch or not. The network should have 2 identical towers (that's why I'm using "reuse = True" for the second tower), and I merge them in the end. Bellow is the code that I managed to write but I cannot make it work. Furthermore, I couldn't find any example where model.fit(..) has two inputs or any example of siamese network. 

I'm getting the following error:
---------------------------------
Run id: Y4RXLR
Log directory: /tmp/tflearn_logs/
Traceback (most recent call last):
  File "siamese_net.py", line 260, in <module>
    model.fit([X1,X2], Y,n_epoch=5)
  File "/home/mss/anaconda3/lib/python3.5/site-packages/tflearn/models/dnn.py", line 214, in fit
    callbacks=callbacks)
  File "/home/mss/anaconda3/lib/python3.5/site-packages/tflearn/helpers/trainer.py", line 282, in fit
    self.summ_writer, self.coord)
  File "/home/mss/anaconda3/lib/python3.5/site-packages/tflearn/helpers/trainer.py", line 706, in initialize_fit
    self.n_train_samples = len(get_dict_first_element(feed_dict))
TypeError: object of type 'Tensor' has no len()
______________________________________________________________
The shape of my data:

X1: (205674, 16, 16)
X2: (205674, 16, 16)
Y: (205674, 2) 
__________________________________________________________________
```
def tower_network(reuse = False):
    network = tflearn.input_data(shape=(None,16,16,1))
    network = tflearn.conv_2d(network, 32,1, activation='relu',reuse=reuse, scope='conv1')
    ...
    network = tflearn.conv_2d(network, 128,1, activation='relu',reuse=reuse, scope='conv9')
    network = tflearn.max_pool_2d(network, 2, strides=2)
    network = tflearn.fully_connected(network, 512, activation='relu',reuse=reuse, scope='fc1')
    network = tflearn.dropout(network, 0.5)
    return network
    
def similarity_network( net1, net2):
    num_classes = 2
    network = tflearn.merge([net1,net2], mode='concat', axis=1, name='Merge') # merge net1 and net2 networks
    # fully connected layers
    network = tflearn.fully_connected(network, 2048, activation='relu')
    network = tflearn.dropout(network, 0.5)
    network = tflearn.fully_connected(network, 2048, activation='relu')
    network = tflearn.dropout(network, 0.5)
    
    # softmax layers
    network = tflearn.fully_connected(network, num_classes, activation='softmax')
    
    return network

if __name__ == "__main__":
    
    X1, _ = tflearn.data_utils.image_preloader (matchFilePath, image_shape=(16,16),
                                             mode='file', categorical_labels=True, normalize=False,
                                             grayscale=True, files_extension=None)
                                             
    X2, Y = tflearn.data_utils.image_preloader (mismatchFilePath, image_shape=(16,16),
                                             mode='file', categorical_labels=True, normalize=False,
                                             grayscale=True, files_extension=None)   
                
    X1 = tf.reshape(np.asarray(X1), [-1, 16, 16, 1]) 
    X2 = tf.reshape(np.asarray(X2), [-1, 16, 16, 1]) 
    # LABEL
    Y       = np.asarray(Y)
    
    #tower networks
    net1 = tower_network()
    net2 = tower_network(reuse=True)
    
    #similarity network
    network = similarity_network( net1, net2)
    #output layer
    #network = tflearn.regression(network, optimizer='sgd', loss='hinge_loss', learning_rate=0.02)
    network = tflearn.regression(network, optimizer='sgd', loss='categorical_crossentropy', learning_rate=0.02)

    #training
    model = tflearn.DNN(network)
    model.fit([X1,X2], Y,n_epoch=5)


```

Any help would be appreciated

**Comment by aymericdamien** [comment]
It is not working because model.fit() is expecting arrays and not tensor. You can use `np.reshape` instead of `tf.reshape`.

**Comment by mairasaboia** [comment]
It worked. Thank you!

**Comment by willduan** [comment]
@mairasaboia Hi, i want to know how is your siamese network is build, can you show more about the code? thanks!

**Comment by willduan** [comment]
@mairasaboia when i run your code ,it gots the follow errors:
```
Variable embed/W already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:
```
