### ISSUE TITLE
Ubuntu: recommend install libhdf5

### ISSUE THREAD

**Issue by mapmeld** [tflearn/tflearn#55]
I had trouble doing pip install on tflearn, until I found this recommendation for installing on Ubuntu:

```sudo apt-get install libhdf5-dev```

Please add to the installation instructions

Edit: on AWS GPU units, also:

```sudo apt-get install cuda-ld-conf-7-5```

**Comment by aymericdamien** [comment]
Thanks for the suggestion! There are indeed too few instructions about the installation process, I will add some more info and troubleshooting.
What was your ubuntu version?

**Comment by mapmeld** [comment]
Ubuntu 14.04 on AWS

**Comment by aymericdamien** [comment]
ok, thanks!
