### ISSUE TITLE
How to get intermediate output (before softmax)?

### ISSUE THREAD

**Issue by mairasaboia** [tflearn/tflearn#557]
I want to get the output of my network before the 'softmax' activation. So my approach was: I trained it using "softmax" activation and I tested it using 'linear' activation. Basically, I saved the model for a specific network and I loaded it for a slightly  different one. I want to know if this is correct or if there is another way to do what I want.

```
** SOFTMAX OUTPUT**  
...
network = tflearn.fully_connected(network, num_classes, activation='softmax', scope='soft1') 
model.save('model_name')

predicted values:
[[0.999675989151001, 0.0003240247315261513]]
[[3.6095348150411155e-06, 0.9999964237213135]]
```

```
**LINEAR OUTPUT**  
...
network = tflearn.fully_connected(network, num_classes, activation='linear', scope='soft1') 
model.load('model_name')

predicted values:
[[3.809051990509033, -4.225314140319824]]
[[-6.13877534866333, 6.393152713775635]]

```

**Comment by SnowWalkerJ** [comment]
I think this is right. After all, softmax([3.809051990509033, -4.225314140319824]) = [0.999675989151001, 0.0003240247315261513].
Also, you can implement it with always the linear activation. And when training it , add a softmax layer after the output layer.

**Comment by mairasaboia** [comment]
Thanks :D
