### ISSUE TITLE
Is it possible to visualize the Tensorboard of the example "lstm_generator_cityname.py"? 

### ISSUE THREAD

**Issue by slothkong** [tflearn/tflearn#558]
I've added the `tensorboard_verbose=3` as an argument to the sequence generator function, but I still am not able to visualize the model. I would greatly appreciate any help.

`30 - m = tflearn.SequenceGenerator(g, dictionary=char_idx,
 31-                             seq_maxlen=maxlen,
 32-                             clip_gradients=5.0,
 33-                             checkpoint_path='model_us_cities', tensorboard_verbose=3)
`

**Comment by C-J-Cundy** [comment]
Try adding `tensorboard_dir='/tmp/tflearn_logs'`, to the list of arguments to `SequenceGenerator`, and pointing tensorboard to that directory with the option `--logdir`
