### ISSUE TITLE
HDF5 library version mismatched error - TFLearn on AWS EC2 Ubuntu 14.04

### ISSUE THREAD

**Issue by DarylWM** [tflearn/tflearn#56]
I'm trying to install TFLearn on AWS EC2 Ubuntu 14.04. I have done `sudo apt-get install libhdf5-dev` but when I import tflearn...

Warning! ***HDF5 library version mismatched error***
Headers are 1.8.11, library is 1.8.15

**Comment by aymericdamien** [comment]
It seems there is a conflict between your system HDF5 library and the binaries of h5py package.
Maybe try to:
```
sudo apt-get remove libhdf5-dev
pip uninstall h5py

sudo apt-get install libhdf5-dev
pip install h5py
```
I remove the dependencies to h5py, so you can anyway run TFLearn without h5py (actually it is onlu useful if using hdf5 data, so this shouldn't be required).
You can reinstall TFLearn, this should words:
```
pip uninstall tflearn
pip install git+https://github.com/tflearn/tflearn.git
```

**Comment by DarylWM** [comment]
I uninstalled h5py, and uninstalled and reinstalled TFLearn, but when I import tflearn I get:
```
>>> import tflearn
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
hdf5 not supported (please install/reinstall h5py)
```

**Comment by aymericdamien** [comment]
Seems that uninstalling and reinstalling haven't fix the issue, but you should be able to use tflearn now, just hdf5 data will not be supported. Do you need to use it?

You may try this if you need HDF5 support: http://stackoverflow.com/questions/34119670/hdf5-library-and-header-mismatch-error?answertab=active#tab-top

**Comment by DarylWM** [comment]
Yes I can use tflearn now - thanks. I haven't needed hdf5 yet.
