### ISSUE TITLE
Python3 UnicodeDecodeError in cifar10.load_data()

### ISSUE THREAD

**Issue by DarylWM** [tflearn/tflearn#57]
Running `python3 convnet_cifar10.py` gives this error:
```
File "/usr/local/lib/python3.4/dist-packages/tflearn/datasets/cifar10.py", line 55, in load_batch
    d = pickle.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 6: ordinal not in range(128)
```
Thanks to SO I got the tip to add an encoding that resolves the problem:
`d = pickle.load(f, encoding='latin1')`

**Comment by aymericdamien** [comment]
Thanks for notifying it, I will update the code!
