### ISSUE TITLE
conv_1d: TypeError: Expected list for attr squeeze_dims

### ISSUE THREAD

**Issue by SnowWalkerJ** [tflearn/tflearn#59]
in the func conv_1d:
`    343         inference = tf.nn.conv2d(inference, W, strides, padding)
    344         if b: inference = tf.nn.bias_add(inference, b)
--> 345         inference = tf.squeeze(inference, 3)
    346         inference = activations.get(activation)(inference)`
but tf.squeeze seems to accept only list type for the second parameter

**Comment by aymericdamien** [comment]
I will have a look to see what is wrong there. What were the dimension of your input data?

**Comment by SnowWalkerJ** [comment]
The input was [None, 360, 1]
The Tensoflow API says it should be tf.squeeze(inference, [3]) instead of tf.squeeze(inference, 3).
