### ISSUE TITLE
AlexNet 17 flowers example - No change in loss/accuracy while training

### ISSUE THREAD

**Issue by ArnoXf** [tflearn/tflearn#60]
Hi!
At first I want to say, I was very excited when I read about tflearn. I am currently writing a paper about image recognition with tensorflow and tflearn seems to be a great library for providing some examples easily. 

First I tried some examples, the cifar10 worked very well but I got stuck in the AlexNet (tflearn/examples/images/alexnet.py) example. After solving some problems with Pillow the network loaded and got trained. For training I am using a GTX 750 ti. After loading the images I got a couple of the following warning:

    W tensorflow/core/common_runtime/bfc_allocator.cc:213] Ran out of memory trying to allocate 
    342.38MiB. The caller indicates that this is not a failure, but may mean that there could be 
    performance gains if more memory is available.

But the network was trained afterwards. So I let it train for about 12 hours (last night) and was excited about the results in the morning. Unfortunately there was no big change in loss and accuracy. Loss is always somewhere around 2.8 and accuracy somewhere between 0.04 and 0.07.

Unfortunately I couldn't find any mistakes in building the net or loading the data, what led me to open an issue here. I didn't change any of the example code, do you have any idea why it isn't working?

Many thanks in advance,
Arno

**Comment by aymericdamien** [comment]
How did you install TensorFlow? Did you build for source with CUDA compute compatibility 3.0? or just regular pip install.
Regarding that memory issue, maybe you can try to lower the batch size, to see if network converge. When you start training, it should start to converge after few iterations.

**Comment by ArnoXf** [comment]
After installing CUDA Toolkit and cuDNN following the instruction on NVIDIAs docs page I installed TFs GPU-version using pip. According to NVIDIAs CUDA GPU table the GTC750ti has a compute capability 5.0

I reduced the batch size from 64 to 32 and now I don't get warnings anymore. Unfortunately, it still seem not to de-/increase:

    Training Step: 100  | total loss: 2.83280
    | Momentum | epoch: 002 | loss: 2.83280 - acc: 0.0646 -- iter: 0704/1224

**Comment by aymericdamien** [comment]
It appears that the 17 flowers dataset has issue. When I am trying on my Ubuntu machine, it is also not converging. Actually, it is because pictures get not loaded correctly, and thus arrays are just 0. Maybe it is similar issue for you? Can you print X[0], X[1], etc... to see if they are not only fill with 0 ?

**Comment by ArnoXf** [comment]
Yes, you are right. There seems to be an issue when leaving the files "oxflower17.py" and "data_utils.py" in the subfolders of tflearn (/usr/local/lib/pythonX.X/dist-packages/tflearn/) because of the passed path of images / pickle-file. After copying both files to the same folder of alexnet.py it worked for me so far, it compiles the images right to the pickle-file. Now I get the following results:

    Training Step: 124  | total loss: 1.79034
    | Momentum | epoch: 003 | loss: 1.79034 - acc: 0.3590 -- iter: 0224/1224

...and so on.

I think I'll have to play with the settings because I reduced the batch-size but its principally working.
Many thanks for giving me food for thought!

**Comment by aymericdamien** [comment]
Ok, I will patch it! About the example, you can set tensorboard_verbose=0 to speed up the training process.
