### ISSUE TITLE
Squeeze net

### ISSUE THREAD

**Issue by igorbpf** [tflearn/tflearn#613]
Does anyone  have a squeeze net pre-trained on ImageNet to be shared?

**Comment by aguang1201** [comment]
what about this？
https://github.com/aguang1201/squeezeNetSource?files=1

**Comment by igorbpf** [comment]
great, man! thanks a lot!

**Comment by aguang1201** [comment]
you are welcome


发自网易邮箱大师
On 02/19/2017 12:03, Igor Santos wrote:

great, man! thanks a lot!
