### ISSUE TITLE
tflearn.DNN ignores checkpoint_path setting unless set to "None"

### ISSUE THREAD

**Issue by H-SG** [tflearn/tflearn#617]
After upgrading to TensorFlow 1.0 and the latest release of tflearn from GitHub, any path I place for checkpoint_path in the model definition gets ignored and checkpoints are saved in the root folder where the code executes from. Setting checkpoint_path=None still has the expected result of no checkpoints being generated.

The issue did not exist when I was using TensorFlow 0.9 and tflearn 0.2.1. The exact code I used for the model definition is as follows:
```python
import tflearn as tfl
...
log_dir = "./logs/"
check_dir = "./checkpoints/"
model = tfl.DNN(target, tensorboard_verbose=3, tensorboard_dir=log_dir,
                checkpoint_path=check_dir, max_checkpoints=val_interval)
```

**Comment by aymericdamien** [comment]
Can you update to TFLearn 0.3 (current master) and see if that fix your issue?

**Comment by H-SG** [comment]
Unfortunately the issue is still apparent under 0.3.

**Comment by aymericdamien** [comment]
You have to input the full path: 
```python
check_dir = "./checkpoints/model.ckpt"
```

**Comment by H-SG** [comment]
Okay, that works. I suppose my code originally worked because of an error in earlier implementations of tflearn.
