### ISSUE TITLE
Activation scope error

### ISSUE THREAD

**Issue by novog** [tflearn/tflearn#621]
With tflearn 0.3 with tensorflow 1.0, I am encountering an error when trying to use PReLU or leaky ReLU activations. Consider the following code with three possible last steps:

    net1 = tflearn.input_data(shape=[None, 1000])
    net2 = tflearn.fully_connected(net1, 1000)
    #net3a = tflearn.relu(net2)
    net3b = tflearn.prelu(net2)
    #net3c = tflearn.leaky_relu(net2)

Assigning to net3a using relu works as expected. However, when trying to apply prelu or leaky_relu, I get an error like the following:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\python-3.5.2.amd64\lib\site-packages\tflearn\activations.py", line 229, in prelu
>     with tf.variable_scope(i_scope + name) as scope:
> TypeError: unsupported operand type(s) for +: 'VariableScope' and 'str'

activations.py includes the following relevant code in the prelu definition, with the last line being the one on which the error occurs:

    # If incoming Tensor has a scope, this op is defined inside it
    i_scope = ""
    if hasattr(x, 'scope'):
        if x.scope: i_scope = x.scope
    with tf.variable_scope(i_scope + name) as scope:

In the example code above, net2 does have a scope attribute, which is of type VariableScope. The last line attempts to concatenate this VariableScope object with the string name, which does not work. I also notice that the leaky_relu copy of this code uses name_scope, while prelu uses variable_scope. I'm new to TensorFlow, but I would think that the same logic should be used in both cases.

I tried a few simple corrections, but then received a new error a few lines later that the variable alphas already exists. Could someone fix these activations or point out what I am doing wrong? Thanks!

**Comment by aymericdamien** [comment]
Hi, thanks for reporting that bug. I refactored both activations. The reason leaky_relu has no variable so we use name_scope instead of variable_scope (but using 'variable_scope' would work too).
Please try again by installing latest TFLearn ```pip install git+https://github.com/tflearn/tflearn.git```
