### ISSUE TITLE
Bug with GRU using 3d input

### ISSUE THREAD

**Issue by aryopg** [tflearn/tflearn#626]
I got this error when implementing GRU cell : 

`TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.`

but when i use LSTM, it works like usual. Is there any idea what possibly happening with the code?

**Comment by aymericdamien** [comment]
Can you try again with master version of TFLearn? It should be working.
```
pip install git+https://github.com/tflearn/tflearn.git
```

**Comment by aryopg** [comment]
@aymericdamien Thanks for the reply. I still got the same error message and only when i'm using the gru cell. What else that i should do?

**Comment by aryopg** [comment]
i've found the solution for this problem, turns out i didn't upgrade the tensorflow to the latest version yet.
