### ISSUE TITLE
Load single layer weights?

### ISSUE THREAD

**Issue by wballard** [tflearn/tflearn#632]
I'm looking to do some more varied transfer learning scenarios with unsupervised pre-training, and want to be able to load specific layers weights. Any suggestion on how to do this?

**Comment by aymericdamien** [comment]
You can use these layer args:
- `trainable=False` for not updating weights of a layer while training
- `restore=False` to not restore the weights of a layer when loading a model
- `weights_init=... / bias_init=...`to initialize a tensor with a custom numpy array

**Comment by jdvala** [comment]
@aymericdamien while specifying weights and biases, it raises an exception 
`Exception: Invalid initialization: layer1_weights`
this is the code
this is where I am specifying I want weights and biases 
```
encoder_layer1 = tflearn.fully_connected(x,41,activation='relu',bias=True)
layer1_weights = encoder_layer1.W
layer1_bias = encoder_layer1.b
```
This is where I want to use them. 
`encoder = tflearn.fully_connected(encoder, 41,trainable = False,restore=False,weights_init='layer1_weights',bias_init='layer1_bias')
