### ISSUE TITLE
'module' object has no attribute 'mul' when using tf = 1.0

### ISSUE THREAD

**Issue by lykaust15** [tflearn/tflearn#633]
I got the following AttributeError when using tflearn combined with tf = 1.0

![image](https://cloud.githubusercontent.com/assets/19503832/23340304/f7e2e76e-fc44-11e6-905b-424acc76b680.png)

Much thanks in advance.

**Comment by aymericdamien** [comment]
Can you try to install latest version of TFLearn? It should fix that error.
```
pip install git+https://github.com/tflearn/tflearn.git
```
