### ISSUE TITLE
Issue with "Pull: Refactor code example within the Titanic tutorial #612"

### ISSUE THREAD

**Issue by EricPerbos** [tflearn/tflearn#656]
Setup: Anaconda 3.5, TF 1.0 on Win10, TFLearn bleeding edge per today, running on GTX 1080 + CUDA.

Issue with Pull https://github.com/tflearn/tflearn/pull/612: it breaks the code/tutorial for beginners so they can't replicate one of the predictions on Titanic's survival probability (Winslet > 0.92).
https://github.com/tflearn/tflearn/blob/master/tutorials/intro/quickstart.md

*********************************************************************
With the latest version (aka Refactored), the prediction for Winslet dropped/varied wildly from 0.20 to .65 approx, over dozens of runs, never exceeding 0.75 instead of 0.92 as per tutorial.

**After I reverted to the code pre-Refactored, the prediction for Winslet returned to 0.92 immediately.**

Current code (Refactored):
```
# Preprocessing function
def preprocess(passengers, columns_to_delete):
    # Sort by descending id and delete columns
    for column_to_delete in sorted(columns_to_delete, reverse=True):
        [passenger.pop(column_to_delete) for passenger in passengers]
    for i in range(len(passengers)):
        # Converting 'sex' field to float (id is 1 after removing labels column)
        passengers[i][1] = 1. if data[i][1] == 'female' else 0.
    return np.array(passengers, dtype=np.float32)
```

Older code (pre-Refactored):
```
# Preprocessing function
def preprocess(data, columns_to_ignore):
    # Sort by descending id and delete columns
    for id in sorted(columns_to_ignore, reverse=True):
        [r.pop(id) for r in data]
    for i in range(len(data)):
      # Converting 'sex' field to float (id is 1 after removing labels column)
      data[i][1] = 1. if data[i][1] == 'female' else 0.
    return np.array(data, dtype=np.float32)
```

I think the problem lies in this line in Refactored:
`passengers[i][1] = 1. if data[i][1] == 'female' else 0.`
It should be:
`passengers[i][1] = 1. if passengers[i][1] == 'female' else 0.`

Could someone test both versions to confirm ?

**Comment by EricPerbos** [comment]
Just created two pull requests on this issue:
https://github.com/tflearn/tflearn/pull/658
https://github.com/tflearn/tflearn/pull/659

**Comment by aymericdamien** [comment]
Thanks for sending PRs!
