### ISSUE TITLE
atrous_conv_2d failing if rate != 1

### ISSUE THREAD

**Issue by liob** [tflearn/tflearn#664]
Hi,

there seems to be a bug in the atrous_conv_2d if the rate is not 1. The rate gets converted to a list with 4 entries by utils.autoformat_kernel_2d (https://github.com/tflearn/tflearn/blob/master/tflearn/layers/conv.py#L338).  This leads to a "unsupported operand type" error when the tensorflow codes tries to substract 1: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/nn_ops.py#L976

This error only occurs on rates != 1 because the tf code checks if the rate is one and finishes before reaching the critical snippet: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/nn_ops.py#L954

**Comment by aymericdamien** [comment]
Thanks for reporting that issue, I just sent a PR to fix it!

**Comment by liob** [comment]
Tested and working as expected. Thank you.
