### ISSUE TITLE
Loading saved model and model-meta doesn't work

### ISSUE THREAD

**Issue by ArnoXf** [tflearn/tflearn#69]
Hi! Unfortunately, I still couldn't solve a big problem. It's very important to get a network with all its weights saved and then loaded from another program, so that its possible to train once and make predictions independently whenever needed. Saving the model with meta seems to work properly, the two files are created. Loading the model again won't work. I even tried to save and load model in the same program after my training has finished with the following code:

    from __future__ import division, print_function, absolute_import

    import tflearn
    from tflearn.layers.core import input_data, dropout, fully_connected
    from tflearn.layers.conv import conv_2d, max_pool_2d
    from tflearn.layers.normalization import local_response_normalization
    from tflearn.layers.estimator import regression

    import image_loader
    X, Y = image_loader.load_data(one_hot=True, shuffle=False)

    print(X.shape)

    # Build network
    input_layer = input_data(shape=[None, 224, 224, 3])

    conv1 = conv_2d(input_layer, 96, 11, strides=4, activation='relu')
    pool1 = max_pool_2d(conv1, 3, strides=2)
    network = local_response_normalization(pool1)

    conv2 = conv_2d(network, 256, 5, activation='relu')
    pool2 = max_pool_2d(conv2, 3, strides=2)
    network = local_response_normalization(pool2)

    conv3 = conv_2d(network, 384, 3, activation='relu')
    conv4 = conv_2d(conv3, 384, 3, activation='relu')
    conv5 = conv_2d(conv4, 256, 3, activation='relu')
    pool3 = max_pool_2d(conv5, 3, strides=2)
    network = local_response_normalization(pool3)

    fc1 = fully_connected(network, 4096, activation='tanh')
    dropout1 = dropout(fc1, 0.5)

    fc2 = fully_connected(dropout1, 4096, activation='tanh')
    dropout2 = dropout(fc2, 0.5)

    fc3 = fully_connected(dropout2, 2, activation='softmax')
    network = regression(fc3, optimizer='momentum',
                         loss='categorical_crossentropy',
                         learning_rate=0.01)

    # Training
    model = tflearn.DNN(network, checkpoint_path='model_ba.ckpt',
                        max_checkpoints=1, tensorboard_verbose=0)
    # n_epoch von 2000 auf 1 gesetzt
    model.fit(X, Y, n_epoch=1, validation_set=0.1, shuffle=True,
              show_metric=True, batch_size=32, snapshot_step=400,
              snapshot_epoch=False, run_id='ba_soccer_network')

    # Save the model
    model.save('my_model')

    # Load weights from saved model
    model.load('my_model')

Running the program, it always crashes with the error message (and a whole bunch of memory allocation warnings)

    tensorflow.python.framework.errors.ResourceExhaustedError: OOM when allocating tensor 
    with shape[12544,4096]

Can't explain that behaviour because it worked to train the network of the same size before without getting any error.

I also tried to load the model from another source-code where it didn't train before, so I just built up the same network without `model.fit()` and tried `model.load()` with the same error but a smaller shape:

    W tensorflow/core/framework/op_kernel.cc:900] Resource exhausted: OOM when allocating 
    tensor with shape[4096,4096]

What is it I don't get? Or is there an issue in `model.load()` maybe?
Thanks in advance

**Comment by aymericdamien** [comment]
It seems your memory is full. Are you training on GPU or CPU? It is indeed strange that you can train without memory issue but not load a network, maybe I suspect that TensorFlow use additional memory when restoring a model.

To save memory, remove dataset loading when you are predicting:
```
import image_loader
X, Y = image_loader.load_data(one_hot=True, shuffle=False)
```

And use:
```
from __future__ import division, print_function, absolute_import

import tflearn
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.conv import conv_2d, max_pool_2d
from tflearn.layers.normalization import local_response_normalization
from tflearn.layers.estimator import regression


# Build network
input_layer = input_data(shape=[None, 224, 224, 3])

conv1 = conv_2d(input_layer, 96, 11, strides=4, activation='relu')
pool1 = max_pool_2d(conv1, 3, strides=2)
network = local_response_normalization(pool1)

conv2 = conv_2d(network, 256, 5, activation='relu')
pool2 = max_pool_2d(conv2, 3, strides=2)
network = local_response_normalization(pool2)

conv3 = conv_2d(network, 384, 3, activation='relu')
conv4 = conv_2d(conv3, 384, 3, activation='relu')
conv5 = conv_2d(conv4, 256, 3, activation='relu')
pool3 = max_pool_2d(conv5, 3, strides=2)
network = local_response_normalization(pool3)

fc1 = fully_connected(network, 4096, activation='tanh')
dropout1 = dropout(fc1, 0.5)

fc2 = fully_connected(dropout1, 4096, activation='tanh')
dropout2 = dropout(fc2, 0.5)

fc3 = fully_connected(dropout2, 2, activation='softmax')
network = regression(fc3, optimizer='momentum',
                     loss='categorical_crossentropy',
                     learning_rate=0.01)

model = tflearn.DNN(network, checkpoint_path='model_ba.ckpt',
                    max_checkpoints=1, tensorboard_verbose=0)

# Load weights from saved model
model.load('my_model')
```
I think this should be working.

At last, if there are still problems, maybe reduce parameters of your network last layers to 2048 or 3092.

**Comment by ArnoXf** [comment]
Many thanks, reducing the layer size did it finally. Now I am able to load and predict independently!

**Comment by tushtinaryani** [comment]
Why does reducing layer size work?

**Comment by LeonMLh** [comment]
Do we have any other options to solve this problem?
I mean that reducing the layer size, in fact, changes the model. 
Or do we have any other ways to save and load the model instead of model.save and model.load?

**Comment by aliyasineser** [comment]
I trained Alexnet with 856 images and 2 class. I saved the model and  in another python code, I tried to load model. I got ResourceExhaustedError. I have GTX970M with 3GB memory.  My main memory is 16 GB and looks like clearly no effects on the training process. Can anyone help ?

**Comment by snapfinger** [comment]
Similar situation here. Surprised to see a model can be trained successfully but run into out-of-memory issue when loading it using same machine....

**Comment by zz2014** [comment]
Same problem here. 
With the same machine the training goes successfully, but run into OOM when loading it, even cleaned the session before loading it : 
```
K.clear_session()        
model = load_model(model_in_path)

```
Any solution without changing the layer size? Thanks very much!

**Comment by snapfinger** [comment]
@zz2014 Not sure about your problem but I checked my machine's processes and found there's another training running at the same time, and there's no problem loading the model after killing that process. FYI.
