### ISSUE TITLE
Invalid incoming layer

### ISSUE THREAD

**Issue by JayDeng2837** [tflearn/tflearn#697]
tried throwing a 4-D numpy array to a tflearn.conv_2d operator and got an 'Invalid incoming layer' error.

I tracked down the error message to the code block below in tflearn.utils.
the function expects input in the form of [np.array, list, tuple] while my input is a 'np.ndarray'.

However, in numpy np.array is just a function that generates an array object, and the type of any numpy array is actually 'numpy.ndarray'. Therefore, is this potentially a bug or am I missing something here?

```python
def get_incoming_shape(incoming):
    """ Returns the incoming data shape """
    if isinstance(incoming, tf.Tensor):
        return incoming.get_shape().as_list()
    elif type(incoming) in [np.array, list, tuple]:
        return np.shape(incoming)
    else:
        raise Exception("Invalid incoming layer.")
```

**Comment by aymericdamien** [comment]
Hi, you are right, there is a bug here. I will send a fix. Thanks for reporting!

**Comment by liguangfa** [comment]
I meet the same problem, are there any solutions please?
