### ISSUE TITLE
Difference between get_weights and example_layer.W

### ISSUE THREAD

**Issue by palashd11** [tflearn/tflearn#704]
What is the difference between retrieving weights using ```example_layer.W``` and using the ```model.get_weights``` method?

**Comment by aymericdamien** [comment]
They return the same weights. `example_layer.W` is more simple but not always available (for a few cases when a layer does not return a tensor), but `get_weights` should always be working.

**Comment by palashd11** [comment]
Hey, thanks for the reply.
