### ISSUE TITLE
tf.concat reordered arguments in tensorflow1.0

### ISSUE THREAD

**Issue by Ruslanmlnkv** [tflearn/tflearn#709]
I'm trying to use time_distributed layer, but I have an error:
```
    tflearn/layers/core.py
    645     except:
    646       x = list(map(lambda t: tf.reshape(t, [-1, 1]+utils.get_incoming_shape(t)[1:]), x))
--> 647     return tf.concat(1, x)

```
It was because in tensorflow1.0 was changed concat function.

> keyword argument concat_dim should be renamed to axis
> arguments have been reordered to tf.concat(values, axis, name='concat').

Arguments reordered in function "concat" (tf.concat(x, axis=1)) will fix this bug.

**Comment by aymericdamien** [comment]
Thanks for the PR!
