### ISSUE TITLE
tflearn.utils.autoformat_stride_3d

### ISSUE THREAD

**Issue by gioGats** [tflearn/tflearn#716]
[Docs](http://tflearn.org/layers/conv/#avg-pooling-3d) say that tflearn.layers.conv.avg_pool_3d should default to stride=[1,1,1,1,1].

Default for stride in the code is None.  No checking or default is done before sending None to tflearn .utils.autoformat_stride_3d.  This function handles ints or tuples/lists of ints, but not None type.

I think the following needs to be added before line 1267 in tflearn.layers.conv:
~~~~ 
if strides is None:
     strides = (1, 1, 1, 1, 1)
~~~~

It fixed my error at least.  May be needed in other pooling functions... (I didn't check)

**Comment by aymericdamien** [comment]
Thanks for reporting that issue! I am sending a fix.
