### ISSUE TITLE
Generate a unicode sequence on Python  2.7

### ISSUE THREAD

**Issue by yarongon** [tflearn/tflearn#728]
I use tensorflow (1.0.1) and tflearn (0.3) with Python 2.7
This is a code snippet from the function `generate`, in  `generator.py` (lines 220 - 228):
```python
	if type(sequence) == str:
	    generated += next_char
	    sequence = sequence[1:] + next_char
	    whole_sequence += next_char
	else:
	    generated.append(next_char)
	    sequence = sequence[1:]
	    sequence.append(next_char)
	    whole_sequence.append(next_char)
```
When `sequence` is `unicode`, the condition goes to the `else` part, and since `unicode` does not a method `append`, I get the following exception:
`AttributeError: 'unicode' object has no attribute 'append'`
Of course this does not happen in Python 3. To fix it, I suggest to simply add a condition to check if the sequence is of type `unicode`.

**Comment by aymericdamien** [comment]
Thanks for reporting that bug, I fixed it.
