### ISSUE TITLE
tflearn has dependency with PIL

### ISSUE THREAD

**Issue by DongjunLee** [tflearn/tflearn#73]
Hello. 
tflearn is cool!

I want to report a bug
I try [vgg_network.py](https://github.com/tflearn/tflearn/blob/master/examples/images/vgg_network.py) with my own dataset(street snap image)

```python
...
import tflearn
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.conv import conv_2d, max_pool_2d
from tflearn.layers.estimator import regression

import input_data
dataset = input_data.load_fashion_dataset()
...
```

then it can't load numpy array data.
i use this function for converting image file to numpy array.

```python
from PIL import Image
import numpy as np
...

def img2numpy_arr(img_path):
    return np.array(Image.open(img_path))
```

so i check this function and find ' Image.open(img_path) ' doesn't work. 

now, i try vgg_network.py like this:

```python
...
import input_data
dataset = input_data.load_fashion_dataset()
...
import tflearn
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.conv import conv_2d, max_pool_2d
from tflearn.layers.estimator import regression
```

**Comment by aymericdamien** [comment]
Hey, can you please send me the error message?
PIL is used for some pre-processing and utility functions in TFLearn.

**Comment by DongjunLee** [comment]
i test it on jupyter notebook.

```python
import tflearn
import numpy as np
from PIL import Image

img_path = "..."
Image.open(img_path)
```

Error log:
```python
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
/usr/local/lib/python2.7/dist-packages/IPython/core/formatters.pyc in __call__(self, obj)
    341             method = _safe_get_formatter_method(obj, self.print_method)
    342             if method is not None:
--> 343                 return method()
    344             return None
    345         else:

/usr/local/lib/python2.7/dist-packages/PIL/Image.pyc in _repr_png_(self)
    617         from io import BytesIO
    618         b = BytesIO()
--> 619         self.save(b, 'PNG')
    620         return b.getvalue()
    621 

/usr/local/lib/python2.7/dist-packages/PIL/Image.pyc in save(self, fp, format, **params)
   1656 
   1657         # may mutate self!
-> 1658         self.load()
   1659 
   1660         save_all = False

/usr/local/lib/python2.7/dist-packages/PIL/ImageFile.pyc in load(self)
    233         if not self.map and not LOAD_TRUNCATED_IMAGES and e < 0:
    234             # still raised if decoder fails to return anything
--> 235             raise_ioerror(e)
    236 
    237         # post processing

/usr/local/lib/python2.7/dist-packages/PIL/ImageFile.pyc in raise_ioerror(error)
     57     if not message:
     58         message = "decoder error %d" % error
---> 59     raise IOError(message + " when reading image file")
     60 
     61 

IOError: broken data stream when reading image file

Out[1] : <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=84x256 at 0x7FDF4DA8EC10>
```

**Comment by aymericdamien** [comment]
I think this is an issue with PIL, maybe try to update pillow.

**Comment by DongjunLee** [comment]
pillow version is 3.2.0.(latest)
so.. i reinstall pillow but, result is same.

**Comment by aymericdamien** [comment]
You can try to
```
sudo apt-get install libjpeg8-dev
```

And reinstall pillow

**Comment by DongjunLee** [comment]
libjpeg8-dev is already the newest version.

I also reinstall libjpeg8-dev and Pillow.
result is same.

My desktop's os is Ubuntu 14.04 LTS.
I will debug this problem.
When i figure it out, i'll tell you.

**Comment by aymericdamien** [comment]
Ok thanks!

**Comment by DongjunLee** [comment]
This problem is tensorflow's Issue.

[TensorFlow_0.8.0 somehow breaks PIL ? #2101](https://github.com/tensorflow/tensorflow/issues/2101)
[https://github.com/scikit-image/scikit-image/issues/2000](https://github.com/scikit-image/scikit-image/issues/2000)

Simple solution is 
```python
from PIL import Image
import tensorflow as tf
```
or
Use TensorFlow 0.7.1 version. (It is the 0.8.0 version's problem)

**Comment by panovr** [comment]
I can confirm this error when running alexnet.py with TensorFlow 0.8:
`Starting to parse images...
Traceback (most recent call last):
  File "alexnet.py", line 27, in <module>
    X, Y = oxflower17.load_data(one_hot=True)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/datasets/oxflower17.py", line 34, in load_data
    categorical_Y=one_hot)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/data_utils.py", line 227, in build_image_dataset_from_dir
    X, Y = image_dirs_to_samples(directory, resize, convert_gray, filetypes)
  File "/usr/local/lib/python2.7/dist-packages/tflearn/data_utils.py", line 210, in image_dirs_to_samples
    samples[i] = resize_image(samples[i], resize[0], resize[1])
  File "/usr/local/lib/python2.7/dist-packages/tflearn/data_utils.py", line 184, in resize_image
    img = in_image.resize((new_width, new_height), resize_mode)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1538, in resize
    self.load()
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFile.py", line 235, in load
    raise_ioerror(e)
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFile.py", line 59, in raise_ioerror
    raise IOError(message + " when reading image file")
IOError: broken data stream when reading image file
`
And import PIL before TensorFlow fixed this error.
