### ISSUE TITLE
Custom preprocessing not available?

### ISSUE THREAD

**Issue by Noahyt** [tflearn/tflearn#737]
I am trying to write a custom preprocessing function (image resizing).   I am running tflern v.03 and Tensorflow 1.0.1

My code:

```
def bin_img_prep(X):
    X = bin_ndarray(X,new_shape=(X.shape[0],50,50,1))
    return X

Real-time image preprocessing
img_prep = tflearn.ImagePreprocessing()
img_prep.add_custom_preprocessing(bin_img_prep)
```

Error:
`AttributeError: 'ImagePreprocessing' object has no attribute 'add_custom_preprocessing'`

**Comment by aymericdamien** [comment]
You need to use the master version of TFLearn: `pip install git+https://github.com/tflearn/tflearn.git`

**Comment by Noahyt** [comment]
@aymericdamien that worked!  

On a related note, now that it is running, my image resizing routine appears to not be working.  

The line 
`X = bin_ndarray(X,new_shape=(X.shape[0],50,50,1))` 

is throwing an error:

`AttributeError: 'list' object has no attribute 'shape'`

I am reading the input data from a hdf5 file (since it is too large to fit in memory).  When I ran this same code using a numpy array (part of the data written to the hdf5 file) it worked.  

Should I open a new issue for this?
