### ISSUE TITLE
DNN model.load() and model.save() Error

### ISSUE THREAD

**Issue by nimish1512** [tflearn/tflearn#738]
I am training a cnn using` model.fit()` and saving it using `model.save("tflearn.model")`
However, this creates 4 files:
1) tflearn.model.data-00000-of-00001
2) tflearn.model.meta
3) tflearn.model.index
4) checkpoint

While loading the model, which file should I use?

**Comment by aymericdamien** [comment]
This is TF Saver v2, you should use "tflearn.model"

**Comment by nimish1512** [comment]
But there is no .model file . My file explorer shows only the three files mentioned above.

**Comment by aymericdamien** [comment]
Yes, but TF just need the prefix `tflearn.model`, and it will load the 3 files.

**Comment by Noahyt** [comment]
`model.load("tflearn.model")`

**Comment by nimish1512** [comment]
Yup, that worked. Thanks alot
