### ISSUE TITLE
MemoryError when running convnet_cifar10.py

### ISSUE THREAD

**Issue by octy40** [tflearn/tflearn#751]
I'm getting a MemoryError when running the convnet_cifar10.py built-in example. It seems like the error is generated by tflearn.data_utils.shuffle(). Is anyone else experiencing this issue when running this example?

**Comment by aymericdamien** [comment]
It seems you are running out of RAM. Are you running on CPU? You can try to free-up some RAM by closing other applications.

**Comment by octy40** [comment]
That was the issue. I changed from a 4GB RAM to a 60 GB RAM and the problem went away. Thanks for the help.
