### ISSUE TITLE
Model accuracy on a new session

### ISSUE THREAD

**Issue by BBarbosa** [tflearn/tflearn#753]
Hi everyone!
I'm using _Tensorflow 1.0.1_ and _TFlearn 0.3_ on _Windows10_.

I came across with an issue about the model's accuracy. I have a script that trains and evaluates the network  repeatedly until it reaches a stop criteria. Then, it saves the trained model on a file so i can load it later.

If i load the trained model right after finishing the training (on the same session as the training) i get an accuracy (command prompt on the left). However, if i load it in other script (i think it creates a new session right?) the accuracy is totally different (command prompt on the right). It should be equal because the test set is exactly the same on the two situations.

Any ideias how can i solve this issue? Or what is it all about?

![log](https://cloud.githubusercontent.com/assets/7063937/26004406/a8ff8200-372d-11e7-846c-ff7b91045605.png)

**Comment by willduan** [comment]
Is there any code about your test set?

**Comment by BBarbosa** [comment]
Sure. 
`# computational resources definition
    tflearn.init_graph(num_cores=8,gpu_memory_fraction=0.4,allow_growth=True)

    # network definition
    network = input_data(shape=[None, HEIGHT, WIDTH, 3],     # shape=[None,IMAGE, IMAGE] for RNN
                        data_preprocessing=None,       
                        data_augmentation=None) 
     
   
    network = architectures.build_network(arch,network,classes)

    # model definition
    model = tflearn.DNN(network, checkpoint_path='models',
                        max_checkpoints=1, tensorboard_verbose=0) # tensorboard_dir='logs'
    
    print("Loading trained model...")  
    model.load(modelpath)
    print("\tModel: ",modelpath)
    print("Trained model loaded!\n")

    # load test images
    Xt,Yt = dataset.load_test_images(filename)

    _,test_acc,_,min_acc = classifier.classify_sliding_window(model,Xt,Yt,"run_id",classes,printout=False)
 
    print(colored("=============================","yellow"))
    print("Test:", test_acc, "%")
    print(" Min:", min_acc, "%") 
    print(colored("=============================","yellow"))
`

**Comment by BBarbosa** [comment]
@willduan I noticed right now that i forget to add the variables for **data preprocessing and augmentation** in this testing script on the **input_data** layer. Apparently it solved my issue.
