### ISSUE TITLE
Cannot install pillow on mac

### ISSUE THREAD

**Issue by LittleFollower** [tflearn/tflearn#77]
I have met this problem when I installed pillow with command line on mac. I got the following messages, can anyone tell me how to fix it? Thanks!

Running setup.py (path:/private/var/folders/_3/qkspw3tx10dcjy48q2fz05f40000gn/T/pip_build_tomhome/Pillow/setup.py) egg_info for package Pillow

    

    warning: no files found matching '*.sh'

    no previously-included directories found matching 'docs/_static'

    warning: no previously-included files found matching '.coveragerc'

    warning: no previously-included files found matching '.editorconfig'

    warning: no previously-included files found matching '.landscape.yaml'

    warning: no previously-included files found matching 'appveyor.yml'

    warning: no previously-included files found matching 'build_children.sh'

    warning: no previously-included files found matching 'tox.ini'

    warning: no previously-included files matching '.git*' found anywhere in distribution

    warning: no previously-included files matching '*.pyc' found anywhere in distribution

    warning: no previously-included files matching '*.so' found anywhere in distribution

Installing collected packages: Pillow

  Running setup.py install for Pillow

    

    warning: no files found matching '*.sh'

    no previously-included directories found matching 'docs/_static'

    warning: no previously-included files found matching '.coveragerc'

    warning: no previously-included files found matching '.editorconfig'

    warning: no previously-included files found matching '.landscape.yaml'

    warning: no previously-included files found matching 'appveyor.yml'

    warning: no previously-included files found matching 'build_children.sh'

    warning: no previously-included files found matching 'tox.ini'

    warning: no previously-included files matching '.git*' found anywhere in distribution

    warning: no previously-included files matching '*.pyc' found anywhere in distribution

    warning: no previously-included files matching '*.so' found anywhere in distribution

    Traceback (most recent call last):

      File "<string>", line 1, in <module>

      File "/private/var/folders/_3/qkspw3tx10dcjy48q2fz05f40000gn/T/pip_build_tomhome/Pillow/setup.py", line 767, in <module>

        zip_safe=not debug_build(), )

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup

        dist.run_commands()

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands

        self.run_command(cmd)

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command

        cmd_obj.run()

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run

        return orig.install.run(self)

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 563, in run

        self.run_command('build')

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command

        self.distribution.run_command(command)

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command

        cmd_obj.run()

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run

        self.run_command(cmd_name)

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command

        self.distribution.run_command(command)

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command

        cmd_obj.run()

      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 337, in run

        self.build_extensions()

      File "/private/var/folders/_3/qkspw3tx10dcjy48q2fz05f40000gn/T/pip_build_tomhome/Pillow/setup.py", line 512, in build_extensions

        ' using --disable-%s, aborting' % (f, f))

    ValueError: zlib is required unless explicitly disabled using --disable-zlib, aborting

    Complete output from command /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c "import setuptools, tokenize;__file__='/private/var/folders/_3/qkspw3tx10dcjy48q2fz05f40000gn/T/pip_build_tomhome/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/_3/qkspw3tx10dcjy48q2fz05f40000gn/T/pip-tOage5-record/install-record.txt --single-version-externally-managed --compile:

    running install

running build

running build_py

creating build

creating build/lib.macosx-10.6-intel-2.7

creating build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/__init__.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/_binary.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/_util.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/BdfFontFile.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/BmpImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/BufrStubImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ContainerIO.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/CurImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/DcxImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/DdsImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/EpsImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ExifTags.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/features.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/FitsStubImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/FliImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/FontFile.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/FpxImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/FtexImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/GbrImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/GdImageFile.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/GifImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/GimpGradientFile.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/GimpPaletteFile.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/GribStubImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/Hdf5StubImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/IcnsImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/IcoImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/Image.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ImageChops.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ImageCms.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ImageColor.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ImageDraw.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ImageDraw2.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ImageEnhance.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ImageFile.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ImageFilter.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ImageFont.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ImageGrab.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ImageMath.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ImageMode.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ImageMorph.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ImageOps.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ImagePalette.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ImagePath.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ImageQt.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ImageSequence.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ImageShow.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ImageStat.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ImageTk.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ImageTransform.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ImageWin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ImImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/ImtImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/IptcImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/Jpeg2KImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/JpegImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/JpegPresets.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/McIdasImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/MicImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/MpegImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/MpoImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/MspImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/OleFileIO.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/PaletteFile.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/PalmImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/PcdImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/PcfFontFile.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/PcxImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/PdfImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/PixarImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/PngImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/PpmImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/PsdImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/PSDraw.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/PyAccess.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/SgiImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/SpiderImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/SunImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/TarIO.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/TgaImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/TiffImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/TiffTags.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/WalImageFile.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/WebPImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/WmfImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/XbmImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/XpmImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

copying PIL/XVThumbImagePlugin.py -> build/lib.macosx-10.6-intel-2.7/PIL

running egg_info

writing Pillow.egg-info/PKG-INFO

writing top-level names to Pillow.egg-info/top_level.txt

writing dependency_links to Pillow.egg-info/dependency_links.txt

warning: manifest_maker: standard file '-c' not found

reading manifest file 'Pillow.egg-info/SOURCES.txt'

reading manifest template 'MANIFEST.in'

warning: no files found matching '*.sh'

no previously-included directories found matching 'docs/_static'

warning: no previously-included files found matching '.coveragerc'

warning: no previously-included files found matching '.editorconfig'

warning: no previously-included files found matching '.landscape.yaml'

warning: no previously-included files found matching 'appveyor.yml'

warning: no previously-included files found matching 'build_children.sh'

warning: no previously-included files found matching 'tox.ini'

warning: no previously-included files matching '.git*' found anywhere in distribution

warning: no previously-included files matching '*.pyc' found anywhere in distribution

warning: no previously-included files matching '*.so' found anywhere in distribution

writing manifest file 'Pillow.egg-info/SOURCES.txt'

copying PIL/OleFileIO-README.md -> build/lib.macosx-10.6-intel-2.7/PIL

running build_ext

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/private/var/folders/_3/qkspw3tx10dcjy48q2fz05f40000gn/T/pip_build_tomhome/Pillow/setup.py", line 767, in <module>

    zip_safe=not debug_build(), )

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup

    dist.run_commands()

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run

    return orig.install.run(self)

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 563, in run

    self.run_command('build')

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run

    self.run_command(cmd_name)

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 337, in run

    self.build_extensions()

  File "/private/var/folders/_3/qkspw3tx10dcjy48q2fz05f40000gn/T/pip_build_tomhome/Pillow/setup.py", line 512, in build_extensions

    ' using --disable-%s, aborting' % (f, f))

ValueError: zlib is required unless explicitly disabled using --disable-zlib, aborting

----------------------------------------

Cleaning up...

Command /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c "import setuptools, tokenize;__file__='/private/var/folders/_3/qkspw3tx10dcjy48q2fz05f40000gn/T/pip_build_tomhome/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/_3/qkspw3tx10dcjy48q2fz05f40000gn/T/pip-tOage5-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /private/var/folders/_3/qkspw3tx10dcjy48q2fz05f40000gn/T/pip_build_tomhome/Pillow

Storing debug log for failure in /var/folders/_3/qkspw3tx10dcjy48q2fz05f40000gn/T/tmpKMAV_5

**Comment by aymericdamien** [comment]
Did you try to use pip installer?
```
pip install pillow
```
If you can't install pillow, I suggest you use Anaconda python distribution (https://www.continuum.io/downloads), there are already many useful python libraries pre-installed.

**Comment by LittleFollower** [comment]
Hi,

Yes, I use the pip installer. And thanks I just fix the problem, there it
miss install zlib and link to it. I found a solution from github. I will
post it later.

Thanks again!

**Comment by aymericdamien** [comment]
oh yes, checking the error it just seems that zlib wasn't install:
```
sudo apt-get install zlib1g-dev
```
If you have any other issue, don't hesitate to open a new thread.
