### ISSUE TITLE
How to perform multi-regression with AlexNet?

### ISSUE THREAD

**Issue by disdaining** [tflearn/tflearn#780]
Any example on how to predict floating numbers from image features?

**Comment by willduan** [comment]
It seems that you don't read the images, you just read the files' name

**Comment by disdaining** [comment]
Oh that's quite basic.
Here is how i am loading the images.

```
train_file='trainData.txt'

# Build the preloader array, resize images to 227x227
X, Y = image_preloader(train_file, image_shape=(227, 227),   mode='file', categorical_labels=False,   normalize=False, grayscale=True, files_extension='.png')

```
and now get this error:
`ValueError: invalid literal for int() with base 10: '0.68'`

Where it is expecting an int value as a class label and my data format is like this:

images/1sasdasd3vvd1.png 0.68 0.37 0.3 0.46 0.4 0.37 0.17 0.25 0.31 0.13 0.61 0.3 0.26 0.26 0.55 0.34 0.27 0.38 0.59 0.02 0.51 0.41

The first column is the image path and the rest are remaining cols are the values which i want to train the system with and predict.

Please guide on how to setup this?

**Comment by willduan** [comment]
I guess maybe you can set:
```
categorical_labels=False
```
to 
```
categorical_labels=True
```

**Comment by disdaining** [comment]
Doesn't work, same error. please any other alternative??

**Comment by disdaining** [comment]
That doesn't work. same error.
I have managed to load data with custom functions:

```
def return_names(filename):
 f = open(filename); final = []; 
 x = f.read();
 x = x.split('\n')
 for i in range(0, len(x)-1):
  temp  = x[i].split(' ');
  final.append(temp[0:1]);
 for i in range(0, len(final)):
   final[i] = str (final[i]);
 return final

def return_labels(filename):
 f = open(filename); final = []; 
 x = f.read();
 x = x.split('\n')
 for i in range(0, len(x)-1):
  temp  = x[i].split(' ');
  final.append(temp[0:22]);
 for i in range(0, len(final)):
  for j in range(0, len(final[i])):
   final[i][j] = float (final[i][j]);
 return final

def myloadImages(myimageList):
	for i in range(len(myimageList)):
		path = myimageList[i]
		path = path[2:-2]
		images = np.array(Image.open(path))
		#print(path); exit();
	return images

x_train = return_names('flist.csv');
y_train = return_labels('labels.csv');

X = myloadImages(x_train);
Y = y_train
```
Now i get the shape error:
`ValueError: Cannot feed value of shape (50, 227) for Tensor 'InputData/X:0', which has shape '(?, 227, 227, 0)'`

All my images are of 227x227 dimensions.
