### ISSUE TITLE
Saving LSTM cell internal structure

### ISSUE THREAD

**Issue by yhalk** [tflearn/tflearn#794]
Hi all,

is it possible to save the gate values, cell state and hidden state over the course of the training?
I have tried adding a custom layer which  will save them, however it fails to do so, usually with errors like 

_You must feed a value for placeholder tensor 'InputData/X' with dtype float_
 
Thank you in advance!

**Comment by willduan** [comment]
if you want to get the custom layer's weight, you can just use like this example (https://github.com/tflearn/tflearn/blob/master/examples/basics/weights_persistence.py)
(https://stackoverflow.com/questions/41705315/using-a-custom-layer-to-define-connectivity-in-tensorflow-tflearn)
:
```
with tf.variable_scope(name = 'dense1', reuse = False):
         dense1 = tflearn.custom_layer(input_layer, my_function, args)
...........
gen_vars = tflearn.get_layer_variables_by_scope('dense1')
print(gen_vars)
```

**Comment by yhalk** [comment]
Thank you!
