### ISSUE TITLE
Unable to read RGB images in Tflearn

### ISSUE THREAD

**Issue by nimish1512** [tflearn/tflearn#819]
I am trying to train VGG model over CK+ dataset in Tflearn. However, using the image_preloader method, I am unable to read RGB images with each channel as a dimension of the tensor.Here is my code
This is the input layer for the network
`self.network = input_data(shape=[None, 224, 224, 3])`
This is the image_preloader call:
`self.train_images, self.train_labels = image_preloader("Dataset/sorted_set/", image_shape=(224,224), mode="folder", categorical_labels=True, normalize=False, filter_channel=False)`

The error I am getting is: 
`ValueError: Cannot feed value of shape (1, 224, 224) for Tensor "InputData/X:0', which has shape "(?, 224, 224, 3)"`

**Comment by furkanese** [comment]
Have you tried reshaping your image data like:
X = X.reshape([-1, 224, 224, 3])

**Comment by nimish1512** [comment]
I tried, but the error shows:
`AttributeError: 'ImagePreloader' object has no attribute 'reshape'`

**Comment by furkanese** [comment]
You can read data in additon to image_preloader as a hdf5 file
```
from tflearn.data_utils import build_hdf5_image_dataset
import h5py
dataset_file = 'filename'
filename = 'train_dataset_64.h5'
img_dim = 64
build_hdf5_image_dataset(dataset_file, image_shape=(img_dim, img_dim), mode='folder', output_path=filename,  categorical_labels=True)
h5f = h5py.File('train_dataset_%s.h5' % str(img_dim), 'r')
X = h5f['X']
Y = h5f['Y']
X = X.reshape([-1, img_dim, img_dim, 3])
```
Also, you can specify things like normalization and greyscaling and resizing as well.

**Comment by nimish1512** [comment]
It gives the error:
`AttributeError: 'Dataset' object has no attribute 'reshape'`

**Comment by willduan** [comment]
you should read this tutorial, (http://tflearn.org/data_utils/#image-preloader)
```
 filter_channel: `bool`. If true, images which the channel is not 3 should
            be filter.
```
It seems that the filter_channel should be set to `True`. Since it will filter images' channels which are not 3

**Comment by nimish1512** [comment]
@willduan thanks. Turns out, most of the images in CK+ were gray scale, hence the error.
