### ISSUE TITLE
How to clone DNN model object

### ISSUE THREAD

**Issue by BBarbosa** [tflearn/tflearn#824]
Hi everyone!
Is there any way of cloning a TFLearn's DNN model object? I'm trying to save the best status of it without using callbacks or saving it into a file but Python's copy functions (shallow copy and deep copy) don't seem to solve the problem. Any ideias? 
With the best regards

**Comment by Legor** [comment]
It sounds like you are looking for the snapshots of the model during training. Why not just use the snapshots that are written to the disk and load them when needed?

**Comment by BBarbosa** [comment]
Hi @Legor! Thank you for your response.
I will follow your advice. 
I didn't want to save on disk because it takes a few seconds in my PC. And then, a few more seconds to load it. However, once it does what I want, i will keep it that way by now.
With the best regards
