### ISSUE TITLE
Fine-tune with different number of classes

### ISSUE THREAD

**Issue by mhasnat** [tflearn/tflearn#83]
Hi,

I have trained a network where the FC layer (**name: fc1**) was trained with **50** classes. 

Now, I would like to fine-tune the above network by keeping all parameters and changing only FC layer (**name: fc1_mod**)number of classes as **100** (previously it was 50). My attempt to do this task failed with the following error message:

tensorflow.python.framework.errors.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [320,100] rhs shape= [320,50]

It appears that fine-tune is not possible if the number of parameters are changes. Is it possible to fix this issue. For example, in Caffe if I change the layer name, then the layer skipped the weights from pre-trained model and initialized randomly.

Thank you.

**Comment by aymericdamien** [comment]
I think it should be working, you just have to set 'restore=False' to layers you do not want weights to be restored (your last layer in your case).

**Comment by mhasnat** [comment]
Thank you for this answer. Yes, it works.

**Comment by mhasnat** [comment]
I have another question for fine-tuning. On of the layers of my CNN consists of **linear** activation. If I change it to **prelu** and set **restore=False**, then I get error message. Example is given below:

**Before:**
conv_52 = conv_2d(conv_51, 320, 3, activation='linear')

**Changed:**
conv_52 = conv_2d(conv_51, 320, 3, activation='prelu', restore=False)

**Error:**
... errors.NotFoundError: Tensor name "Conv2D_9/PReLU/alphas" not found in checkpoint files ...

Looking forward for a solution.

Thanks.

**Comment by aymericdamien** [comment]
Arf yes, it is because PReLU has inner variable. Can you try this to fix the issue:
```
for v in tf.trainable_variables():
  if "PReLU/alphas" in v.name:
    tf.add_to_collection(tf.GraphKeys.EXCL_RESTORE_VARS, v)

# Then load your model
```

**Comment by TrinhTUHH** [comment]
@aymericdamien @mhasnat , I have exactly the same problem. Is it correct that we should add 'restore=False' before pretraining the model and then delete it when we start training with our desired dataset? I did like this when pretraining Alexnet with ox 17flowers dataset (which has 17 classes), and then load the pretrained model (with weight_only = True) and start training with my own dataset which has 6 classes, but there's always the error: `Assign requires shapes of both tensor to match...`

**Comment by TrinhTUHH** [comment]
My bad, it works now :D, It should be the other way around!
