### ISSUE TITLE
Data augmentation modifies the original input data(?)

### ISSUE THREAD

**Issue by mubastan** [tflearn/tflearn#854]
When processing an input mini batch of images with data augmentation (e.g., random blur) during training, are the original images also modified? Normally, I would expect that a copy of each batch is processed at each iteration and the original images are not modified, otherwise, the transformations are accumulated and this is not expected.

Is this the case in tflearn? If it is, then it is very important and should at least be emphasized in the documentation.

I have been doing cross-validation and realized that the validation performance steadily drops at each cross-validation iteration, which was unexpected. Then, I provided the training with a new copy of the data at each CV iteration and the results improved significantly. However this is only a partial solution, if the original training data is overwritten/modified by data augmentation, since it gets accumulated at each epoch.

**Comment by aymericdamien** [comment]
Data augmentation is applied to a batch of images only once, it is not persistent and not cumulated. You can have a look here to see how that works: https://github.com/tflearn/tflearn/blob/master/tflearn/data_augmentation.py

**Comment by mubastan** [comment]
If the input `batch`  (in data_augmentation.py) is not a copy, but a reference to the training data, then it will be modified. Then, the question is whether it is passed as a copy or reference during training. One way to check is by comparing the training data before and after training to see if it is modified (I will try to check this when I have time).

**Comment by mubastan** [comment]
I have checked it: copied the training data and computed the difference after training with data augmentation. The difference is 0. That is, data augmentation does not modify the training data, as expected.
