### ISSUE TITLE
import error with latest tf version 1.2

### ISSUE THREAD

**Issue by stevewyl** [tflearn/tflearn#867]
I cannot import tflearn with tensorflow 1.2 version. 
I met with following errors:

  File "D:\Anaconda3\lib\site-packages\tflearn\layers\__init__.py", line 2, in <module>
    from .conv import conv_2d, max_pool_2d, avg_pool_2d, conv_1d, \
ImportError: cannot import name 'deconv_2d'

Maybe deconv_2d means tf.nn.conv2d_transpose. I'm not sure

**Comment by aymericdamien** [comment]
I am not having any issue with TF1.2. That is weird, deconv_2d is defined here: https://github.com/tflearn/tflearn/blob/master/tflearn/layers/conv.py#L648.
Can you try to use the latest tflearn version? 
```pip install git+https://github.com/tflearn/tflearn.git```

**Comment by stevewyl** [comment]
It's weird. I upgrade some related package of tensorflow and now it works. Thanks!

**Comment by dankdaddy** [comment]
step 1:  first check ur pants if see hair then ur good to go
step 2 : go to the anconda directory and give ur anaconda to it
step 3: go to te directory where u intalled python get oyut of it go to this pc type in system 32 if see annaconda in there its good delete the system 32 folder and create a new folder like that and add anaconda to 

it works 100000% of the time it worked for me
