### ISSUE TITLE
noob question on string colums as target column

### ISSUE THREAD

**Issue by michelson** [tflearn/tflearn#880]
Hello there,
I've a model in tflearn which is predicting an integer column on a data set, and is working fine
but what should I do if I want to get a string column ? something like

  `data = [1,1,"hello"], [0,0,"good bye"]`

  `test([.2,.2]) == "good bye" `

is possible to encode each string on the dataset and then return the most accurated string ? 
which path should I take ?

thanks

**Comment by Legor** [comment]
I think you would have to provide more information on what you want to achieve. 

For example If you have a limited amount of output strings it boils down to a classification problem where you could just predict a class id which may then be used as an index to your string dictionary. Or in more technical terms your target value is an int or a hot-encoded int vector and not really a string-type object.

However if you want to predict arbitray strings (sentences) which are connections of single words it is a much harder task in the field of natural languge processing (NLP). Without knowing your domain, in many NLP tasks they use LSTMs but as i implied it really depends on your concrete task.

Greetings

**Comment by michelson** [comment]
Hi @Legor , thanks for your reply

that's right I've a dataset with diagnosis reports which contains a "text" field and many structured attributes, so what I need is a program that could suggest those diagnosis texts on a given example , So yes I think the hot-encoded is the way to go.

How can I encode a text column ? when I try to process the csv I get:

```
from tflearn.data_utils import load_csv
data, labels = load_csv('out.csv', target_column=-1,
                        categorical_labels=True, n_classes=2000)
```
```
ValueError: invalid literal for long() with base 10: 'lorem ipsum ....'
```

**Comment by michelson** [comment]
ok, I converted my texts to integers and save the reference in other place. then I've use `predict_label` function to get the list of predicted labels. 

thanks!
