### ISSUE TITLE
Understanding Tensorflow/Tflearn LSTM input?

### ISSUE THREAD

**Issue by pbhatnagar3** [tflearn/tflearn#89]
I am trying to train a LSTM using glove embeddings
After reading through https://github.com/tflearn/tflearn/issues/8, I tried implementing it using the following code:

#### Reading and pre-processing data
![image](https://cloud.githubusercontent.com/assets/5567951/15376713/ac1e6ce0-1d0b-11e6-8760-add7c9a4cffd.png)

#### Setting up an LSTM and training
![image](https://cloud.githubusercontent.com/assets/5567951/15376755/e954b984-1d0b-11e6-8448-a777a96e45de.png)

#### but am getting the following error:
![image](https://cloud.githubusercontent.com/assets/5567951/15376784/0f754854-1d0c-11e6-87dd-5b745702f404.png)

I followed all the instructions that were highlighted in https://github.com/tflearn/tflearn/issues/8 and I do not understand why it is crashing. Can someone please help? :( 

Thanks a lot!

**Comment by aymericdamien** [comment]
Can you try to convert your sequence to a numpy array?
```
trainX, testX = np.array(trainX), np.array(testX)
trainY, testY = np.array(trainY), np.array(testY)
```

**Comment by pbhatnagar3** [comment]
Thanks for the quick reply. So this is what I have:

Since I want to feed in sentences, each containing 82 words vectors ( which are word mappings in glove) and there are 10,000 such sentences, my X ( variable that consists of all attributes is an np.array) which looks like the following: 
    
    X.shape = (10000, 82, 50)

and then I have the following definition for the LSTM:

 net = tflearn.input_data(shape=[None, 82, 50],name='input');
net = tflearn.lstm(net, 4100, return_seq=True);
net = tflearn.dropout(net,0.5);
net = tflearn.lstm(net, 4100);
net = tflearn.dropout(net,0.5);
net = tflearn.fully_connected(net, 2, activation='softmax');
net = tflearn.regression(net, optimizer='adam',
                         loss='categorical_crossentropy');

Here is the code. I have tried adding some print statements so that it might be easier to see what the dimensions and other variables look like.
![image](https://cloud.githubusercontent.com/assets/5567951/15401552/e7506c16-1da4-11e6-8893-221c28b3171b.png)
![image](https://cloud.githubusercontent.com/assets/5567951/15401594/1330efae-1da5-11e6-90a2-1c59143527b9.png)
![image](https://cloud.githubusercontent.com/assets/5567951/15401622/304ea11c-1da5-11e6-8d27-95b8e2f80505.png)

Given what I am trying to accomplish. Does this seem like the correct way to use tflearn?

Thanks for helping me out :) !

**Comment by aymericdamien** [comment]
Yes, it seems right, you parse every word into its glove vector representation, and feed sequences to the LSTM network. You can train to check performances, and tune your networks to find best parameters.

**Comment by pbhatnagar3** [comment]
I have tried different parameters but the loss is still blowing to NaN. I even set the learning rate to 0 ( just to check what was happening) and it did not work. :/ At this point, I am thinking that this might be an issue with my data.

Thanks so much for your help @aymericdamien. Just one last thing I wanted to ask/suggest: 

I do not see anything any bibTex/cite links on the tflearn website and I think that you should definitely add that as an option. :+1:  I would love to cite your library in my present and future work.

Finally, I will try contributing to the project as well as soon as I finish the stuff that I am working on. :)

**Comment by aymericdamien** [comment]
Thanks for your support :) Make a bibTex or link for citing the library is actually a good idea, I will add it to tflearn website.

**Comment by pbhatnagar3** [comment]
@aymericdamien, one more quick question. Given that I now have a trained model, I have a separate set of sentences that I want to feed forward into my trained model and get the resulting activations ( for each of the input sentence) at any layer and store them. Is there anyway to accomplish this?

**Comment by aymericdamien** [comment]
Can you check again? You actually should have 2 files: 'my_model' (binaries file) and 'my_model.meta' the network architecture info.

**Comment by vinayakumarr** [comment]
what exactly the above code does?

**Comment by pbhatnagar3** [comment]
@aymericdamien you are right. I think that the ipython notebook was just taking some time to save the second file: i.e. the .meta file was immediately saved but the other file (containing the model) would be saved after a few minutes. Thanks anyways! I am sorry for the confusion that my concern might have caused.

**Comment by pbhatnagar3** [comment]
hey @aymericdamien one quick question. I am using embedding like the following:

![image](https://cloud.githubusercontent.com/assets/5567951/15571930/969ce828-22f2-11e6-9535-7ee6d5ec3d3a.png)

Is there anyway that after I have trained the weights of the network that I can access the embeddings learnt?

Thanks so much for the help!

**Comment by aymericdamien** [comment]
Yes, to do so, you have to give a name to your layer:
```
net = tflearn.embedding(net, input_dim=20000, output_dim=128, name='my_embedding')
```
Then you can retrieve that layer variables using:
```
# tflearn.get_layer_variables_by_name returns a list of all variables of a layer
embedding_var = tflearn.get_layer_variables_by_name('my_embedding')[0]
```
Then, if you want to manipulate its content, you can use the tensorflow session of DNN model class `DNN.session`, or you can directly call `get_weights`:
```
model = DNN(...)
model.get_weights(embedding_var) # Return numpy array
```

**Comment by pbhatnagar3** [comment]
@aymericdamien If I already have a model saved, will I have to run it again in order to get the embeddings?

**Comment by aymericdamien** [comment]
Yes, you will have to load it first, so it can restore weights.

**Comment by pbhatnagar3** [comment]
@aymericdamien Thanks for all your help! I really appreciate it. 

Just one last thing that I want to know. Is there a way to visualize the model/architecture of the LSTM that we trained. I tried using the tensorboard but could not get it working with tflearn. I read online that it might be because my log file might be big but am entirely not sure what is happening. 

Finally, is it possible that once we reload the model by using model.load() that we can visualize it to get a image of how the model has been set up?

Thanks for the help! :+1:

**Comment by aymericdamien** [comment]
Yes, you can visualize it with, if your logs are very large, it may take some time to display:
```
tensorboard --logdir=/tmp/tflearn_logs/
```
you can also clean that directory to remove all your old logs, so it should display your model quickly.
What do you mean by visualizing it? When you load it, you can see it inside Tensorboard, if it is what you mean:
```
model.load(...)
tf.train.SummaryWriter("/tmp/tflearn", model.session.graph)
```

**Comment by pbhatnagar3** [comment]
@aymericdamien Thanks for the reply! Shouldn't this be `tensorboard --logdir=/tmp/tflearn/` since by following the command `tf.train.SummaryWriter("/tmp/tflearn", model.session.graph)`, we are saving the model in `tmp/tflearn` directory.

Finally, assuming that it should be   `tensorboard --logdir=/tmp/tflearn/`, I ran the command and waited but my model does not show up on tensorboard. And I also get the following message: 
![image](https://cloud.githubusercontent.com/assets/5567951/15786926/fd579e8c-2973-11e6-959b-49fec09e91e4.png)

when I look inside my tmp folder, the file is there: 
![image](https://cloud.githubusercontent.com/assets/5567951/15786944/161111a6-2974-11e6-9fc1-e4afd4bccd46.png)

I am not sure what is happening at this point? Any pointers @aymericdamien ?

**Comment by aymericdamien** [comment]
ops, yes, it should be:
```
tf.train.SummaryWriter("/tmp/tflearn_logs", model.session.graph)
```
Your file is 8M, maybe it is taking some time to process? I am not so sure why you can't see... It is strange! Maybe try to update TensorFlow and ultimately, when you reload your model, try to fit it for 0 epoch, to see if you can see your model in tensorboard...

**Comment by krayush07** [comment]
@pbhatnagar3 Hi, did you identify the issue of 'NaN' score on using pre-trained glove vector? 

@aymericdamien I have to load a pre-trained word embedding to LSTM model instead of training the embeddings. Is the way @pbhatnagar3 load glove embedding and skip the embedding layer, the way to achieve the case?

**Comment by aymericdamien** [comment]
Yes, this way is also right. You can do your pre-loading in python itself (map your sequence of words with your custom embedding), and then use tensorflow for model computation.

**Comment by aryopg** [comment]
I'm trying to implement this code :

net = tflearn.input_data([None, num_words_in_longest_sentence, 50])
net = tflearn.embedding(net, input_dim=word_count, output_dim=128, name="embedding")
net = tflearn.lstm(net, 128, dropout=0.8, dynamic=True)
net = tflearn.fully_connected(net, 2, activation='softmax');
net = tflearn.regression(net, optimizer='adam',
loss='categorical_crossentropy');

I'm getting an error in the embedding layer : 

`AssertionError: Incoming Tensor shape must be 2-D`

How to make the embeddding layer to get the input_data? Thanks

**Comment by krayush07** [comment]
@aryopg You are trying to feed 3D input to [tflearn.embedding](https://github.com/tflearn/tflearn/blob/master/tflearn/layers/embedding_ops.py#L46) which is incorrect.

**Comment by aryopg** [comment]
@krayush07 thanks for the reply, i wanted to replicate the code given by @pbhatnagar3 . He used this:

```
net = tflearn.input_data([None, 82, 50])
net = tflearn.lstm(net, 4100, dropout=0.8, dynamic=True)
```

If i want to add the embedding layer, what should i do first?

**Comment by aryopg** [comment]
@krayush07 @aymericdamien i can run my code after several fixes :
 Here's my final code : 
<img width="621" alt="screen shot 2017-02-23 at 5 36 32 pm" src="https://cloud.githubusercontent.com/assets/17272091/23255628/f8c9e766-f9ee-11e6-9d60-cde1afe0c458.png">
<img width="670" alt="screen shot 2017-02-23 at 5 37 32 pm" src="https://cloud.githubusercontent.com/assets/17272091/23255630/fa552bae-f9ee-11e6-9ad2-a1bdd46d3e26.png">
<img width="740" alt="screen shot 2017-02-23 at 5 38 00 pm" src="https://cloud.githubusercontent.com/assets/17272091/23255634/fd896fc4-f9ee-11e6-8771-41d4a7d3141f.png">
<img width="581" alt="screen shot 2017-02-23 at 5 38 29 pm" src="https://cloud.githubusercontent.com/assets/17272091/23255637/ff8def16-f9ee-11e6-92db-33b5257cc65e.png">
<img width="818" alt="screen shot 2017-02-23 at 5 38 40 pm" src="https://cloud.githubusercontent.com/assets/17272091/23255649/03768192-f9ef-11e6-8876-bd0af39fc6f0.png">
And i got and error in 'Gather ops', like this : 
```
Traceback (most recent call last):
  File "arg2glove.py", line 192, in <module>
    batch_size=32)
  File "/Users/aryopradiptagema/anaconda2/lib/python2.7/site-packages/tflearn/models/dnn.py", line 215, in fit
    callbacks=callbacks)
  File "/Users/aryopradiptagema/anaconda2/lib/python2.7/site-packages/tflearn/helpers/trainer.py", line 333, in fit
    show_metric)
  File "/Users/aryopradiptagema/anaconda2/lib/python2.7/site-packages/tflearn/helpers/trainer.py", line 774, in _train
    feed_batch)
  File "/Users/aryopradiptagema/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/Users/aryopradiptagema/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/Users/aryopradiptagema/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/Users/aryopradiptagema/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0] = -1 is not in [0, 8320)
	 [[Node: Gather = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Reshape, add)]]

Caused by op u'Gather', defined at:
  File "arg2glove.py", line 167, in <module>
    net = tflearn.lstm(net, 256, dropout=0.8, dynamic=True)
  File "/Users/aryopradiptagema/anaconda2/lib/python2.7/site-packages/tflearn/layers/recurrent.py", line 224, in lstm
    scope=scope, name=name)
  File "/Users/aryopradiptagema/anaconda2/lib/python2.7/site-packages/tflearn/layers/recurrent.py", line 84, in _rnn_template
    o = advanced_indexing_op(outputs, sequence_length)
  File "/Users/aryopradiptagema/anaconda2/lib/python2.7/site-packages/tflearn/layers/recurrent.py", line 765, in advanced_indexing_op
    relevant = tf.gather(flat, index)
  File "/Users/aryopradiptagema/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1359, in gather
    validate_indices=validate_indices, name=name)
  File "/Users/aryopradiptagema/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/Users/aryopradiptagema/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/aryopradiptagema/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): indices[0] = -1 is not in [0, 8320)
	 [[Node: Gather = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Reshape, add)]]
```

I really don't know what happen, i want to use an ibm debate dataset for some classification stuff.  Hope to see replies soon

**Comment by aryopg** [comment]
may i know your email @krayush07 so i can send you the code?

**Comment by bandarikanth** [comment]
I,am working on LSTM
can you send to my mail    :       bandarikanth810@gmail.com
