### ISSUE TITLE
Do you know how to install tflearn in pycharm?

### ISSUE THREAD

**Issue by gsw888** [tflearn/tflearn#895]
There is no ftlearn package in pycharm, so I installed it by "pip install tflearn", the installation is successful. However when I start using it, it always says "ImportError: No module named 'tflearn.data_utils'; 'tflearn' is not a package"
I use "pip show tflearn", I can see it is under:
Location: c:\users\geoff\anaconda3\envs\keras\lib\site-packages
I tried pip3 install tflearn as well but it didn't work since my pycharm doesn't have pip3.
The python compiler I am using are: 3.5.3
Any help is highly appreciated!

**Comment by poornagurram** [comment]
Pycharm is just an IDE it will not contain any package. you can actually configure the environment for Pycharm in preferences. that can either be your normal python or anaconda environment.From your problem, I can see that you have not configured it as anaconda environment.if you change the project interpreter to anaconda3 environment you will not get the error.

<img width="1000" alt="screen shot 2017-09-02 at 6 11 51 pm" src="https://user-images.githubusercontent.com/9065157/29995575-4751aae8-900a-11e7-95ae-4b4bfbe0bb4e.png">

**Comment by gsw888** [comment]
Thanks for your reply, I am using anaconda3 environment, here is the screen shot
![anaconda3](https://user-images.githubusercontent.com/31453111/29995607-57154284-8fe5-11e7-9fbd-0588afb06e20.png)

**Comment by gsw888** [comment]
I have python 3.6.1 as well but Pycharm is only working with python 3.5.3

**Comment by gsw888** [comment]
after installing the tflearn by "pip install tflearn", I still can't used it so I remove it.

**Comment by poornagurram** [comment]
use this command to install in anaconda `conda install -c derickl tflearn`

**Comment by gsw888** [comment]
I tried this as well but it didn't work either, here is the error:
"conda install -c derickl tflearn
Fetching package metadata ......
WARNING: The remote server could not find the noarch directory for the
requested channel with url: https://github.com/tflearn/tflearn
"
However I checked the url: https://github.com/tflearn/tflearn and it is valid.
I added the https://github.com/tflearn/tflearn into Pycharm "Manage Repositories" then refresh and I didn't see tflearn package is there either. Somehow the tflearn is not compatible with the Pycharm community edition 2017.2.2

**Comment by gsw888** [comment]
I reinstalled the tensorflow and tflearn. now it is working fine for me in pycharm.
The command I am using for tflearn is: pip install tflearn.
I used this before, it didn't work but this time after installation, I tried it first from the pycharm python console by import tflearn and it worked. Then I use it in pycharm for deep learning and it works fine too.

**Comment by royism** [comment]
I have problem installing tflearn using Anaconda3...have already installed tensorflow. Following are the errors while installing tflearn. Kindly, help me in this regard.
![screenhunter 05](https://user-images.githubusercontent.com/26703904/34096421-37adebca-e3fb-11e7-90aa-447d36b77a2f.png)

**Comment by gsw888** [comment]
First, make sure you have all the latest updates installed for pycharm;
Secondly, installing the tensorflow by conda  command as normal;
Thirdly, pip install tflearn
Then from the pycharm console and test ftlearn by:
import tflearn
it shall not show any error if you have correctly installed the package and the path was set correctly.
Then you can use tflearn in pycharm DEV.
This was what I did and it works fine for me now.

**Comment by royism** [comment]
Thank you for your reply. I have installed the latest updates for pycharm and have followed all the steps you mentioned. Still I got the error messages. Kindly, help me in that regard.

**Comment by ChanaLii** [comment]
> Thank you for your reply. I have installed the latest updates for pycharm and have followed all the steps you mentioned. Still I got the error messages. Kindly, help me in that regard.

you can try this command to install tflearn：
`pip install tflearn -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com`
