### ISSUE TITLE
How to save and restore network architektur in tflearn

### ISSUE THREAD

**Issue by tomalbrecht** [tflearn/tflearn#899]
I am looking for a way to save and restore a network-structure with tflearn. The embeded model.save takes care about the weights persistance. But in case I want to forget about the network structure and load it again, I have to build the net again. Therefore I have to "remember" the structure (layers, amount of neurons) and so on.

I've experimented with pickle (something like pickle.dump(net)) and tf.train.import_meta_graph (combine tflearn with tensorflow) without success.

Lets say I have a training like this:

```
`from future import division, print_function, absolute_import

import numpy as np
import tflearn

import tflearn.datasets.mnist as mnist

X, Y, testX, testY = mnist.load_data(one_hot=True)
X = np.reshape(X, (-1, 28, 28))

testX = np.reshape(testX, (-1, 28, 28))

net = tflearn.input_data(shape=[None, 28, 28])
net = tflearn.lstm(net, 128, return_seq=True)
net = tflearn.lstm(net, 128)
net = tflearn.regression(net, optimizer='adam',
loss='categorical_crossentropy', name="output1")
model = tflearn.DNN(net, tensorboard_verbose=2,tensorboard_dir='lstm')
model.fit(X, Y, n_epoch=1, validation_set=0.1, show_metric=True,
snapshot_step=100)

model.save('lstm_load.tflearn')`
```

Later I want to restore all needed stuff in a different program or session like this (pseudo-like code does not work of course ;-))

```
`from future import division, print_function, absolute_import

import numpy as np
import tflearn

import tflearn.datasets.mnist as mnist

X, Y, testX, testY = mnist.load_data(one_hot=True)
X = np.reshape(X, (-1, 28, 28))

testX = np.reshape(testX, (-1, 28, 28))

model = model.load_everything("model.tfl")
prediction = model.predict([X])`
```

Any ideas?

**Comment by tomalbrecht** [comment]
I'll switch to tf.keras now.

**Comment by crizzy9** [comment]
Facing the same issue. Any solutions within tflearn?

**Comment by tomalbrecht** [comment]
I use tf.keras now as high level API. In Tensorflow you would save the model like this:
https://www.tensorflow.org/api_docs/python/tf/keras/models/save_model
