### ISSUE TITLE
visualize the DNN error with tensorboard_berbose = 3

### ISSUE THREAD

**Issue by Fankbai** [tflearn/tflearn#906]
** code  :**
```python
model = tflearn.DNN(net, tensorboard_verbose = 3)
```
BUT TENSORBOARD SHOWS NOTHING(PIC 3 ) WHILE THE FOLDER WAS GOT THE events FILE LIKE PIC2. I TRY 
```powershell
tensorboard.exe --inspect  --event_file = E:\tmp\tflearn_logs\835CJT\
```
RETURN LIKE PIC 1
![2017-09-15_193327](https://user-images.githubusercontent.com/10338671/30480806-2f8a9a04-9a0b-11e7-9bff-1ac9ad66b76d.jpg)    
PIC 1

![2017-09-15_193537](https://user-images.githubusercontent.com/10338671/30480810-324effe6-9a0b-11e7-9c80-6cc14584a06f.jpg)   
 PIC2
![2017-09-15_193756](https://user-images.githubusercontent.com/10338671/30480807-308565f6-9a0b-11e7-9a5d-7049ce4dc15e.jpg)   
PIC3

**Comment by BBarbosa** [comment]
Hi @Fankbai! 
I think that the _--inspect_ parameters expects an event file and not a folder actually.
Can you try `tensorboard.exe --inspect  --event_file = E:\tmp\tflearn_logs\835CJT\events.out.tfevents.1505...`?

**Comment by Fankbai** [comment]
@BBarbosa only open cmd up the \835CJT folder could it work. that's weired.
