### ISSUE TITLE
Is there a rule-of-thumb for choosing the number of units in an LSTM layer?

### ISSUE THREAD

**Issue by DarylWM** [tflearn/tflearn#92]
My time series input shape is (3000,30,1) and without any particular reason I use 300 units in my LSTM layer. Is there a rule-of-thumb for choosing the width?

**Comment by aymericdamien** [comment]
Hi, I do not think there is such rule-of-thumb. You may experimentally find out what is the best architecture for your data.
But I have read somewhere (I think from a study by Baidu Research) that using a units number multiple of 32 may actually speed up a little the training (When you dealing with float32). So usually, people will do as such when designing their RNN.

**Comment by DarylWM** [comment]
Thanks. I have found for my time series data that quite large numbers of units (1000-1200) optimises the loss more quickly and increases prediction accuracy, although it increases training time for each step quite a bit. Now I'm experimenting with a single LSTM layer versus several.

**Comment by scindew** [comment]
Hi. Did you found how many layers and Also how many epochs are more suitable for your model?

**Comment by asis-shukla** [comment]
Can anyone please explain the time series data. Like above given My `time-series input shape is (3000,30,1)` What this mean exactly? Like in simple pandas data frame if we have data shape something like (30000, 500) that means 30000 data points with each data point has 500 features.In the case of CNN we have (batch_size, width, height, channels).
