### ISSUE TITLE
Can't visualize the event on tensorboard

### ISSUE THREAD

**Issue by egg-west** [tflearn/tflearn#946]
Does it not work because I use tensorflow1.3 ?
I found there are event file in a directory in tflearn_logs, but I open tensorboard and get nothing.
Thanks to everybody sees this issue.

**Comment by egg-west** [comment]
I solve this myself, I miss the logdir path a '/' in the head

**Comment by zemu121** [comment]
How you set the paramter of tensorboard_dir and where you execute the command:tensorboard --logdir=path
Is your OS windows or Linux?

**Comment by zemu121** [comment]
You should open the url(lcoalhost:6006) by google chrome, I used to open it by firefox and it has nothing
