### ISSUE TITLE
Do I need to download the alexnet or vgg model for running the examples?

### ISSUE THREAD

**Issue by panovr** [tflearn/tflearn#97]
I'm reading the "Apply Alexnet to Oxford Flowers 17 classification task" and "Apply VGG Network to Oxford Flowers 17 classification task", I just wonder that do I need to download the alexnet or vgg model weight file for running these examples?

**Comment by aymericdamien** [comment]
You do not need to, the dataset will automatically be downloaded when you run the example script.

**Comment by guduxingzou** [comment]
the data_utils.py  "directory_to_samples" function  is not fit to this file  folder.I use this:
def directory_to_samples(directory, flags=None):
    """ Read a directory, and list all subdirectories files as class sample """
    samples = []
    targets = []
    label = 0
    
    #print('directory_to_samples',os.walk(directory))
    print('directory',directory)
    classes = sorted(os.walk(directory).next()[2])
    for sample in classes:
        #print('sample','--------')
        if not flags or any(flag in sample for flag in flags):
            samples.append(os.path.join(directory, sample))
            targets.append(int(label/80))
        label += 1    
    
    
    '''
    #以下是原文件的处理方式，我为了运行vgg路径改成了上面的形式，如果其他的程序需要
    #利用此函数需要更改过来
    #更改的原因是：应该有个类别文件夹，一个类别对应一个文件夹，类别文件夹下是图片。
    classes = sorted(os.walk(directory).next()[1])
    print('classess',classes)
    for c in classes:
        c_dir = os.path.join(directory, c)
        for sample in os.walk(c_dir).next()[2]:
            print('sample','--------')
            if not flags or any(flag in sample for flag in flags):
                    samples.append(os.path.join(c_dir, sample))
                    targets.append(label)
        label += 1
    '''
    targets[len(targets)-1]=16
    print(set(targets))
    print(samples[1])
    return samples, targets
