### ISSUE TITLE
Bidirectional rnn Throws Shape Error

### ISSUE THREAD

**Issue by selcouthlyBlue** [tflearn/tflearn#976]
I'm not sure if this is similar to this [issue](https://github.com/tflearn/tflearn/issues/818) but I encountered this error when I'm using tflearn's bidirectional_rnn:

`ValueError: Shape (48, ?) must have rank at least 3`

Here's the relevant code:

```
self.inputs = network_utils.input_data([None, self.num_time_steps, self.input_dimension], name="input")
... # label placeholders and whatnot
model = tflearn.input_data([None, 1596, 48])
model = bidirectional_rnn(model, BasicLSTMCell(50), BasicLSTMCell(50), return_seq=True)
... # loss and stuff
```

I'm using tensorflow 1.4 and tflearn 0.3.2

If you want to reproduce the error yourself, you can clone this [repository](https://github.com/selcouthlyBlue/simplified_bi_lstm_ocr) and run train.py

**Comment by selcouthlyBlue** [comment]
Nevermind. I found the reason for the error. I was passing a wrong input to self.inputs.

**Comment by sumyuck** [comment]
Hey, can you tell me the correct way of taking the input.
