### ISSUE TITLE
getting error in lstm

### ISSUE THREAD

**Issue by vinayakumarr** [tflearn/tflearn#99]
Getting the following error in LSTM recurrent neural network to classify IMDB
sentiment dataset
![untitled](https://cloud.githubusercontent.com/assets/18217467/15455194/4635f30e-206b-11e6-9056-ba683bd147b3.png)

**Comment by aymericdamien** [comment]
Can you please show me the code you used? It seem there is some problem in padding the sequence.

**Comment by vinayakumarr** [comment]
The error is solved by specifying dtype='float' in padding sequence

**Comment by aymericdamien** [comment]
ok, good to know :)
